### ISSUE TITLE
Long waiting on install profile

### ISSUE THREAD

**Issue by midyro** [OstlerDev/PopcornTV#10]
It's takes a long time to install the profile.

**Comment by midyro** [comment]
and I've got some errors

**Comment by OstlerDev** [comment]
It should not take more then 2-3 seconds to install the Profile, make sure you are pointing the DNS to the correct IP. What are the other errors?

**Comment by midyro** [comment]
Error: bind EADDRNOTAVAIL
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by OstlerDev** [comment]
Ok, so make sure to enter in your local IP. That error means that you are attempting to attach Popcorn TV to an incorrect IP. Are you using the local IP address of your computer? Please note that you should not use your public IP address but rather your local IP address. 

Follow these instructions and put your local IP address into your config.json file: http://lifehacker.com/5833108/how-to-find-your-local-and-external-ip-address

**Comment by OstlerDev** [comment]
@midyro let me know if that fixed the issue for you.

**Comment by midyro** [comment]
it's fixed ^_^

**Comment by OstlerDev** [comment]
Good to hear! Enjoy and be sure to report back any bugs, or put feedback on the forum page!

**Comment by kmanleafs** [comment]
I did everything u said....but still it takes forever to install the profile

**Comment by OstlerDev** [comment]
Make sure that you have entered in the DNS correctly to the Apple TV and that PopcornTV is still running in the background.

**Comment by kmanleafs** [comment]
So here is what the program says

C:\Users\krish\Desktop\PopcornTV>node atv.js
Starting PopcornTV
DnsProxy binding on 192.168.2.4:53
Web: listening on 192.168.2.4:80
SSL Web: listening on 192.168.2.4:443

I have entered 192.168.2.4 as my DNS on the apple tv....
And the profile i am installing is http://trailers.apple.com/trailers.cer

Still not working :/

**Comment by OstlerDev** [comment]
Is your Apple TV on the same network as the computer you are running PopcornTV on? Are you getting anything on the PopcornTV window? Or does it just stay like that?

**Comment by kmanleafs** [comment]
It is just staying like that, and yes they are connected to the same network

**Comment by OstlerDev** [comment]
Try to make sure that you are using the correct Local IP address, that could possibly be it.

**Comment by kmanleafs** [comment]
This is where I got my local IP from; Under "Wireless LAN adapter Wi-Fi" in ipconfig It says the local IP beside the IPv4 Address

**Comment by OstlerDev** [comment]
Are you also connected to an Ethernet cable as well?

**Comment by kmanleafs** [comment]
No, both the Apple TV and my computer r Wi-Fi as I do not have acess to Ethernet for both

P.S Thank you very much for the quick replies

**Comment by OstlerDev** [comment]
Try starting the Command Prompt in administrator mode and running PopcornTV that way. Another way that we can try is to add the certificate by using '192.168.2.4/trailers.cer' instead of 'http://trailers.apple.com/trailers.cer'

**Comment by kmanleafs** [comment]
Still not working....after sometime I get error -1001 on both methods

**Comment by OstlerDev** [comment]
What wifi-router are you currently using? Could you try using another computer?

**Comment by kmanleafs** [comment]
Belkin N300....different computer didnt work

**Comment by OstlerDev** [comment]
Please check to make sure all the following are met.

1. Confirm your Local IP address is the same as the IP address in config.json
2. Make sure that your computer AND Apple TV are on the EXACT same network
3. Make sure to set the Apple TV DNS to the Manual and use your Local IP address.
4. Make sure that PopcornTV is running when you attempt to add the profile.

When you change the DNS are you seeing something similar to this?
```
Starting PopcornTV
DnsProxy binding on 10.0.1.16:53
Web: listening on 10.0.1.16:80
SSL Web: listening on 10.0.1.16:443
DNS: local
```
The DNS: local being the important part that we want to keep an eye on.

Make sure that PopcornTV is running when you try to add the profile. Please also try to add using the IP address again.

The reason this might be happening is because your router might not support internal port forwarding. If your Apple TV is not on the EXACT same Wifi Network then it WILL NOT WORK.

**Comment by kmanleafs** [comment]
I do not see DNS: local.....

**Comment by OstlerDev** [comment]
I am thinking that the problem is one of the following from above:

1. You do not have the correct local IP address
2. You are on DIFFERENT wifi networks
3. You are not setting the correct DNS IP
4. You are not running PopcornTV when you attempt to install the profile.

Those are the most likely reasons as to why it is not working.

**Comment by kmanleafs** [comment]
Okay.....I did everything and checked everything....still no "DNS: Local"

**Comment by masonjames** [comment]
I did a pull request and updated to 0.1.4 master and now get the following:
Masons-MacBook-Pro:PopcornTV masonjames$ sudo node atv.js
Password:
module.js:338
    throw err;
          ^
Error: Cannot find module 'ip'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/masonjames/Desktop/PopcornTV/atv.js:3:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

I'm not sure how to debug that though :-/

I may try rolling back and seeing if everything works correctly.  I double-checked and the local json config file and the IP is still correct there.

**Comment by OstlerDev** [comment]
You need to run "sudo npm install" again to download the new package.

**Comment by kmanleafs** [comment]
Is there any way for me to get DNS: Local?

**Comment by OstlerDev** [comment]
Try doing a fresh install of the latest branch, that might possibly work. The "DNS: local" is not a requirement but can be a sign that we are pointing in the right direction.
