### ISSUE TITLE
Subtitles can't be loaded?

### ISSUE THREAD

**Issue by domidyon** [OstlerDev/PopcornTV#102]
Hi,

I can stream just fine, and until today I had subtitle support. Now, when I select subtitles it gives me no options. I reinstalled already, and yes, open subtitles.org loads fine on my laptop. So what is going on and how could I fix this?

Thanks

**Comment by OstlerDev** [comment]
It could have been that you ran too many queries today looking for subtitles, there is not much I can do to debug this other then to suggest that you wait until tomorrow and attempt to use subtitles again then.

If that does not work I will further debug your issue.

**Comment by domidyon** [comment]
I tried it like, 5 times today. On the first try it didn't show any results, so that shouldn't be the problem.

**Comment by OstlerDev** [comment]
Can you follow this guide so I can further understand the issue? https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue

**Comment by OstlerDev** [comment]
Fixed when updating to the latest commit (moving from iconv to iconv-lite)
