### ISSUE TITLE
Missing Module in latest push?

### ISSUE THREAD

**Issue by JakeRound** [OstlerDev/PopcornTV#103]
Current commit unable to start server, missing module?https://gist.github.com/JakeRound/6dea1df05986e0ab90be

**Comment by OstlerDev** [comment]
Winston is there: https://github.com/OstlerDev/PopcornTV/blob/master/package.json#L20

Did you make sure to run ``sudo npm install``?

**Comment by JakeRound** [comment]
Whoops, sorry that was a silly mistake. It's getting late over there in the UK haha.

**Comment by OstlerDev** [comment]
You are perfectly fine!
