### ISSUE TITLE
Extra info on subtitles list

### ISSUE THREAD

**Issue by leoravagnani** [OstlerDev/PopcornTV#106]
Is it possible to add locale info on the subtitles list so we can pick correctly between choices that look the same on the current UI? 

eg: it currently shows two "Portuguese" options, ideally it would show both "Portuguese" (meant for people from Portugal and some other countries) and "Portuguese - Brazil" (meant for Brazilians, duh haha). Both are very different and having to guess which to choose every time gets frustrating.

Thanks!

(off-topic: is there a way to change the subs language while playing?)

**Comment by OstlerDev** [comment]
What Locale info are you looking for?

No there is no way to change subtitles while playing, this is a limitation of the Apple TV.

**Comment by leoravagnani** [comment]
Just as noted on my example above, something to distinguish between variations of a language.
"Portuguese" and "Portuguese - Brazil" are both shown as "Portuguese" currently

**Comment by OstlerDev** [comment]
If you take a look in lang.js you can see the two lines where "Portuguese" is referenced. 

https://github.com/OstlerDev/PopcornTV/blob/master/lang.js#L529
https://github.com/OstlerDev/PopcornTV/blob/master/lang.js#L749

If you would like me to change one of those to further reflect "Portuguese - Brazil" let me know. I was not the one that created that file.

**Comment by leoravagnani** [comment]
Oh great! The last one should be changed (line 749)
I suggest changing the nativeName also, as follows:

"pb":{
		"name":"Portuguese - Brazil",
		"nativeName":"Português - Brasil"
	}


Thanks for the quick replies, really great job done so far!
