### ISSUE TITLE
Issue with subtitles

### ISSUE THREAD

**Issue by aDoStereo** [OstlerDev/PopcornTV#107]
First of all i wanted to thank you for your hard work. All your answers through the wiki really help me. 

Now i want to report a bug so you can improve your project, i'm from a Spanish speaking country, and if the subtitles have accent (not sure how to say it in english) they appear with this ? symbol even the ¿ appears with ? symbol.

Example:

```
* How it is:Tendr?as un ej?rcito tan mono que no podr?a ser atacado.
* How it should be: Tendrías un ejército tan mono que no podría ser atacado. 

```

also the word ñ, and the symbol ¿ appear with ? symbol

here are some pics so you can see the symbol

!
![unnamed 1](https://cloud.githubusercontent.com/assets/13308642/8644645/4b7e9788-2906-11e5-80f2-9c12da5d7fab.jpg)
![unnamed](https://cloud.githubusercontent.com/assets/13308642/8644646/4b91cd30-2906-11e5-959b-4487bf27840b.jpg)

**Comment by OstlerDev** [comment]
Sadly this is not something that I can fix (with my current knowledge) if you take a look here #68 you can see further on.

I have marked this as "Won't Fix" for now because after testing I did not find a way to fix this issue.
