### ISSUE TITLE
fatal error : cannot start DNS server

### ISSUE THREAD

**Issue by Dragenum** [OstlerDev/PopcornTV#109]
So I was pretty much handling the installation, last thing I did is changing the IP address on config.json to my IP. But now when I type atv.js in cmd, I get this message:

C:\Users\Matis\Desktop\popcorntv [master]> node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 23.233.252.156:53
Web: listening on 23.233.252.156:80
Web: SSL Web: listening on 23.233.252.156:443
error: ========= FATAL ERROR =========
error: Cannot start DNS Server. Please make sure you are using the correct IP!
error: Error Code: EADDRNOTAVAIL
error: ===============================

I checked and my IP address is correct. Thank you for the help

**Comment by OstlerDev** [comment]
You do not need to change it to your public IP, the installer actually sets it to the local IP you should use. Just delete ``config.json`` and start it up without stopping it.

**Comment by Dragenum** [comment]
Thank you so much for developping this app and for answering all our stupid questions! You are an incredible person :)
