### ISSUE TITLE
Cannot Create Certificate on Windows

### ISSUE THREAD

**Issue by OstlerDev** [OstlerDev/PopcornTV#11]
When attempting to generate the certificates on Windows it gives the following error: 

```
C:\Users\Username\Desktop\PopcornTV>node atv.js
SSL Certificate does not exist, Please restart PopcornTV once the process ends!
C:\Users\Username\Desktop\PopcornTV\atv.js:9
        fs.writeFile('assets/certificates/trailers.cer', keys.certificate+ '\n
                                                             ^
TypeError: Cannot read property 'certificate' of undefined
    at C:\Users\Username\Desktop\PopcornTV\atv.js:9:62
    at C:\Users\Username\Desktop\PopcornTV\node_modules\pem\lib\pem.js:238:24
    at C:\Users\Username\Desktop\PopcornTV\node_modules\pem\lib\pem.js:202:20
    at C:\Users\Username\Desktop\PopcornTV\node_modules\pem\lib\pem.js:754:20
    at C:\Users\Username\Desktop\PopcornTV\node_modules\pem\lib\pem.js:733:13
    at done (C:\Users\Username\Desktop\PopcornTV\node_modules\pem\lib\pem.js:674:
21)
    at ChildProcess.<anonymous> (C:\Users\Username\Desktop\PopcornTV\node_modules
\pem\lib\pem.js:691:13)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

Possibile Solution:
This could be happening because OpenSSL is not installed. If someone could try to install OpenSSL and report back their findings. (Link to install OpenSSL: http://slproweb.com/products/Win32OpenSSL.html )

**Comment by kmanleafs** [comment]
I'm having the same problem....downloading OpenSSL did not work

**Comment by OstlerDev** [comment]
Here is a workaround you can follow temporarily.

Step 1. Run the following command in the Command Prompt. Please note that you need to run CMD in administrator mode. Please make sure to install OpenSSL from the original post.
```sh
C:\OpenSSL-Win32\bin\openssl.exe req -new -nodes -newkey rsa:2048 -out C:\trailers.pem -keyout C:\trailers.key -x509 -days 7300 -subj "/C=US/CN=trailers.apple.com" -config C:\OpenSSL-Win32\bin\openssl.cfg
```
Step 2. Next, run this command
```sh
C:\OpenSSL-Win32\bin\openssl.exe x509 -in C:\trailers.pem -outform der -out C:\trailers.der
```
Step 3. Finally run this (the word "type" is part of the command, paste this entire command into your cmd prompt)
```
type C:\trailers.key >> C:\trailers.pem
```

Once you have that done, copy the three files it created and put them in the certificates folder (found in assets/certificates/)

Can someone try this and report back?

**Comment by kmanleafs** [comment]
Done tried it.....no difference made Here is the result

C:\Users\krish\Desktop\PopcornTV>node atv.js
SSL Certificate does not exist, Please restart PopcornTV once the process ends!
C:\Users\krish\Desktop\PopcornTV\atv.js:9
        fs.writeFile('assets/certificates/trailers.cer', keys.certificate+ '\n
                                                             ^
TypeError: Cannot read property 'certificate' of undefined
    at C:\Users\krish\Desktop\PopcornTV\atv.js:9:62
    at C:\Users\krish\Desktop\PopcornTV\node_modules\pem\lib\pem.js:238:24
    at C:\Users\krish\Desktop\PopcornTV\node_modules\pem\lib\pem.js:146:24
    at C:\Users\krish\Desktop\PopcornTV\node_modules\pem\lib\pem.js:67:20
    at C:\Users\krish\Desktop\PopcornTV\node_modules\pem\lib\pem.js:754:20
    at C:\Users\krish\Desktop\PopcornTV\node_modules\pem\lib\pem.js:733:13
    at C:\Users\krish\Desktop\PopcornTV\node_modules\pem\lib\pem.js:640:20
    at C:\Users\krish\Desktop\PopcornTV\node_modules\pem\lib\pem.js:786:20
    at F (C:\Users\krish\Desktop\PopcornTV\node_modules\pem\node_modules\which\w
hich.js:40:25)
    at E (C:\Users\krish\Desktop\PopcornTV\node_modules\pem\node_modules\which\w
hich.js:43:29)

**Comment by OstlerDev** [comment]
Did you put the files in the PopcornTV certificates folder? If you did it should bypass the generation. What are they named? There should be three files, trailers.cer, trailers.pem, and trailers.key

**Comment by kmanleafs** [comment]
oops! One is named "Trailers.der" rather then "Trailers.cer" i'll rename it and try it

**Comment by kmanleafs** [comment]
It works! Thanks man!

**Comment by OstlerDev** [comment]
Awesome! I will close this and add a "Windows Install" page to the wiki.

**Comment by kmanleafs** [comment]
Just to point out......In the instructions provided above, it says "-out C:\trailers.der" rather then "-out C:\trailers.cer". I want to point this out and make sure other people dont make a mistake!

**Comment by OstlerDev** [comment]
@kmanleafs I did not realize that! I will go and fix it now so that nobody else messes up on accident because of bad instructions. Thanks for bringing it to my attention c:

**Comment by ADMNTK** [comment]
![default](https://cloud.githubusercontent.com/assets/12907809/8180133/88d898be-1424-11e5-9958-d37be4a028c8.png)

help me plz ,

**Comment by hachox** [comment]
que estoy haciendo mal??...ayuda por favor...
![sin titulo](https://cloud.githubusercontent.com/assets/12968054/8255604/b8d947b8-1666-11e5-8d35-3318f9723767.png)

**Comment by rjrobinson** [comment]
Is there a workaround with mac?

**Comment by OstlerDev** [comment]
It will automatically generate for Mac, or at least it should. I will check into it.

**Comment by OstlerDev** [comment]
The generation still works fine on Mac, what OS version are you on?

**Comment by luisgsm** [comment]
i don't fully understand. I did start CMD as administrator. my question is about the first command
C:\OpenSSL-Win32\bin\openssl.exe req -new -nodes -newkey rsa:2048 -out C:\trailers.pem -keyout C:\trailers.key -x509 -days 7300 -subj "/C=US/CN=trailers.apple.com" -config C:\OpenSSL-Win32\bin\openssl.cfg
we have to paste this in CMD??????? 
nothing happen check the image 
![cmd](https://cloud.githubusercontent.com/assets/13733949/9176429/47945b58-3f59-11e5-9929-1992ce1d3dfa.jpg)

**Comment by kayohenriquemd** [comment]
i dont know how but it generated automatically for Windows when i installed... didnt have to do the workaround... is that ok? Sems that subtitles dont load properly i mean some movies wont load all list of languages. some wont load any list but just a "off" button... does that relate to not following the tutorial above or its a known issue?
