### ISSUE TITLE
Stuck on add profile page

### ISSUE THREAD

**Issue by Seb137** [OstlerDev/PopcornTV#110]
Hi
I have same problem than others adding profile on ATV.
I checked my config.json file who include:
{
    "ip": "192.168.1.18",
    "default_dns": "8.8.8.8"
}
DNS are normal 8.8.8.8?
Thank you

**Comment by JHFreeman** [comment]
8.8.8.8 is google's public dns server

**Comment by JakeRound** [comment]
Are you unable to add the profile? Make sure you've set the DNS on your apple TV to manual and type in  192.168.1.18, then try adding the profile are you given an error?

**Comment by Seb137** [comment]
Hi Jake,
Thank you for input
Yes I did set DNS to manual and enter 192.168.001.018 and when adding profile, a long time (around 5 minutes) elapse and I get an error message: "An error has occurred when adding the profile [-1001]. Check the URL an try again" (screenshot attached)

I tried both URL http://trailers.apple.com/trailers.cer and http://192.168.1.18/trailers.cer
I tried to delete certificates (trailers.cer and trailers.pem) and re-create them with 'node atv.js' command

Anything else I can try?
Thank you guys

![image](https://cloud.githubusercontent.com/assets/13299729/8681747/85285e74-2a69-11e5-936b-eea22b525bca.png)

**Comment by OstlerDev** [comment]
@Seb137 are you still running PopcornTV using ``sudo node atv.js``? This error could be happening becase you are not running PopcornTV.

**Comment by Seb137** [comment]
Yes, Popcorn TV is running on the Mac

**Comment by OstlerDev** [comment]
Are you seeing any output in the terminal when you attempt to add the certificate?

**Comment by Seb137** [comment]
In my previous attempts yes, terminal showed (some iTunes and Apple stuff).
Since I restart from scratch (delete certificate etc...) nothing more in the terminal than the 3 lines with my IP address

**Comment by JHFreeman** [comment]
If you go to System Settings->Security & Privacy->Firewall does it take Firewall: On?

**Comment by OstlerDev** [comment]
That means that the DNS might not be changing correctly. The long wait shows that it cannot get the file, which either means the DNS is entered incorrectly on the Apple TV  or not at all.

Try deleting ``config.json`` and allow it to regererate with a new IP.

Also attempt what @JHFreeman has mentioned.

**Comment by Seb137** [comment]
@JHFreeman Firewall is OFF
@OstlerDev here are the operations I did:
- after reading another issue I stopped Apache Server
- deleted config.json and change my IP address (24 now)
- deleted certificates (cer and pem)
- stopped and launched Popcorn Time
- node atv.js to regenerate certificate and config.json (I checked IP address is 192.168.1.24 and I reserved it in my router settings)

I got this:
iMac:PopcornTV maison$ sudo node atv.js
Password:
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.24:53
Web: listening on 192.168.1.24:80
Web: SSL Web: listening on 192.168.1.24:443

But profile still not adding.
Is there a way via terminal to check my 53, 443 and 80 ports are OK to Popcorn Time?
Thank you both of you

![image](https://cloud.githubusercontent.com/assets/13299729/8684994/038b719a-2a7c-11e5-853a-0d65e586fbf6.png)
![img_2256](https://cloud.githubusercontent.com/assets/13299729/8685269/cfbebc58-2a7d-11e5-97fa-d1a1134f372a.JPG)
![img_2257](https://cloud.githubusercontent.com/assets/13299729/8685281/de3fa44a-2a7d-11e5-9028-5212ef5ae323.JPG)

**Comment by JHFreeman** [comment]
to check port 80 use your browser to connect to http://192.168.1.24
to check port 443 use https
How is your Apple TV connected to the router? Ethernet or Wi-fi?

**Comment by OstlerDev** [comment]
Try opening up your web browser and going to the IP that it shows, it should load something like "index.html was not found on this server" but you will still see something in the console. If you see something in the console that means you correctly bound to the IP address and it's rather an issue with the Apple TV.

If the page waits to load that means you are binding to the wrong ip for some reason.

Let me know your results.

**Comment by OstlerDev** [comment]
Looks like @JHFreeman beat me to it

**Comment by Seb137** [comment]
Hey guys thank you for your enthusiasm supporting me!

Apple TV is connected via Ethernet
In Chrome port 80 seems to be ok
port 443, I don't know because of security alert and 'https' red crossed

When I attempted check ports, I got this in the terminal (seems good according to @OstlerDev):
iMac:~ maison$ cd Desktop/
iMac:Desktop maison$ cd PopcornTV
iMac:PopcornTV maison$ sudo node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.24:53
Web: listening on 192.168.1.24:80
Web: SSL Web: listening on 192.168.1.24:443
Web: /index.html
Web: 404: /index.html
Web: /favicon.ico
Web: 404: /favicon.ico
Web: SSL: /index.html
Web: SSL 404: /index.html
Web: SSL: /favicon.ico
Web: SSL 404: /favicon.ico
Web: SSL: /index.html
Web: SSL 404: /index.html

![image](https://cloud.githubusercontent.com/assets/13299729/8695839/399936e8-2ae8-11e5-93ee-6a0a63d23aa4.png)
![image](https://cloud.githubusercontent.com/assets/13299729/8695885/801524ce-2ae8-11e5-8479-1545a1f11bf3.png)

**Comment by Seb137** [comment]
I'ts amazing, it's working :dancers: 
Thank you guys!!

**Comment by Seb137** [comment]
One more thing: do I have to run terminal each time with sudo node atv.js command or running PopcornTime is enough?
Thank you

**Comment by JHFreeman** [comment]
'sudo node atv.js' has to be running at all times while using your atv unless you change the dns back to automatic

**Comment by Seb137** [comment]
is there a way to run this command at computer login?

**Comment by JHFreeman** [comment]
I would follow these directions ( http://developernotes.com/archive/2011/04/06/169.aspx ) but replace 'emacs --daemon' with '/usr/bin/sudo /usr/local/bin/node ~/Desktop/PopcornTV/atv.js'

**Comment by gnmfcastro** [comment]
Hello i'm having the same issue Seb137 how did u solve this?

**Comment by Seb137** [comment]
Hi,
I discovered I had installed a tiers firewall on my Mac (noobproof) years ago.
I just turned down all the rules and that's it.
Hope it'll help you

Envoyé de mon iPad
