### ISSUE TITLE
[Potential Idea] Storing own Shows / Movies?

### ISSUE THREAD

**Issue by JakeRound** [OstlerDev/PopcornTV#111]
Storing own shows / movies would be a nice addition, maybe shown as a separate listing on the Libraries  page ( I renamed it Browse, just sounds better ) However i assume fetching meta data might be a slight issue. It's kind of a incorporation of the whole plex connect idea however i want the features of PopcornTV as a priority. 

As i think @OstlerDev said they both can't run simultaneously as they're pretty much bases off each other and use the same ports?

**Comment by OstlerDev** [comment]
I don't think that this is something that I will be adding, I will be implementing PlexConnect compatability which will kind of sort this out. It feels like a feature that would be nice, but does not fit in with the idea of the application.

**Comment by JakeRound** [comment]
Okay thanks for a response anyway, its not essential it would just be a nice.  I didn't realise you were planning on implementing Plex Connect?

**Comment by OstlerDev** [comment]
Well I am not planning on implementing their features, but rather a bridge to allow their code to work in tandem.

**Comment by JakeRound** [comment]
Ah right understood, not particularly essential since both API's pretty much store almost all TV shows anyway.
