### ISSUE TITLE
Search problems

### ISSUE THREAD

**Issue by leoravagnani** [OstlerDev/PopcornTV#112]
I tried searching for a TV Show and it wouldn't return anything, so I looked on terminal and it says there's an error retrieving from the API, and the warning keeps coming up and nothing else loads anymore.

Also, sometimes the search won't work, even if I put the whole movie name, no results are shown.

Here's the terminal:
<img width="697" alt="screen shot 2015-07-14 at 23 44 10" src="https://cloud.githubusercontent.com/assets/13058201/8689844/718a08a8-2a83-11e5-9928-b06669d08687.png">

**Comment by OstlerDev** [comment]
What happens if you attempt to access [this?](http://eztvapi.re/shows/1?keywords=game%20of%20thrones)

Also, sometimes if you type too fast it will not pull up results, I believe this happens because it does not cancel the old query first.

**Comment by OstlerDev** [comment]
@leoravagnani Are you still having these issues?

**Comment by leoravagnani** [comment]
Just saw your replies and tested again and I still get the error.

Attempting the link gives me a 500 Internal Server Error.

**Comment by OstlerDev** [comment]
Do you by chance live in the UK? There is a known issue because some UK web providers block the API.

**Comment by leoravagnani** [comment]
Nope, I'm in Brazil... as far as I know we don't have these kind of block issues as in the UK

**Comment by OstlerDev** [comment]
Are you able to view the TV Shows in the Desktop application of Popcorn Time?
