### ISSUE TITLE
detect iOS version remove media bages if iOS is lower then iOS 6

### ISSUE THREAD

**Issue by wahlmanj** [OstlerDev/PopcornTV#113]
Receiving validation error on tv while using aTV2 iOS 5.3 when visiting any content for example: 

http://trailers.apple.com/Movies/MoviePrePlay.xml?torrentID=4282&UDID=DCYG9P34DDR5

Element 'additionalMediaBadges': This element is not expected.

--------------------------------------------------

Can there be a iOS detection be put in place when the aTV on lower is revisions cannot support the media badges?

**Comment by OstlerDev** [comment]
I did not realize that the media badges were not supported in <=5.3 I will add that into the code soonish.

**Comment by wahlmanj** [comment]
Line 814, 1027, 1497, 1670 in XMLGenerator.js seems to be the culprit.

**Comment by georgel** [comment]
Or is it possible to set this in a config? I have a couple all running on 5.3 :) Thanks for the great work. Brilliant idea :)

**Comment by OstlerDev** [comment]
I just need to add a catch in, I will do this soon.

**Comment by wahlmanj** [comment]
I totally forgot to ask this when I opened this issue, my apologies. Is it also possible to add this option into the settings tab as well? I also spoof all my aTV2's for A LOT of additional apps while jailbroken on iOS 5.3 and the auto detection won't work for this or PlexConnect (unless using my theme afaik for PlexConnect). I added a similar option in my fork of PlexConnect to allow for the additional apps.

**Comment by OstlerDev** [comment]
The only thing against adding it to the settings is firstly that it would add clutter where none is really needed, your case is very specific and I doubt anybody else has their aTV setup that way. So it is really just clutter vs benefit, if there were enough people that were having the same issue I would say sure, but seeing as how it is isolated and I believe it should be as simple as possibile I will not be adding it to the settings menu.

I will however check the settings for that setting. So if you manually add something such as ``version: 5.3`` to aTVSettings.json then it will take that version instead. Does that sound like a good compromise?

**Comment by wahlmanj** [comment]
Sounds good to me :+1:

**Comment by OstlerDev** [comment]
There you go, I just added this in commit 88c20b8b07577ec51cdd7989f340c9a841f111ba

Just add ``"version": 5.3,`` to your aTVSettings.json file.

If you need this added for the seasons fanart page as well let me know.

**Comment by wahlmanj** [comment]
Ok got it to work on iOS 5.3 :) Had to use this tho:

"version": "5.3",

Now I can enjoy the PlexConnect app directly installed on my aTV2 , PopcornTV running on my MBP feeding the trailers app. All of this on the go while my aTV is spoofed with a lot more non iOS 5.3 apps. No more swapping my server back and forth since the aTV2 hosts PlexConnect for me. Thanks man, really appreciate it :) Keep up the good work :+1:

**Comment by OstlerDev** [comment]
You are very welcome! Glad that I could come up with a simple fix for you.

**Comment by wahlmanj** [comment]
This will make vacations and out of town visits simple as $hit. ;)
