### ISSUE TITLE
PopcornTV not starting

### ISSUE THREAD

**Issue by Uokereh** [OstlerDev/PopcornTV#114]
Has anyone else come across this issue before, this is my first time experiencing it.

![screen shot 2015-07-15 at 9 52 34 pm](https://cloud.githubusercontent.com/assets/12503400/8713824/e584bc5e-2b3b-11e5-9de9-2424f98fb0c7.png)

**Comment by OstlerDev** [comment]
Try deleting ``config.json`` and letting it regenerate.

**Comment by Uokereh** [comment]
let me give that a shot and see if it works

**Comment by Uokereh** [comment]
that worked but it seems like every time i have to delete the config.json file before starting popcornTV

**Comment by OstlerDev** [comment]
That might be because your IP keeps changing every 24 hours. Try assigning a static IP to your computer in your router, or changing how long IP's will last.
