### ISSUE TITLE
I can not install the certificates and popcorntv in win 7

### ISSUE THREAD

**Issue by diogosmiranda** [OstlerDev/PopcornTV#116]
when I create the certificate error ( WARNING : can't open config file: /usr/local/ssl/openssl.cnf ) and thus can not install popcorntv ( npm install) the error

**Comment by OstlerDev** [comment]
Update to the latest version and try again.

**Comment by diogosmiranda** [comment]
Repeat the installation process with the last update and when I type (npm
install) the error and creates a file (npm-debug.log) in PopcornTV folder.
The file is attached

2015-07-16 19:17 GMT-03:00 Skylar Ostler <notifications@github.com>:

**Comment by OstlerDev** [comment]
You did not attach the file, can you upload it?

**Comment by diogosmiranda** [comment]
![npm-debug](https://cloud.githubusercontent.com/assets/6942182/8761792/cddf767a-2d39-11e5-8415-70a40949d682.png)

**Comment by diogosmiranda** [comment]
my apple tv 3 ( A1469 ) with this ios 7.2 ( 7512 )

**Comment by OstlerDev** [comment]
@diogosmiranda if your issue has not already been resolved, please try completely reinstalling.

**Comment by Xalcker** [comment]
I had this problem with 64bit OpenSSL used 32bit and worked fine.
