### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by sweetw0r** [OstlerDev/PopcornTV#117]
No ability to use iPhone keyboard wile search.

**Comment by OstlerDev** [comment]
I just tested this and it works perfectly fine for me, be sure that you have entered the text box.

**Comment by sweetw0r** [comment]
I just double checked. Keyboard doesn't show up on iPhone 6 Plus/8.4  Screen keyboard works well. Once I check iPhone 6 will let you know

**Comment by sweetw0r** [comment]
Works today. Will keep eye on it.

**Comment by OstlerDev** [comment]
Sure, thanks for bringing it to my attention.
