### ISSUE TITLE
Continue watching 

### ISSUE THREAD

**Issue by sweetw0r** [OstlerDev/PopcornTV#119]
Quite to main menu then return and be able to continue watching from the moment where user left it

**Comment by OstlerDev** [comment]
This feature will be coming along with Trakt.tv integration. It is currently unimplemented because the seek function is also unimplemented.

**Comment by OstlerDev** [comment]
Opening this back up because of the needed torrent seek function.

Thanks for reporting all of these things, it is good to bring attention to them.

**Comment by OstlerDev** [comment]
Will be added with Trakt.tc Integration.
