### ISSUE TITLE
assets/js/settings.js missing

### ISSUE THREAD

**Issue by w1nterl0ng** [OstlerDev/PopcornTV#12]
The Settings.xml file is making a dead call to http://trailers.apple.com/js/settings.js
Not sure if this file was never added, or if it is missing. 404 Error showing in the logs.

**Comment by w1nterl0ng** [comment]
I made a pull request to resolve this.  Feel free to close it if you pull.

**Comment by OstlerDev** [comment]
I have taken a look at the pull request and commented. Have you tested this in production and gone to the settings page? I want to make sure that it will not crash if you run it like that. In the future we will need to do some work on implementing the settings page and making it actually work.
