### ISSUE TITLE
The age of Adeline 

### ISSUE THREAD

**Issue by sweetw0r** [OstlerDev/PopcornTV#120]
Not able to find this movie. Watched on popcorn using android app a week ago.

**Comment by OstlerDev** [comment]
We pull our movies from Yts.to, if they do not have the movie, then we do not have the movie. Are you sure you were using the popcorntime.io version and not the timeforpopcorn version?

**Comment by sweetw0r** [comment]
It was http://popcorn-time.se/

**Comment by OstlerDev** [comment]
I would suggest taking a look [here,](https://www.reddit.com/r/PopCornTime/comments/2lyxnm/time4popcorn_popcorntimese_now_includes_adware_do/) popcorn-time.se has Malware included in it (from what I understand). This project is a version of [http://popcorntime.io](http://popcorntime.io)

That is why we do not have that content.

**Comment by sweetw0r** [comment]
Interesting! Thanks) Unfortunately popcorntime.io doesn't have iOS app yet
