### ISSUE TITLE
Progress [$15]

### ISSUE THREAD

**Issue by sweetw0r** [OstlerDev/PopcornTV#121]
Hard to understand if user is getting some downloading progress. Would be helpful to see some buffering in percentage

**Comment by OstlerDev** [comment]
This is a planned feature, however buffer percentage may never be implemented. What most likely will be implemented is a screen that tells the user what is happening.

The buffer percentage most likely would require to query the whole time.

**Comment by OstlerDev** [comment]
Will most likely implement this by adding a ``progress.json`` page that is queried for updates until it is ready to stream. This should also fix the play timeout ( #2 )

**Comment by OstlerDev** [comment]
Do not update to the current commit, it breaks playback currently, however this is the progress of what it looks like currently:
![](https://cloud.githubusercontent.com/assets/1490586/9028265/7ad7eca2-3930-11e5-9926-8d0c1fd1aabf.jpg)

**Comment by JakeRound** [comment]
Very nice job @OstlerDev

**Comment by OstlerDev** [comment]
@JakeRound I just need to finish implementing it for non-fanart views and TV shows then it is done! You can download now and test it out (on movies with fanart enabled)!

**Comment by JakeRound** [comment]
@OstlerDev Sure thing will do i'll let you know how it goes, hope the small contribution could help towards development. :smile:

**Comment by OstlerDev** [comment]
Every contribution helps towards the development :) the reason this got pushed higher on the priorities was in part by the bounty placed on this issue as well as your donation to the project. It helps when I know that I can spend a bit of Time on PopcornTV without having to worry about my financial situation as much.

I am implementing the converting status now.

**Comment by sweetw0r** [comment]
@OstlerDev Awesome! Good progress)

**Comment by OstlerDev** [comment]
@sweetw0r Glad that you like it! You can help us further this feature by submitting any bugs that you find in it.

**Comment by ZoneMR** [comment]
Thank you so much for implementing this - it makes a tremendous usability difference :)

**Comment by OstlerDev** [comment]
@ZoneMR Glad that you like it! It helps solve one of the large bugs which has been open since I started the project, I do wish I could have a clearer loading bar, but as far as I am aware there is nothing like that in the Apple TV XML.
