### ISSUE TITLE
Moving 'PopcornTV' folder

### ISSUE THREAD

**Issue by ssurfong** [OstlerDev/PopcornTV#123]
Hello,

I moved the 'PopcornTV' folder from my Desktop to the default 'Movies' folder in OSX (HD/Users/XXX/Movies). I got back to Terminal to type in 'sudo nom install' but it says 'no license field.' Am I missing a step or need to do something differently since moving the folder?

Thank you and great work on everything!

**Comment by ssurfong** [comment]
* I typed in 'sudo npm install' not nom FYI

**Comment by sweetw0r** [comment]
When I did same. I was forced to remove everything and reinstall the app from scratch to (cd /Users/youruser/Movies/) 
). Mostly it had meant for me that I needed to reset Apple TV as well
So the idea is to do everything like you did first time but not for Desktop folder

**Comment by OstlerDev** [comment]
Firstly, the "no license field" is just a warning, it does not really mean anything and the installation still continues. Just continue on as normal.

You do not need to reset the Apple TV.

**Comment by ssurfong** [comment]
I actually did restart the ATV. And now the Terminal just reads 'iMac:PopcornTV HD$'

Only the Computers and Settings icons are showing up on the ATV...

**Comment by OstlerDev** [comment]
Sounds like you are not still running PopcornTV, you need to be running it at all times. If you are not super technically savvy, you can try out an alpha build of the Desktop application here: http://ci.popcorntv.io/job/PopcornTV-Desktop/

The application is still very WIP, but should suit your needs.

**Comment by ssurfong** [comment]
My Popcorn TV bash in Terminal has been running the whole time. I just want to know what I need to do since I moved the original PopcornTV folder from my Desktop to the Movies folder.

**Comment by OstlerDev** [comment]
If you moved it to the movies folder, all you would need to do is change the command to get to the movies. So instead of running ``cd Desktop`` you would type ``cd Movies``

Or just type ``cd ~/Movies/`` which will take you right there, then follow the guide as normal.

**Comment by ssurfong** [comment]
Thank you both. Just needed help getting the 'cd ~/Movies/' right. 'cd Movies' didn't work earlier. All is well. Thank you again.

**Comment by OstlerDev** [comment]
No problem! If you need more help, feel free to hop on the IRC or open up another issue.

**Comment by ssurfong** [comment]
What is this PopcornTV desktop app BTW? Should we migrate to that instead?

**Comment by OstlerDev** [comment]
The Desktop App is a VERY basic piece of software right now that basically makes installing and running PopcornTV very simple, however it does not have a lot of features, such as FFMPEG conversion and log viewing. If you are looking to just run PopcornTV and don't want to have to worry about the Terminal, I suggest giving it a try.

Just keep in mind that right now it is likely to be very buggy, and it only has a couple features.

You can see screenshots of it here: https://github.com/OstlerDev/PopcornTV-App
