### ISSUE TITLE
hebrew subtitles are not shown properly

### ISSUE THREAD

**Issue by shali3** [OstlerDev/PopcornTV#124]
Hebrew subtitles are usually encoded with windows-1255 encoding. It looks like the apple TV is having trouble displaying them. The characters appear in weird question mark symbols. 

I would suggest re-encode the subtitles to UTF-8 or something like this on the server side to solve the issue. But I might be wrong.

Anyway, I hope you can fix it soon. let me know if you need anything from me.

Thanks

**Comment by OstlerDev** [comment]
This is a known issue, and currently I do not have any fixes for this #68

**Comment by shali3** [comment]
Thank for the prompt reply! :)

**Comment by shali3** [comment]
Hi @OstlerDev I've fixed this in #130
