### ISSUE TITLE
Arabic Subtitle

### ISSUE THREAD

**Issue by meo-in-silent-hill** [OstlerDev/PopcornTV#125]
hey guys
thank you very much for this great app. i have a problem with my arabic language it showing the subtitl not in arabic language but in some symbols not clear like there a problem with uincode or the font i'm not clear.

is that an issue or am i missing something.
thanks in advance

**Comment by OstlerDev** [comment]
Take a look at issue #68 for more info, it's a known bug that I cannot currently fix.
