### ISSUE TITLE
Issue! code: 'MODULE_NOT_FOUND' Please Help

### ISSUE THREAD

**Issue by disfin83** [OstlerDev/PopcornTV#131]
I'm on Mac and I installed node and restarted but I'm not sure if node is activated or not. This is the error that came up.

Users/rosienesilva/Desktop/PopcornTV/npm-debug.log
imac-de-rosiene-martins-silva:PopcornTV rosienesilva$ sudo node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 10.0.0.16:53
error: There is an error starting Popcorn TV, please post this on the Github page
{ [Error: Cannot find module 'popcorn-streamer'] code: 'MODULE_NOT_FOUND' }
imac-de-rosiene-martins-silva:PopcornTV rosienesilva$

**Comment by JakeRound** [comment]
Try rerunning

```
sudo npm install

**Comment by disfin83** [comment]
Thanks will do

**Comment by disfin83** [comment]
didn't work @JakeRound

**Comment by JakeRound** [comment]
@disfin83 Why not try the development build of the application @OstlerDev is working on?

http://ci.popcorntv.io/job/PopcornTV-Desktop/lastSuccessfulBuild/artifact/Mac.zip

**Comment by OstlerDev** [comment]
@disfin83 Can you post the entire log of what happens when you run ``npm install``?
