### ISSUE TITLE
"Playback error. Unable to download file fast enough, aborting stream attempt"

### ISSUE THREAD

**Issue by n3d1117** [OstlerDev/PopcornTV#132]
I get this error all the time, especially with TV Shows like Breaking Bad, although i am able to stream it fine with the desktop app. What should i do?

**Comment by OstlerDev** [comment]
This could be happening either because your internet is too slow or that it cannot download the torrent fast enough.

**Comment by n3d1117** [comment]
My internet is fine, and i can stream shows on my mac without problems. it's just my ATV that seems slowed down :(
