### ISSUE TITLE
Install corrections

### ISSUE THREAD

**Issue by omgsh** [OstlerDev/PopcornTV#134]
Step 1. Download Popcorn TV ((at this time it is still called Popcorn Time, the advice to change the name to PopcornTV comes in Step 2))or Clone the Repository. For ease of updating I suggest that you clone the repository, if you do not know how to do that then please follow this guide.

Step 2. Drag PopcornTV to your desktop ((again at this point it is still called popcorn time))(and extract it if you downloaded the zip). ((on mac there is no zip, just the ability to download the dmg, open it, see the drive inside the dgm and see the application within the drive.. what exactly are we to drag to the desktop and rename? The .dmg file? The Drive? The Application?)) Rename it "PopcornTV".
Step 3. Open Terminal and enter the commands below.

I'm lost here as terminal displays errors after following the above steps. I am very new to Mac OS

**Comment by OstlerDev** [comment]
You did not download PopcornTV. It looks like you downloaded Popcorn Time. PopcornTV is a completely separate application, on the right hand side of github there is a zip download, however I HIGHLY suggest installing via git by following this guide: https://github.com/OstlerDev/PopcornTV/wiki/How-to-Clone-the-Project
