### ISSUE TITLE
Node/Sudo Processes

### ISSUE THREAD

**Issue by ssurfong** [OstlerDev/PopcornTV#135]
Hello,

Issue 1: I don't have a ton of RAM in my machine, but it seems like just recently my comp has been thoroughly slowed down and when I open up Activity Monitor, 'node' is taking up a bunch of % CPU even when I am not streaming anything. Just been doing this lately. Is there anything I can do besides restart? 

Issue 2: Who are these 'listeners' and what does it mean? From Terminal:

Web: /Movies/MoviePrePlay.xml
(node) warning: possible EventEmitter memory leak detected. 11 open listeners added. Use emitter.setMaxListeners() to increase limit.

**Comment by OstlerDev** [comment]
In my testing unless you are actively converting a video you should only use around 100MB of ram total maximum. Secondly, I am not sure what the EventEmitter memory leak might be, can you post what version of node you are using?

**Comment by ssurfong** [comment]
Thanks for always replying quickly! Is this what you were looking for?

![screen shot 2015-07-26 at 9 38 52 pm](https://cloud.githubusercontent.com/assets/13172633/8898721/c372b2d2-33de-11e5-9e2d-aafbed4bf5f4.png)

**Comment by OstlerDev** [comment]
Wow, that really seems to be using up a whole ton of memory! Can you try restarting in debug mode and see if the issue persists? https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue

**Comment by ssurfong** [comment]
Now I'm getting this when I debug...
![screen shot 2015-07-26 at 11 40 55 pm](https://cloud.githubusercontent.com/assets/13172633/8899991/ceda439a-33ef-11e5-96f8-e720e8c6dce9.png)

**Comment by ssurfong** [comment]
I think I figured out the issue. I was running Popcorn Time on a laptop yesterday and left the app open all day. Could that be a reason why the lag was happening? Because I had PCT open on a laptop in addition to having PopcornTV open (but not streaming?)

**Comment by OstlerDev** [comment]
Popcorn Time does not need to run at the same time as PopcornTV, it is most likely Popcorn Time that is using up all that ram, try closing down Popcorn Time and see if that helps.

**Comment by ssurfong** [comment]
To clarify, my iMac runs PopcornTV and a separate laptop was running Popcorn Time. With those two apps open each machine it seemed like my iMac was running slow all day. I just quit out of the PCT running on the laptop and the iMac is seemingly running smoother because of it.

**Comment by OstlerDev** [comment]
That does not make sense if they were running on different computers, but if it worked great! Give it some testing and let me know how it goes.

**Comment by ssurfong** [comment]
My iMac is the hub for PopcornTV. I was just running PCT on the laptop in another room to view strictly on the laptop itself. Does that make sense? And would having those running consecutively (separate machines) cause the iMac to get sluggish i.e. the screenshot sent earlier?

**Comment by OstlerDev** [comment]
What I was meaning is that it does not make sense that it was having issues and slowing down, I understand that they are running separate. It is not possibile for the two different computers to really effect each other so I do not think it is anything with that.

I will look into the possibile memory leak.

**Comment by ssurfong** [comment]
Yeah, that wouldn't make any sense to me either, but it's running smoother now that PCT quit out from the laptop. Looking at the Activity Monitor, I no longer see the node or kernel_task spiking. I'll keep you updated with any other issues/findings.

**Comment by NicoSegoviaC** [comment]
I'm just running PopCorn Tv in my apple tv, and everything seems to works well, but wen i set the spanish subtitles the program crush down. This is the error:

Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
Web: /Movies/MoviePlay.xml
Streamer: Ready to Stream, binding to http://192.168.0.6:9999
Web: /subtitle.json
/Users/nicosegovia/Desktop/PopcornTV/SubtitleAPI.js:241
                        r: parseInt(color[1], 16)/255,
                                         ^
TypeError: Cannot read property '1' of null
    at /Users/nicosegovia/Desktop/PopcornTV/SubtitleAPI.js:241:42
    at Array.forEach (native)
    at /Users/nicosegovia/Desktop/PopcornTV/SubtitleAPI.js:194:18
    at /Users/nicosegovia/Desktop/PopcornTV/SubtitleAPI.js:133:25
    at /Users/nicosegovia/Desktop/PopcornTV/node_modules/xmlrpc/lib/client.js:130:9
    at callback (/Users/nicosegovia/Desktop/PopcornTV/node_modules/xmlrpc/lib/deserializer.js:42:7)
    at Deserializer.onDone (/Users/nicosegovia/Desktop/PopcornTV/node_modules/xmlrpc/lib/deserializer.js:92:12)
    at SAXStream.emit (events.js:104:17)
    at Object.SAXStream._parser.onend (/Users/nicosegovia/Desktop/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:184:8)
    at emit (/Users/nicosegovia/Desktop/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:615:33)

Any idea?

**Comment by OstlerDev** [comment]
@NicoSegoviaC this is not the correct place to post this issue, however if you post the Movie/TV Show (with season and episode) then I can test it out on my end and get it resolved.
