### ISSUE TITLE
Some Movies is not working from search 

### ISSUE THREAD

**Issue by Samb00** [OstlerDev/PopcornTV#137]
there is some movies not working when i get it from the search list like The Rock

**Comment by OstlerDev** [comment]
Can you post a full log for the affected movies? https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue/

**Comment by Samb00** [comment]
here you go: [PopcornTV Log The ROCK MOVIE](https://www.dropbox.com/s/nbfib5bwhmorgzu/PopcornTV%20copy.txt?dl=0)

sorry i can't post at pastebin

**Comment by OstlerDev** [comment]
This could be happening because the description has this character in it? "é"
