### ISSUE TITLE
Can't Access TV Shows By Genre

### ISSUE THREAD

**Issue by Kurry** [OstlerDev/PopcornTV#139]
I just pulled the master branch, and when I try to browse TV shows by genre, I get this 404, and the screen is stuck loading.
```bash
Web: templates/TVGenre.xml
Web: 404: templates/TVGenre.xml
```

```bash
new-host:PopcornTV ktran$ git show head
commit 4c8613f13c4c55905d4ba6fb45fde076caea8e19
Merge: a53c4b2 eadd00b
Author: Skylar Ostler <ostlerdev@me.com>
Date:   Fri Jul 24 14:46:28 2015 -0600

    Merge pull request #130 from shali3/master
    
    Added support for subtitles encoding with the Iconv library. Closes #68
```

**Comment by OstlerDev** [comment]
This happens because I cannot search by genres in the API, I will replace it with something else soon.

**Comment by Kurry** [comment]
@OstlerDev thanks for the quick response, I'll try to work on it when I get free time

**Comment by OstlerDev** [comment]
Turns out that it is as simple as this: ``http://eztvapi.re/shows/1?genre=Action`` it was not documented anywhere but that seems to work fine.

Will work on implementing this when I get some free time.
