### ISSUE TITLE
Version 1.3

### ISSUE THREAD

**Issue by Mehmeed** [OstlerDev/PopcornTV#14]
I dont know why, but mine says that i'm running version 1.3.. and one idea would be to change the quality and to change preferred quality to 1080p thanks.

**Comment by OstlerDev** [comment]
Right now you cannot change the quality, it is hardcoded to 720 right now but that will be changed in the next version hopefully.

**Comment by Mehmeed** [comment]
oh ok. thanks, and what about the version? is it supposed to say 1.3? or how do i download the new one?

**Comment by OstlerDev** [comment]
It should say 0.1.4a in the settings menu. It depends on how you downloaded the project. If you downloaded the zip, backup your certificates and reinstall, then add the certificates back in after.

I will add a wiki page on how to update shortly!

**Comment by Mehmeed** [comment]
oh ok thanks! :)
