### ISSUE TITLE
Add config option for alternate TV Api Endpoint

### ISSUE THREAD

**Issue by alise235** [OstlerDev/PopcornTV#141]
The trailer app seems completely fine until I scroll down to TV Shows, and then it all seems to crash and delivers an error message in my terminal window.

Link to log and settings files: https://gist.github.com/alise235/fe610751d87d51a0e307

Help please!

This is the screenshot of error code:
![screen shot 2015-07-29 at 16 44 47](https://cloud.githubusercontent.com/assets/13557471/8962207/438ff20c-3611-11e5-9cb4-0e86d9455ffe.png)

**Comment by OstlerDev** [comment]
@alise235 is this still happening for you?

**Comment by alise235** [comment]
Yes, it is. I've tried it again this morning, and I keep getting the same error message.

**Comment by OstlerDev** [comment]
A couple questions for you, firstly, in the desktop version of Popcorn Time are you able to access the TV Shows? Secondly are you from the UK?

**Comment by alise235** [comment]
In the desktop version, yes, I am able to access everything. And yes, I live in the UK.

**Comment by OstlerDev** [comment]
The UK block the servers for eztvapi.re currently, I will try to send a workaround for you later today

**Comment by alise235** [comment]
Ah ok. Great thank you!

**Comment by JakeRound** [comment]
Great news! I'm currently having to use a VPN which isn't the ideal solution.
