### ISSUE TITLE
Cant download certificate.

### ISSUE THREAD

**Issue by domidyon** [OstlerDev/PopcornTV#142]
Hi.

I am trying to download the certificate on my ATV but it doesn't work. It's just stuck on 'adding profile'
Yes, I changed the DNS on my ATV. Yes, i reinstalled and restarted everything but with no luck. 

According to terminal;

notice: Starting PopcornTV
DNS: DnsProxy binding on 1xxx:53
Web: listening on 1xxx:80
Web: SSL Web: listening on 1xxx:443

**Comment by JakeRound** [comment]
Are you using a Mac? Ensure the DNS IP is identical to the one shown in Terminal, also make sure that 'Send data to Apple' is set to 'no' then make sure 100% that you're adding the right certificate that being

```
http://trailers.apple.com/trailers.cer
```

All else fails restart the Apple TV.

**Comment by domidyon** [comment]
Did everything, including the restart. No luck yet..

**Comment by domidyon** [comment]
When I changed the DNS settings, the entire network on my ATV stopped working. When I changed it back to automatic, everything worked again. What is going on?

**Comment by Xalcker** [comment]
Make sure your Computer and the AppleTV are on the same network.

2015-07-29 12:13 GMT-05:00 domidyon <notifications@github.com>:

> When I changed the DNS settings, the entire network on my ATV stopped
> working. When I changed it back to automatic, everything worked again. What
> is going on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OstlerDev/PopcornTV/issues/142#issuecomment-126022658>
> .
>



-- 
----------------------------------------------
I.S.C. Yazel Hernández Vicente

**Comment by domidyon** [comment]
They are, 100% sure.

**Comment by Xalcker** [comment]
Is there any activity on the terminal window running PopcornTV when you
change the DNS on the AppleTV?

2015-07-29 12:20 GMT-05:00 domidyon <notifications@github.com>:

> They are, 100% sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OstlerDev/PopcornTV/issues/142#issuecomment-126025047>
> .
>



-- 
----------------------------------------------
I.S.C. Yazel Hernández Vicente

**Comment by domidyon** [comment]
Nope, there isn't

**Comment by JakeRound** [comment]
Possibly try over ethernet? Apart from that the only possible idea would be that the DNS you've entered is wrong? 

Maybe try close the terminal and delete, one should regenerate when you start the terminal and run the command. Then double check the DNS IP is 100% correct.
```
config.json
```

**Comment by domidyon** [comment]
Is there a  command to quit PopcornTV without having to restart? Brb, restarting...
Thanks for the quick reactions by the way. Ethernet isn't an option sadly. 
It doesn't make sense, it worked for me like 3 weeks ago..

**Comment by cadesalaberry** [comment]
Try Ctrl+C                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: domidyonSent: Wednesday, July 29, 2015 19:26To: OstlerDev/PopcornTVReply To: OstlerDev/PopcornTVSubject: Re: [PopcornTV] Cant download certificate. (#142)Is there a  command to quit PopcornTV without having to restart? Brb, restarting...
Thanks for the quick reactions by the way. Ethernet isn't an option sadly. 
It doesn't make sense, it worked for me like 3 weeks ago..

—Reply to this email directly or view it on GitHub.

**Comment by domidyon** [comment]
I'm on Mac by the way. 
Now I can't reinstall, stuck on; 
npm WARN package.json PopcornTV@0.1.6 No license field.
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.11.2"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.11.2"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.11.2"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.11.2"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.11.2"})
|
> iconv@2.1.8 install /Users/Dyon/Desktop/PopcornTV/node_modules/iconv
> node-gyp rebuild

Now it just doesn't do anything. I can't put in commands or something.

**Comment by domidyon** [comment]
I'm on Mac. Cmd+C doesn't do anything for me.

**Comment by domidyon** [comment]
Nothing yet. Should I just give up?

**Comment by domidyon** [comment]
Thanks! CTRL+C worked.

**Comment by Xalcker** [comment]
Maybe reinstalling Node.js, delete popcorntv folder and start over from git.

2015-07-29 12:39 GMT-05:00 domidyon <notifications@github.com>:

> Thanks! CTRL+C worked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OstlerDev/PopcornTV/issues/142#issuecomment-126031242>
> .
>



-- 
----------------------------------------------
I.S.C. Yazel Hernández Vicente

**Comment by JakeRound** [comment]
Holy crap! I didn't know 'Ctrl+C' closed the script... I've been restarting my computer overtime i modify something aha.

Nope don't give up you'll be missing out on something great. Yeah i'd agree with @Xalcker maybe try that. If nothing please post the entire console log.

**Comment by domidyon** [comment]
Still nothing..... How do I post my console log?

**Comment by domidyon** [comment]
My full log.... http://pastebin.com/CWyCsRD7

**Comment by JakeRound** [comment]
When entering the DNS ip does it look like this?
```
192.168.001.108

**Comment by domidyon** [comment]
Yep, it does!

**Comment by JakeRound** [comment]
Maybe asking @OstlerDev is your only solution? If you've tried everything

**Comment by domidyon** [comment]
I'll await his reaction I guess!

**Comment by OstlerDev** [comment]
What error are you getting on your Apple TV? Are you on the same Wifi Network on both devices?

**Comment by domidyon** [comment]
No error, just stuck on 'downloading profile'.
Yes, theyre on the same network..

**Comment by OstlerDev** [comment]
What router are you using? It could be possibile that it is blocking local traffic.

**Comment by domidyon** [comment]
Nope, it isn't the router, as it worked 2-3 weeks ago.. Still no fix, I tried everything..
