### ISSUE TITLE
Web: SSL 404: /appletv/application.js

### ISSUE THREAD

**Issue by jonRE** [OstlerDev/PopcornTV#144]
Hi,

I followed all the steps and I'm getting the following 404 error.

notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.36:53
Web: listening on 192.168.1.36:80
Web: SSL Web: listening on 192.168.1.36:443
Web: SSL: /appletv/application.js
Web: SSL 404: /appletv/application.js

I'm on OSX.

Appreciate any help

Kind regards,

**Comment by OstlerDev** [comment]
What Apple TV version are you running?

**Comment by OstlerDev** [comment]
@jonRE are you able to reproduce this issue?

**Comment by jonRE** [comment]
Hi,

Apple TV 2nd generation
iOS 5.0.1

Kind regards
