### ISSUE TITLE
Trailers is unavailable. Try again later.

### ISSUE THREAD

**Issue by stevemarks79** [OstlerDev/PopcornTV#146]
Every time I try to open the Trailers app, I get the "Trailers is unavailable. Try again later" error. Everything was working fine a few days ago. I've attempted reinstalling PopcornTV, Node, restarting the Apple TV, and restarting the MacBook. The DNS settings on the Apple TV are matched to the DNS showing when I run atv.js .

Any idea what could be the issue? Thanks.

**Comment by OstlerDev** [comment]
Sounds like the certificate on your Apple TV is not working, try re-adding the certificate.

**Comment by stevemarks79** [comment]
That solved it. 

Weird though, the certificate was there from when I added it the first time. I removed it and re-added it and it worked.

**Comment by OstlerDev** [comment]
Glad that worked for you!
