### ISSUE TITLE
Can't install PopcornTV on windows 7

### ISSUE THREAD

**Issue by bob1321** [OstlerDev/PopcornTV#149]
When I write npm install, I have this script

C:\Users\Pascal-Raphael>cd desktop/popcorntv

C:\Users\Pascal-Raphael\Desktop\PopcornTV\ npm install
npm WARN package.json PopcornTV@0.1.6 No license field.
-
> iconv@2.1.8 install C:\Users\Pascal-Raphael\Desktop\PopcornTV\node_module
nv
> node-gyp rebuild

C:\Users\Pascal-Raphael\Desktop\PopcornTV\node_modules\iconv>if not defined
config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gy
\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebui

Génération des projets individuellement dans cette solution. Pour activer l
ération en parallèle, ajoutez le commutateur "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.t
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid v
on number. [C:\Users\Pascal-Raphael\Desktop\PopcornTV\node_modules\iconv\bu
libiconv.vcxproj]
TRACKER : error TRK0005: échec de localisation de : "CL.exe". Le fichier sp
ié est introuvable. [C:\Users\Pascal-Raphael\Desktop\PopcornTV\node_modules
nv\build\libiconv.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe`
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_mod
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Pascal-Raphael\Desktop\PopcornTV\node_modules\iconv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\n
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.1.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.1.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Pascal-Raphael\Desktop\PopcornTV\npm-debug.log

C:\Users\Pascal-Raphael\Desktop\PopcornTV>

**Comment by MatthieuTnsc** [comment]
This is not a "Windows only" issue !
It appears to be a rebuild error during the installation of the node module : iconv

Here is my terminal output : http://pastebin.com/DPYLim4j

For information I tried reinstalling  Xcode command line tools with command : `xcode-select --install`
and also install again node-gyp to make sure the path was OK. Nothing fixed it.

@bob1321the iconv module seems to be an optional module inside package.json so you should be able to run PopcornTV without it.

**Comment by nicoti** [comment]
i have the same problem. I thought maybe i'm doing something wrong. Do it have any solution? Does anybody kwnos when is gonna be available the software for amateurs like me? :)

**Comment by MatthieuTnsc** [comment]
For people on Windows having this issue, can you try to install node-gyp dependencies on Windows first and then retry `sudo npm install` ?

**To install node-gyp dependencies on Windows you must first :**

- Install python: http://www.python.org/getit/windows/
- Install Microsoft Visual Studio C++ 2012 Express version: http://go.microsoft.com/?linkid=9816758
- Install node-gyp: `npm install -g node-gyp`

**Comment by bob1321** [comment]
@MatthieuTnsc Je ne suis pas Français mais je le parle :p  

Faut tu absolument Visual studio 2012? j'ai installer le 2015 hier et ça m'a donner l'erreur plus haut

**Comment by KingWouter** [comment]
@MatthieuTnsc Thanks ,I did get it fixed with this solution.
Only problem is that the subs (Dutch), on lets say the movie Focus (2015) are showing faster then the audio. Any way to fix this?

**Comment by MatthieuTnsc** [comment]
@bob1321 Je ne peux pas te le confirmer (je n'ai pas Windows)  mais je suppose que Visual Studio 2015 n'embarque pas les mêmes libraires que VS 2012 et cela pourrait être à l'origine du problème. Je vais continuer à chercher plus en détail les raisons.

@KingWouter Good news, for your subtitle delay issue I suppose you should create a new topic issue.

@OstlerDev I think it could be interesting to look for an alternative of **iconv module**. A module based on node-gyp generate a lot of complexe dependencies...

**Comment by nicoti** [comment]
I did what you said but i have the same poblem. Not found git.

**Comment by MatthieuTnsc** [comment]
@nicoti can you share your logs or console outputs following the process described here please : [How to report an issue](https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue)

**Comment by OstlerDev** [comment]
It is an issue with iconv needing to be compiled, I am going to test out iconv lite, it does not require compiling but does support less languages.

**Comment by OstlerDev** [comment]
This has been tested and fixed in the latest commit. Moving to iconv-lite has removed (some) compilation dependencies.
