### ISSUE TITLE
Fanart does not work Jailbroken ATV 2 OS 5.3

### ISSUE THREAD

**Issue by w1nterl0ng** [OstlerDev/PopcornTV#15]
I get this message when I select a movie from the Page of fan Art.  I am on a macbook pro.

**Comment by OstlerDev** [comment]
Can you post the log please? What movie does this happen for, just one or all?

Make sure you are on the latest version.

**Comment by w1nterl0ng** [comment]
Latest from Master or Dev?

**Comment by OstlerDev** [comment]
@w1nterl0ng Latest on the Master, that is the stable branch.

**Comment by w1nterl0ng** [comment]
ok, so I start up the server. then on ATV open Trailers.
I choose movies
the first movie
and here is the log
Starting PopcornTV
DnsProxy binding on 192.168.0.168:53
Web: listening on 192.168.0.168:80
SSL Web: listening on 192.168.0.168:443
SSL WEB: js/application.js
WEB: templates/navbar.xml
WEB: templates/index.xml
WEB: templates/Search/search.xml
WEB: templates/settings.xml
WEB: /js/settings.js
404: /js/settings.js
WEB: /Parade.xml
WEB: templates/MovieNav.xml
WEB: /js/utils.js
WEB: /js/navbarHandler.js
WEB: /MoviesGrid.xml
Streamer: No Stream Running
WEB: /Movies/MoviePrePlay.xml
WEB: /cache/tt2358925.jpg

**Comment by OstlerDev** [comment]
What is that movie that you pick? 
Does it happen to all movies, or just the one?

**Comment by w1nterl0ng** [comment]
That movie is Unfinished Business, but it happens with all movies.

**Comment by OstlerDev** [comment]
Is your Apple TV updated to the latest version?
What Apple TV do you use? (720p or 1080p)
Can you try in the TV Show section and see if it gives the same results?

**Comment by w1nterl0ng** [comment]
Is there a way to test this without apple tv? in a browser?
Thanks.

**Comment by OstlerDev** [comment]
Yes, on the computer you are running PopcornTV on please open the following page:

http://192.168.0.168/MoviePrePlay.xml?torrentID=4134

Please upload the response you get to pastebin or to a gist and post it on here. It should look exactly like this: https://gist.github.com/OstlerDev/e0756359a729796a8949

**Comment by w1nterl0ng** [comment]
Here is the pasteBin.
http://pastebin.com/Q7RKnn3Q
It looks like there is an issue with the loadURL string. is using html encoded text &quote maybe you can have better luck finding something.

**Comment by w1nterl0ng** [comment]
Is there a way to turn on verbose logging?  without something like wireshark?  I would like to see what the actual http request is from the MoviesGrid.xml that is bringing up the error message
thanks

**Comment by OstlerDev** [comment]
@w1nterl0ng I just pushed a commit to the master that hopefully should fix your issue. And currently the only way to view all incoming URL's is to add 'console.log(pathname + query);' to line number 42 in webserver.js.

I am planning on adding a further error reporting system that will log all the XML generated, URL's, everything so that users could enable it when things go wrong and they need to report them.

I forgot to ask. Do you get this issue when you are already in the fanart view and then try to select a related movie? Or do you get this issue when you try to go from the MovieGrid (Popular Movies) to the Fanart view?

**Comment by w1nterl0ng** [comment]
it happens when I go from MovieGrid to fan art.  I tried the console.log but it spits out query as [object Object].
One last thing. I am using 2nd Gen ATV with firecore jailbreak.
That could be the problem, but I am not sure.
Thanks for the help, if you want to dump this until someone else raises it, that is fine with me.
If you want to help me get a dev environment set up, I could do more to help debug it. I am curious how these libraries work and I have only dabbled in Node.

**Comment by OstlerDev** [comment]
Can you try the very latest commit?

**Comment by w1nterl0ng** [comment]
I did. sorry.. Same issue.

**Comment by OstlerDev** [comment]
What OS version is your Apple TV on?

**Comment by w1nterl0ng** [comment]
5.3 and firecore 2.5

**Comment by OstlerDev** [comment]
I think your Apple TV is too out of date to  display the Fanart, either you need to update the OS or wait until functionality for turning fan-art off is added

**Comment by w1nterl0ng** [comment]
I think you are correct, I did some searching on FanArt and PlexConnect and pre- 6.0.  I wonder what part of the fanart is causing a problem?  I'll dig around and see if anyone had a workaround for plexconnect.

**Comment by OstlerDev** [comment]
I am pretty sure it is the entire part with the fanart, I do not think Apple added "itemDetailWithImageHeader" until v6.0. Does Firecore support any OS versions above 6.0? If so you can attempt updating.

**Comment by w1nterl0ng** [comment]
FireCore Does not.  So, is there a guide to what valid xml in 5.3 looks like?  I would be happy to work on a setting that disabled fan art, I have tried just pulling those nodes out, but I still get the error

**Comment by OstlerDev** [comment]
This is the commit from before I changed to using the Fanart for the generator: https://github.com/OstlerDev/PopcornTV/commit/4891b6fa4b96df0b4e81e03b3a974b011542f99f#diff-d3483723301fe29d1745c4406e7725a6L149

You can also take a look at a sample XML file of what it normally will look like before generated: https://github.com/finkdiff/ATVBrowser-script/blob/master/assets/Movies/MoviePrePlay.xml

**Comment by w1nterl0ng** [comment]
ok, thank you Success.  I am able to play movies., I stripped out too much, I will put ack some of the features.  then see if I can make it configurable.
Thank you for your patience.

**Comment by OstlerDev** [comment]
No problem! If you want you can just use this as a version for you for now until I implement the configuration stuff and get it all working. I am glad we got this figured out though.

**Comment by OstlerDev** [comment]
I started some more work on this today by implementing the settings page into the Apple TV and making it functional, soon I will be able to send out the non-fanart view instead of the main view. 

@w1nterl0ng Has changing the XML to the non-fanart view worked for you?

**Comment by w1nterl0ng** [comment]
Yes, I modified the file, it is on my fork but not as a conditional setting
so I did not or.
Thanks for your work

**Comment by OstlerDev** [comment]
@w1nterl0ng If you use the latest version you can disable Fanart now. Just go into the settings page on the ATV and set it to "Off".

I still need to disable the season view as well as the episode preplay view, but you should be able to use the latest version without worry!

**Comment by w1nterl0ng** [comment]
Thanks, I'll give this a try.
