### ISSUE TITLE
Problem GIT file

### ISSUE THREAD

**Issue by diogosmiranda** [OstlerDev/PopcornTV#151]
I am having a problem popcorn installation, after I type (npm install) appears error in git file not found.
![npm](https://cloud.githubusercontent.com/assets/6942182/9035615/15fe6ee8-39b0-11e5-9eae-6859cb7603b2.png)
![npm11](https://cloud.githubusercontent.com/assets/6942182/9035627/236723d6-39b0-11e5-847c-a819685c460a.png)

**Comment by JakeRound** [comment]
Seems like there's a small bug in the latest commitment regarding support for windows. @OstlerDev works great on the Mac.

**Comment by MatthieuTnsc** [comment]
Same issue here with iconv rebuild (node-gyp) : https://github.com/OstlerDev/PopcornTV/issues/149

**Comment by nicoti** [comment]
so what is the solution? couse it not the same problem as  #149

**Comment by OstlerDev** [comment]
Update and try again please.

**Comment by nicoti** [comment]
yes, i already did that, but still happens... :(

**Comment by OstlerDev** [comment]
Try installing Git for Windows that might fix it: https://msysgit.github.io/
