### ISSUE TITLE
While installing "Module not found"

### ISSUE THREAD

**Issue by dudisr** [OstlerDev/PopcornTV#154]
Hi i was following the step by step although after installing the certificates i typed "sudo node atv.js" as said and the following message has showed 

"notice: Creating SSL Certificates...
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.25.10:53
error: There is an error starting Popcorn TV, please post this on the Github page
{ [Error: Cannot find module 'popcorn-streamer'] code: 'MODULE_NOT_FOUND' }"

I can not get after that. 
Can anyone help me out???

TY 
Ed

**Comment by OstlerDev** [comment]
Try running ``npm install`` again.

**Comment by dudisr** [comment]
now appear that "package.json npm can't find a package.json file in your current directory."
did i missed this part or should be on PopcornTV file ?
Where can i find this ?

**Comment by dudisr** [comment]
Ostler now i just did again and passed, although on apple tv on the add profile part it can't  add it. 
Any suggestion ?

**Comment by OstlerDev** [comment]
Did you make sure to change the DNS?

**Comment by dudisr** [comment]
on apple tv? yes. 
on terminal appeared this 
"Error: bind EADDRNOTAVAIL
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3"
any problem on that ?

still waiting a lot to add the profile on apple tv and after a while shows 
"unable to add profile 
an error occurred while adding the profile [-1101]. check the url and try again"

**Comment by dudisr** [comment]
also tried using the dns on profile. 

"Starting PopcornTV
DnsProxy binding on 10.0.1.2:53
Web: listening on 10.0.1.2:80
SSL Web: listening on 10.0.1.2:443
events.js:85"

so http://10.0.1.2/trailers.cer and still no response.

**Comment by OstlerDev** [comment]
You are not binding to the correct IP address then. What is your Local IP? Try updating to the latest version and deleting config.json.
