### ISSUE TITLE
Install and run PopcornTV on aTV (jailbroken)

### ISSUE THREAD

**Issue by MatthieuTnsc** [OstlerDev/PopcornTV#157]
I haven't tried yet but apparently the Python app (PlexConnect) using the same DNS workaround could be installed and run directly by the aTV.

Here is the installation tutorial to do so : https://github.com/iBaa/PlexConnect/blob/master/support/aTV_jailbreak/README.txt

Would it be technically possible to do the same with PopcornTV ? Installing Node.js via SSH then push PopcornTV app and run it from aTV ?

I have an aTV 2nd gen that I could jailbreak to try but before I would like to know if it seems possible to you @OstlerDev ?

**Comment by orossant** [comment]
Yes, you can copy past from asset folder of plexconnect the certificate files and paste them on your PorcornTV Folder
See https://github.com/OstlerDev/PopcornTV/wiki/How-to-install-%28Mac%29

**Comment by orossant** [comment]
My first test bring me with menu, jackets, and after having selected Play, there is a first phase of bufferisation of the selected media, then a converting phase after downloading 10%.  But then it doesn't play the media, don't know what is wrong (perhaps file format don't supported ?). I need to test with a mp4 file streamed to avoid the conversion phase ...

**Comment by OstlerDev** [comment]
As long as you can install NodeJS on the Apple TV I do not see why you wouldn't be able to install it. I cannot test so this will be up to you.

**Comment by OstlerDev** [comment]
There is also another issue with storage space, you would need to make sure that the "Keep Downloads" option is disabled.

**Comment by orossant** [comment]
With apple TV 3, i think it's not possible to jailbreak it to install something on it.
Your solution is similar to plexconnect (stream via a pc or mac) and it's fine !
So it would be very nice to be able to have an option "keep downloads" that allow nodejs on the MAC to bufferise the media. And to have a paramerer to control buffer size.
It is possible to install nodeJS on a synology nas if you wan't to avoid the use of a mac or pc.
for instance plex media server and plex connect can be installed on synology ds214 play

**Comment by OstlerDev** [comment]
This is beyond the scope of the project to provide support for this, but if someone writes up a Wiki article I would be more then glad to get it up on the wiki.
