### ISSUE TITLE
Adding preferred quality for the TV SHOWS

### ISSUE THREAD

**Issue by Samb00** [OstlerDev/PopcornTV#158]
Hello Bro, 
first of all i want to thank you so much for your amazing work, the latest update is awesome and working very well, 
i was thinking if you can add a separate preferred quality for the TV show bc as you know we have to play it in 480 because of the converting, so we can play the MOVIES in 1080 and the TV SHOWS in 480

Have a blessed day.

**Comment by sjako** [comment]
Good idea!

**Comment by OstlerDev** [comment]
Will add this, as I do experience this as well. Currently the quality selection goes to both, but I think having them separate would add to the experience.

**Comment by Samb00** [comment]
just tested it, working very well 
You are the ONE BRO.

**Comment by OstlerDev** [comment]
Glad you like it! I am working on some other features right now too so stay tuned!

**Comment by Samb00** [comment]
@OstlerDev and i have a lots of ideas :P :D

**Comment by OstlerDev** [comment]
Keep suggesting them! Also, thanks for donating earlier! I am adding an awesome new perk soon ;)

**Comment by Samb00** [comment]
it's nothing Bro you deserve MORE

**Comment by OstlerDev** [comment]
Glad that you think so :p I honestly did not expect to get the amazing amount of donations and support that I have received! It sucks that I cannot add more to this program all the time because of schooling or work, that is why I setup the campaign page at: https://salt.bountysource.com/teams/popcorntv

**Comment by Samb00** [comment]
you doing so good my friend and again you deserve more :) keep your amazing work UP
