### ISSUE TITLE
After Buffering  and Conversion Phase, Video doesn't play on AppleTV

### ISSUE THREAD

**Issue by orossant** [OstlerDev/PopcornTV#159]
I have successfully installed PopcornTV on a Mac and certificate for trailers channel on appleTV 3 not jailbreaked by following detailed well explained steps :-).
All seems fine, very cool screen, etc, awesome. 
I have tested all menus, etc and it"s ok. 
But then when I select a show to play,   I  choose 720 p resolution, then, there is a first phase of bufferisation of the selected media, then a converting phase after downloading 10%. 
After That, it doesn't play the media, I have the dead stalling ring.
I don't know what is wrong (perhaps file format don't supported ?). I need to test with a mp4 file streamed to avoid the conversion phase ... 
Perhaps need I to choose continue downloading in the settings right menu ?

Anyway, it's a very impressiv work, it almost works for me

**Comment by OstlerDev** [comment]
It sounds like you might need to restart your Apple TV, I have heard that this can happen rarely, but that usually fixes it.

Is it happening for all media? Or only one? Try running PopcornTV in debug mode to see if there is an error.

**Comment by orossant** [comment]
1) Yes, I have reboot the appletv, and then I have choose in setting continue downloading, and it works perfectly ! thanks a lot !
Can you explain what is the meaning of this setting "continue downloading"
2) Is it possible to use a vpn on the mac ? when appletv stream the media, i think is use the mac to download video parts, so normaly it will be inside my VPN right ?
3) 
I have then tried to launch a client VPN on the Mac, and it continue to works but in the play horizontal bar graph i have seen that the buffer doesn't grow very fast and during the play, after One minutes, there is no more buffer and the video is pausing, it is inevitable ... 
I think my VPN provider or my internet connection is to slow and it doesn't concern popcorn TV
Perhaps, it could be helpfull to be able to choose the buffer size in advanced mode ?

**Comment by OstlerDev** [comment]
1. Awesome!
2. Yes, you can use a VPN to hide your traffic, however be warned that it may become to slow to stream the movie.
3. Refer to 2. Choosing a buffer size may help a little bit so I /may/ add this feature into the settings.

**Comment by orossant** [comment]
Very nice work and fast answer ! thks !
