### ISSUE TITLE
DNS Server IP Verification

### ISSUE THREAD

**Issue by masonjames** [OstlerDev/PopcornTV#16]
Hiya,

I'm not sure this is an issue with this app, but when I run node avt.js I get an error like this:
Error: bind EADDRNOTAVAIL
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

I'm wondering if there's an issue with the IPs because the address on my mac is 10.0.1.28 and that is what I changed my appletv to.  When I run avt though It lists these IPs:
Starting PopcornTV
DnsProxy binding on 10.0.1.2:53
Web: listening on 10.0.1.2:80
SSL Web: listening on 10.0.1.2:443

Should any of those actually match up?  On the appletv side I'm unable to add a new profile because it says it cannot connect to the URL.  My hunch is, that's related to my issue, but I'm not much of a coder and only installed node.js to try and get this app running.

Would appreciate any pointers someone could offer. Thanks for sharing and keeping it open-sourced!

**Comment by OstlerDev** [comment]
You forgot to change the Local IP in the Config.json file, once you change that to your local IP (10.0.1.28) and save then restart it should work fine.

**Comment by brunojalves** [comment]
Hello, 

I have this error, 
node atv.js 
Starting PopcornTV
DnsProxy binding on 192.168.7.200:53
Web: listening on 192.168.7.200:80
SSL Web: listening on 192.168.7.200:443
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

But this machine i'm testing is an ubuntu server 32bit 14.04
I just create a new interface eth0:1 with this ip.


Would appreciate any help.

By the way, subtitles there is any way to insert it?

**Comment by OstlerDev** [comment]
Are you running it on a remote server? If so you need to put the remote IP. It seems like the error is that you might also be running apache or some sort of Web server on that machine?

**Comment by brunojalves** [comment]
No the server is local, and yes I'm using apache.
There is some way to use the two?

**Comment by masonjames** [comment]
Yup. Thanks, setting that fixed my issue.

**Comment by masonjames** [comment]
I'd be happy to add this step to the installation wiki if you wanted some help on documentation.

**Comment by OstlerDev** [comment]
@brunojalves PopcornTV requires using port 80, you can change the Apache port to something else and also use PopcornTV, but PopcornTV must use port 80. 443, and 53.

@masonjames Glad that fixed your issue! Enjoy! It should currently be on the Wiki, but if you want to edit the Wiki page post your edit here and I will update the page. If you wish to contribute more in the future we can look into adding you as an editor.

**Comment by kmanleafs** [comment]
Im gettting the same problem now

C:\Users\krish\Desktop\PopcornTV>node atv.js
Starting PopcornTV
DnsProxy binding on 192.168.2.4:53
Web: listening on 192.168.2.4:80
SSL Web: listening on 192.168.2.4:443
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRNOTAVAIL
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

But i have edited the json file  and running it on a local computer

**Comment by OstlerDev** [comment]
@kmanleafs Are you making sure that you are using the correct local IP? You are getting the error 'EADDRNOTAVAIL'  because you are not using the Local IP of your computer.

I just pushed a commit to the dev branch (0.1.5) that resolves your issue. Please download this branch and test it out if you could, it should resolve the issue that you are having. https://github.com/OstlerDev/PopcornTV/tree/0.1.5

**Comment by kmanleafs** [comment]
I was able to fix it....my local IP changed..thanks tho!

**Comment by OstlerDev** [comment]
No problem! Enjoy!
