### ISSUE TITLE
When playing 720p tv show, suddenly leave the player

### ISSUE THREAD

**Issue by rimkashox** [OstlerDev/PopcornTV#160]
There is a problem with buffering of 720p tv shows, it just leaves the player suddenly if not enough sources (so download speed not sufficient) and if I pause to let it buffer more, also start time and end time values of player remain wrong. 

Maybe it's a problem with the conversion process needing a faster connection (or more sources) to work correctly.

I have not seen this problem for 480p shows, but perhaps more testing is needed. 

To simulate a slow or bad network you can use a dev tool by apple called "network link conditioner" more info here http://nshipster.com/network-link-conditioner/

**Comment by OstlerDev** [comment]
This is because of #3
