### ISSUE TITLE
"accessing trailer..." turning wheel for tv shows loaded with load more

### ISSUE THREAD

**Issue by rimkashox** [OstlerDev/PopcornTV#161]
When accessing tv-show on popular view, then click load more, new loaded tv-show when clicked on does not load, stays stuck on "accessing trailer..." turning wheel. The solution to load this tv shows in to then access them via search view.

**Comment by OstlerDev** [comment]
Issue is that I hardcoded some values, will fix shortly.

Affected code can be found here: https://github.com/OstlerDev/PopcornTV/blob/master/assets/js/utils.js#L87-L88

**Comment by OstlerDev** [comment]
@rimkashox This is untested but should fix this issue, I am not near my Apple TV so I cannot test it out until later. If you get a chance to test it please report back.

**Comment by rimkashox** [comment]
Great will update and report back.
