### ISSUE TITLE
Search not working for not loaded tv-shows

### ISSUE THREAD

**Issue by rimkashox** [OstlerDev/PopcornTV#162]
Search in case of a tv-show present in 2nd page or more of popular are not found. Works only if 2nd page or more of popular view loaded first (by pressing on load more).

**Comment by OstlerDev** [comment]
@rimkashox I just tested this and it worked fine. Can you give more context as to what might be happening?

**Comment by rimkashox** [comment]
@OstlerDev Thanks for checking, I also just checked and it now works.. I think, the apis are not always responsive.. Maybe in time, when this gets really serious you could build some kind of a proxy with caching of those apis...

**Comment by JakeRound** [comment]
@rimkashox Something similar to #156 ?

**Comment by rimkashox** [comment]
Yes, what you described there would be great.. And running such a server
would be quite cheap.. Processing is low and data is pure text..

**Comment by OstlerDev** [comment]
I do plan on getting an API server set up at some point.

**Comment by rimkashox** [comment]
Awesome
