### ISSUE TITLE
Fatal error cannot start webserver.

### ISSUE THREAD

**Issue by Sudden78** [OstlerDev/PopcornTV#163]
C:\Users\Sandin\Desktop\PopcornTV>node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.214:53
Web: listening on 192.168.1.214:80
Web: SSL Web: listening on 192.168.1.214:443
error: ========= FATAL ERROR =========
error: Cannot start web Server. Please make sure you are using the correct IP!
error: Error Code: EACCES
error: ===============================

Get this error every time i start.
Started getting this after update 2015-08-06

**Comment by diogosmiranda** [comment]
Sudden78  was also with this issue, I released every port and it worked.
I did so: the typed command: net stop was, confirmed (yes) then tried again atv.js node and it worked.

**Comment by OstlerDev** [comment]
On Windows: Start command prompt in administrator mode
On Mac: start with "sudo" at the start

**Comment by Sudden78** [comment]
Same error when runnig as administrator

**Comment by OstlerDev** [comment]
Try deleting ``config.json`` and restarting.

**Comment by Sudden78** [comment]
Already tried that. 

Did not work. 

Reverted back to 0.1.5 same problem. 

Probably  something in my computer. 

Just can't figure out what's wrong.

**Comment by OstlerDev** [comment]
Have you attempted to restart your computer? Are you sure you are getting the error "EACCES"?

**Comment by Sudden78** [comment]
Yes i have restarted the computer several times. 

Yes error eacces

**Comment by OstlerDev** [comment]
Are you an administrator user on that computer? ``EACCES`` means that you do not have permission to bind to that port. Try right clicking cmd (on windows) and selecting ``Run as Administrator`` if you have not already.

**Comment by Sudden78** [comment]
Yes i have runned cmd as administrator. 

Wich of the port can't it bind to?

It has worked perfectly  until i updated popcorn tv yesterday. 

But when i reverted back to 0.1.5 same problem. 

Maybe Microsoft pushed some updates this week that ruined something.

**Comment by OstlerDev** [comment]
Are you an administrator user on that computer?

**Comment by Sudden78** [comment]
Yes i am an administrator.

Can´t figure out whats wrong.

Do you have any ideas how to track the problem?

**Comment by OstlerDev** [comment]
1.Try disconnecting your Ethernet cable (if plugged in) and just use wifi on the Apple TV and your Desktop.
2. Delete config.json again
3. Restart PopcornTV

See if those steps solve your issue. I am thinking there is just an issue with being on the same network to talk to each other.

What router do you have in your house?
Are you running Windows 10?

**Comment by Djimmo** [comment]
I seem to be having the same problem, I am running as administrator in Windows 10

**Comment by OstlerDev** [comment]
Looks like this is an issue with Windows 10. A quick search to see if PlexConnect had a similar issue yielded results.

Try taking a look here: https://forums.plex.tv/discussion/comment/986314/#Comment_986314

It looks like Windows 10 automatically starts a service using up port 80 or 443, by disabling that (you most likely are not using it anyways) then you will be able to use PopcornTV as normal! 

Unfortunately since I run Mac and not Windows, I do not know the steps in order to disable it or even where to find it. If someone that fixes it could PLEASE post a guide on how to disable that I would be forever thankful.

**Comment by Djimmo** [comment]
The command "net stop" worked.. Windows 10 seems to be running some web server things:

- World Wide Web publishing Service
- Net.Pipe Listener
- Net.Msmq Listener

Stopping these services makes it possible to start PopcornTV. They only thing is I'm not sure what I am exactly stopping..

**Comment by OstlerDev** [comment]
World Wide Web publishing Service is the service you need to disable (as outlined in my post above). From what I understand it just serves up content similar to a webserver? (clarification anyone?)

**Comment by Djimmo** [comment]
Found somewhere:

"World Wide Web Publishing Service is a component of Internet Information Services (IIS) on Microsoft Windows and of Internet Information Server (IIS) on Microsoft Windows NT. The World Wide Web Publishing Service provides support on Windows and Windows NT for communication using the Hypertext Transfer Protocol (HTTP). This protocol allows users to publish Web content on IIS for use on the Internet or on corporate intranets. Published Web content can then be accessed and displayed on client computers by using a standard Web browser such as Microsoft Internet Explorer. The World Wide Web Publishing Service is also central to third-party applications that facilitate remote administration of computers running Windows and Windows NT using Web browsers as their standard administrative interface."

**Comment by Sudden78** [comment]
Tested your steps not working. 

My router Asus rt-n66

Running Windows 7

Skickat från min iPhone

**Comment by Djimmo** [comment]
@Sudden78 Try stopping the services I listed using the "net stop" command. Then try to start PopcornTV using "node atv.js", this worked for me!

**Comment by Sudden78** [comment]
These services is not running on my win7 computer. 

PopcornTV still same error. 

Skickat från min iPhone

**Comment by Sudden78** [comment]
Finally solved it. 

It was a vmware service using port 443. 

Turned off that service and now is everything working fine. 

Thanks for the support and thanks for PopcornTV.

**Comment by OstlerDev** [comment]
Glad you got it figured out!

You are welcome for the support, and I am glad that you like PopcornTV!
