### ISSUE TITLE
Think subs are broken

### ISSUE THREAD

**Issue by sjako** [OstlerDev/PopcornTV#165]
No subs anymore after last update...

**Comment by OstlerDev** [comment]
Could be broken for win encodings, currently the encoding shows as CP1251 instead of win1251. Needs further testing.

**Comment by sjako** [comment]
Let me know if I can help with testing. And btw, you rock dude, awesome work.

**Comment by sjako** [comment]
Dutch subs are still broken

**Comment by OstlerDev** [comment]
Can you post a full debug log by following the "How to report an issue" wiki page? In my testing it works fine.

**Comment by sjako** [comment]
[ 'Error: Cannot find module \'iconv-lite\'',
     '    at Function.Module._resolveFilename (module.js:336:15)',
     '    at Function.Module._load (module.js:278:25)',
     '    at Module.require (module.js:365:17)',
     '    at require (module.js:384:17)',
     '    at decode (/Users/xxxx/Desktop/PopcornTV/SubtitleAPI.js:123:21)',
     '    at /Users/xxx/Desktop/PopcornTV/SubtitleAPI.js:152:39',
     '    at /Users/xxx/Desktop/PopcornTV/node_modules/xmlrpc/lib/client.js:130:9',
     '    at callback (/Users/xxx/Desktop/PopcornTV/node_modules/xmlrpc/lib/deserializer.js:42:7)',
     '    at Deserializer.onDone (/Users/xxx/Desktop/PopcornTV/node_modules/xmlrpc/lib/deserializer.js:92:12)',
     '    at SAXStream.emit (events.js:104:17)' ] }

and the log
http://pastebin.com/SbJBCKKT

**Comment by OstlerDev** [comment]
Please run ``npm install`` again. This is required sometimes when updating.

**Comment by sjako** [comment]
Tx, just noticed that. Missed the module. Apologies.

**Comment by OstlerDev** [comment]
No problem! We all make mistakes :)

Enjoy your movie!
