### ISSUE TITLE
Workaround for Apple TV when PopcornTV isn't running?

### ISSUE THREAD

**Issue by krugster** [OstlerDev/PopcornTV#168]
Is there anyway to workaround the fact that the AppleTV is essentially useless if its designated DNS server is not avialable?  Like when PopcornTV isn't running?

Thanks!

**Comment by OstlerDev** [comment]
Change the DNS back to Automatic.

**Comment by krugster** [comment]
Yes true, but that's a little bit arduous to be flipping back and forth between DNS.  I totally realize this isn't a PopcornTV issue (since it's not even running :-) ) but was hoping maybe you would have a workaround.

Thanks!

**Comment by OstlerDev** [comment]
I wish there was a better workaround I really do, the best thing to do is just to leave PopcornTV running in the background. It takes up minimal RAM and Processing power and unfortunately I do not know of any other way.

**Comment by krugster** [comment]
Okay sounds good, just thought I'd ask.  It's not so much a matter of leaving PopcornTV running (I'm setting it up on a dedicated machine) but in case it crashes or that machine isn't avialable, etc.

Thanks anyway!

**Comment by OstlerDev** [comment]
What I would suggest doing is running something like [Forever](https://github.com/foreverjs/forever) to automatically restart PopcornTV if it crashes (however crashes are handled and just logged so the App will not exit).
