### ISSUE TITLE
Can't run as service on Windows

### ISSUE THREAD

**Issue by krugster** [OstlerDev/PopcornTV#169]
I used a node.js tool called "qckwinsvc" to install PopcornTV as a service on my Windows machine and it won't seem to start properly.

The event logs show:
Child process [4968 - C:\Program Files (x86)\nodejs\node.exe --harmony "C:\Users\pkrug\AppData\Roaming\npm\node_modules\qckwinsvc\node_modules\node-windows\lib\wrapper.js" -f "C:\Users\pkrug\PopcornTV-0.1.5\atv.js" -l "PopcornTV" -g 0.25 -w 1 -r 3 -a n] terminated with 0

And then I discovered when running it manually (from outside of its directory) I get the following error:
C:\Users\pkrug>node C:\Users\pkrug\PopcornTV-0.1.5\atv.js
warning: SSL Certificate does not exist, Please restart PopcornTV once the process ends!
C:\Users\pkrug\PopcornTV-0.1.5\atv.js:11
        fs.writeFile('assets/certificates/trailers.cer', keys.certificate+ '\n
                                                             ^
TypeError: Cannot read property 'certificate' of undefined
    at C:\Users\pkrug\PopcornTV-0.1.5\atv.js:11:62
    at C:\Users\pkrug\PopcornTV-0.1.5\node_modules\pem\lib\pem.js:238:24
    at C:\Users\pkrug\PopcornTV-0.1.5\node_modules\pem\lib\pem.js:146:24
    at C:\Users\pkrug\PopcornTV-0.1.5\node_modules\pem\lib\pem.js:67:20
    at C:\Users\pkrug\PopcornTV-0.1.5\node_modules\pem\lib\pem.js:754:20
    at C:\Users\pkrug\PopcornTV-0.1.5\node_modules\pem\lib\pem.js:733:13
    at C:\Users\pkrug\PopcornTV-0.1.5\node_modules\pem\lib\pem.js:640:20
    at C:\Users\pkrug\PopcornTV-0.1.5\node_modules\pem\lib\pem.js:786:20
    at F (C:\Users\pkrug\PopcornTV-0.1.5\node_modules\pem\node_modules\which\which.js:40:25)
    at E (C:\Users\pkrug\PopcornTV-0.1.5\node_modules\pem\node_modules\which\which.js:43:29)
C:\Users\pkrug>

Yet if I am in the directory, it runs just fine:
C:\Users\pkrug\PopcornTV-0.1.5>node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.200:53
Web: listening on 192.168.1.200:80
Web: SSL Web: listening on 192.168.1.200:443

 Thanks a lot for your help!

Perry

**Comment by OstlerDev** [comment]
Try updating to the latest version.

**Comment by krugster** [comment]
I'm running 0.1.5...do you think I need to grab the master?

Not at all asking you to support other software :-)  Just trying to get PopcornTV running as headless...

And it seems I was able to reproduce at least some issue running it without being in the directory which is how Windows service is going to launch it I assume...

**Comment by OstlerDev** [comment]
You are perfectly fine :)

I pushed some updates that fix when running the script from a location other then directly inside the folder while working on the Desktop Application, so updating to the master branch should fix that :) (along with adding tons of awesome features)

**Comment by krugster** [comment]
sweet, I'll give it a try now!

**Comment by krugster** [comment]
Well that seems to have made things better.  I can start atv.js from anywhere on the command-line, and when I install it as a service it's able to launch and I see node.exe running...but it's not responding to DNS requests so I imagine there's still something else wrong.  Though now I can't figure out what because I can't find where the output would be...

I'm going to keep digging in, but any further thoughts?

**Comment by OstlerDev** [comment]
Not sure for the DNS, just make sure that you are on the same network and such.

**Comment by krugster** [comment]
okay so I can tell that the app is definitely running, I can open a connection to port 443 as well as 80, though not on 53.

However, now when I run the app manually I get an error about the log:
C:\>node C:\Users\pkrug\PopcornTV\atv.js
error: There has been an error generating the Config, please report this error on the github page!
error: EPERM, open 'C:\config.json'
error: uncaughtException: EPERM, open 'C:\PopcornTV.log'
{ date: 'Sat Aug 08 2015 22:42:38 GMT-0700 (Pacific Daylight Time)',
  process:
   { pid: 372,
     uid: null,
     gid: null,
     cwd: 'C:\\',
     execPath: 'C:\\Program Files (x86)\\nodejs\\node.exe',
     version: 'v0.12.7',
     argv: [ 'node', 'C:\\Users\\pkrug\\PopcornTV\\atv.js' ],
     memoryUsage: { rss: 29163520, heapTotal: 17800448, heapUsed: 8612192 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 5662.2948178 },
  trace:
   [ { column: null,
       file: null,
       function: 'Error',
       line: null,
       method: null,
       native: true } ],
  stack:
   [ 'Error: EPERM, open \'C:\\PopcornTV.log\'',
     '    at Error (native)' ] }

**Comment by krugster** [comment]
Before I was downloading it as a zip file, but now I did a git clone, npm install, and then moved over my certificates and config.json...did that screw something up?

**Comment by OstlerDev** [comment]
Hmm, shouldn't have screwed anything up. I am going to look at the code fast.

**Comment by krugster** [comment]
I'm not nearly as good with Windows as I need to be...I downloaded git and then used git-shell to do the git clone and npm install (because npm was complaining if I ran it from the regular command-line) and now the app looks like it starts-up properly if I run it from within the git-shell.  I can see it receiving and responding to DNS requests from my aTV, but it doesn't actually serve anything...

I think I'll start totally from scratch...

**Comment by OstlerDev** [comment]
I just pushed up an update that will fix the issue you stated here: https://github.com/OstlerDev/PopcornTV/issues/169#issuecomment-129126066

**Comment by krugster** [comment]
Okay, tried to pull down a completely clean copy but now it's not picking up the config file location correctly...it's looking for it in my current directory instead of where the atv.js script is located:
warning: Config file does not exist, please report this error on the github page

error:  Error: ENOENT, no such file or directory 'C:\Users\pkrug\config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.getTVEndpoint (C:\Users\pkrug\PopcornTV\settings.js:224:23)
    at Object.<anonymous> (C:\Users\pkrug\PopcornTV\TVApi.js:2:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
Web: /TVGrid.xml
warning: Error connecting to undefined and grabbing json: http://undefined/shows/1

**Comment by OstlerDev** [comment]
Delete the config file and start again.

**Comment by krugster** [comment]
nope, same error

**Comment by OstlerDev** [comment]
What is the full command line arguments that you are using to start PopcornTV?

**Comment by krugster** [comment]
C:\Users\pkrug>node C:\Users\pkrug\PopcornTV\atv.js

**Comment by OstlerDev** [comment]
I think I know the issue, give me a sec to write it and push up a commit (not the one being sent right now, but the one after it)

**Comment by krugster** [comment]
no worries at all, much appreciate you working on this so late at night with me!

**Comment by OstlerDev** [comment]
You are perfectly fine :p I was just about to sit down and watch a movie, but these are just quick bug fixes once I find them.

**Comment by krugster** [comment]
Yes!  That worked beautifully!

Thank you so much, enjoy your movie and your next few beers are on me :-)

**Comment by OstlerDev** [comment]
No problem! Glad you like it :)
