### ISSUE TITLE
Does not Delete Files on Windows.

### ISSUE THREAD

**Issue by krugster** [OstlerDev/PopcornTV#170]
Saw this in the logs:
2015-08-09T06:27:08.192Z - warning: Unable to delete path

I suspect it was trying to remove a cached video file and couldn't for some reason, there's not much more in the logs around that.

I do see a few files still left around in assets/cache...

**Comment by OstlerDev** [comment]
This is a known issue with how Windows handles files, it is still something that I want to fix.
