### ISSUE TITLE
Movie freezes after first buffered load

### ISSUE THREAD

**Issue by SkOpE-000** [OstlerDev/PopcornTV#173]
First off
Fond user of PopcornTV. Great app. Great Code.

i have update to todays updates 2015-09-08 and have problems playing movies.
I get the following error:

error: uncaughtException: Cannot read property 'data' of undefined 
{ date: 'Sun Aug 09 2015 15:10:47 GMT+0200 (CEST)',
  process: 
   { pid: 2477,
     uid: 0,
     gid: 0,
     cwd: '/home/PopcornTV',
     execPath: '/usr/local/bin/node',
     version: 'v0.12.7',
     argv: [ 'node', '/home/PopcornTV/atv.js' ],
     memoryUsage: { rss: 76214272, heapTotal: 45475328, heapUsed: 33224540 } },
  os: 
   { loadavg: [ 0.216796875, 0.4052734375, 0.224609375 ],
     uptime: 670 },
  trace: 
   [ { column: 61,
       file: '/home/PopcornTV/SubtitleAPI.js',
       function: null,
       line: 150,
       method: null,
       native: false },
     { column: 9,
       file: '/home/PopcornTV/node_modules/xmlrpc/lib/client.js',
       function: null,
       line: 130,
       method: null,
       native: false },
     { column: 7,
       file: '/home/PopcornTV/node_modules/xmlrpc/lib/deserializer.js',
       function: 'callback',
       line: 42,
       method: null,
       native: false },
     { column: 12,
       file: '/home/PopcornTV/node_modules/xmlrpc/lib/deserializer.js',
       function: 'Deserializer.onDone',
       line: 92,
       method: 'onDone',
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'SAXStream.emit',
       line: 104,
       method: 'emit',
       native: false },
     { column: 8,
       file: '/home/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js',
       function: 'Object.SAXStream._parser.onend',
       line: 184,
       method: 'SAXStream._parser.onend',
       native: false },
     { column: 33,
       file: '/home/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js',
       function: 'emit',
       line: 615,
       method: null,
       native: false },
     { column: 3,
       file: '/home/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js',
       function: 'end',
       line: 654,
       method: null,
       native: false },
     { column: 24,
       file: '/home/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js',
       function: 'Object.SAXParser.end',
       line: 149,
       method: 'SAXParser.end',
       native: false },
     { column: 16,
       file: '/home/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js',
       function: 'SAXStream.end',
       line: 234,
       method: 'end',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'data\' of undefined',
     '    at /home/PopcornTV/SubtitleAPI.js:150:61',
     '    at /home/PopcornTV/node_modules/xmlrpc/lib/client.js:130:9',
     '    at callback (/home/PopcornTV/node_modules/xmlrpc/lib/deserializer.js:42:7)',
     '    at Deserializer.onDone (/home/PopcornTV/node_modules/xmlrpc/lib/deserializer.js:92:12)',
     '    at SAXStream.emit (events.js:104:17)',
     '    at Object.SAXStream._parser.onend (/home/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:184:8)',
     '    at emit (/home/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:615:33)',
     '    at end (/home/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:654:3)',
     '    at Object.SAXParser.end (/home/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:149:24)',
     '    at SAXStream.end (/home/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:234:16)' ] }

**Comment by OstlerDev** [comment]
What Movie/TV Show were you trying to watch and with what subtitle?

**Comment by SkOpE-000** [comment]
on that error i was trying to watch aloha. I also tried Pitch Perfect 2. both had the same problems. i did not select any subtitle. also my settings file has this selected as subtitle: "subtitle": "undefined". And i cannot change the setting.

**Comment by OstlerDev** [comment]
The setting is currently disabled right now, so you won't be able to change it. I am looking into this now.

**Comment by SkOpE-000** [comment]
Thanks .. if you need any more info .. happy to provide :)

**Comment by OstlerDev** [comment]
Feel free to try that out :) I tested it and it solved the issues.
