### ISSUE TITLE
Buffer speed on ATV + converting file for Series

### ISSUE THREAD

**Issue by Djimmo** [OstlerDev/PopcornTV#175]
First of all thank you for this amazing application!
It is working very nicely apart from that the buffering speed on ATV seems to be quite a bit slower than buffering the same movie on my desktop using popcorn time program. Are there any settings which could influence this? (VPN on/off, max DL speed, buffer size, number of connections etc.. ?)

Secondly I had a question about the file conversion, for example when trying to watch game of thrones, this does not seem to be working yet! EDIT: I see in the console this is flagged as experimental still. :)

regards,
Djim

**Comment by OstlerDev** [comment]
Firstly, glad you like it!

It should be the same speed as in Popcorn Time so I am not sure what exactly might be slowing it down for you. I will look into it though.

Second, did you make sure to install FFMPEG? It works pretty well most the time unless the download speed is too slow.

**Comment by Djimmo** [comment]
Thanks for your quick answer!

About the file conversion I had put ffmpeg in the wrong spot, stupid me! So that is solved. 

However for buffering and loading movies I also have to add once it gets stuck it does not seem to continue anymore and simply hang. It looks like when it has trouble downloading it just gives up and stops downloading altogether.

**Comment by OstlerDev** [comment]
What you described sounds like attempting to download a torrent taht you already downloaded a bit of before, try erasing the files contained in /assets/torrent-stream/ and /assets/converted/

**Comment by Djimmo** [comment]
I have tried deleting the already downloaded torrents, however this did not improve the buffering/loading movies. Somehow PopcornTV does work 50% of the time and I can perfectly watch the movie/serie without any trouble. However the other times the download speed is too slow or the buffer is too small. Could this be due to the amount of clients it can connect to for downloading, eg. a few fast clients and no problem, but a few slow clients -> freeze ?

When I test this on my computer it does work every time, no buffer or slow loading problems for any movie!

As I understand the PopcornTV program does the downloading and then streams it to the ATV, so the same computer is used to download the movie (either in PopcornTV or PopcornTime). Maybe there is a difference in streambuffersize?

**Comment by OstlerDev** [comment]
Try updating to the latest version.

**Comment by Djimmo** [comment]
I just downloaded the latest files, if I use these files, the program can start up and is giving no errors in the console. However when I go trailers on AppleTv it says: Trailers not available, please try again later

**Comment by OstlerDev** [comment]
You need to reinstall the certificate on the Apple TV since it generated a new one.
