### ISSUE TITLE
Subtitle is not working with the latest update

### ISSUE THREAD

**Issue by Samb00** [OstlerDev/PopcornTV#176]
i just installed the latest update but the subtitle are not working even from the settings  or from the movies itself, it's showing no languages

**Comment by OstlerDev** [comment]
What Movies subtitles were you looking for? I have noticed some movies do not have subtitles, but others do. I believe this happens because opensubtitles.org does not have the IMDB ID for those movies yet.

**Comment by sjako** [comment]
Dont think so. Happens across all movies now

**Comment by OstlerDev** [comment]
I just tested as well and it seems to be happening for me as well. Looking into it now.

**Comment by nicoti** [comment]
i have the same problem as sjko. any  movie have subtitle..

**Comment by OstlerDev** [comment]
It looks like either the opensubtitles.org API is down, or they have changed the API again. I am going to wait an hour to see if this sorts itself out.

**Comment by OstlerDev** [comment]
@Samb00 @sjako @nicoti It looks like the subtitles are back, just was a small temporary outage.
