### ISSUE TITLE
After installing FFmpeg the subtitle option menu is empty

### ISSUE THREAD

**Issue by Wouter1978** [OstlerDev/PopcornTV#178]
Hi,
first I wanted to say that your software is awesome :-)
After I installed FFmpeg the subtitle option menu is empty and the only choose I have under 'Please select your desired language' is Off.

I have installed a clean PopcornTV and deleted the profiel on the AppleTV but that doesn't help.

Can you help me with this.

Best regards, Wouter

**Comment by Wouter1978** [comment]
If fixed it! :-)

**Comment by eralardz** [comment]
How did you fix this? I'm having the same issue.

**Comment by OstlerDev** [comment]
The OpenSubtitles API has been up and down lately, it is not an issue with your install but rather the actual API endpoint.

**Comment by eralardz** [comment]
Oh, ok. Thank you!
