### ISSUE TITLE
FATAL ERROR 'EACCES' (Windows)

### ISSUE THREAD

**Issue by blake4792** [OstlerDev/PopcornTV#179]
https://gist.github.com/anonymous/588bfcab1d78451c9230

user@userPC ~/Desktop/PopcornTV
$ node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.108:53
Web: listening on 192.168.1.108:80
Web: SSL Web: listening on 192.168.1.108:443
error: ========= FATAL ERROR =========
error: Cannot start web Server. Please make sure you are using the correct IP!
error: Error Code: EACCES
error: ===============================

can't figure out how to resolve this fatal error.... any help please? :)

**Comment by diogosmiranda** [comment]
I correct this error by opening all doors like this:
open comand (administrator) enter: net stop was

**Comment by blake4792** [comment]
i tried entering "net stop was" in CMD (administrator) and it says "the service name is invalid"

**Comment by OstlerDev** [comment]
Try running ``net stop``

**Comment by blake4792** [comment]
what service do i want to stop though?

**Comment by OstlerDev** [comment]
Try taking a look here: https://github.com/OstlerDev/PopcornTV/issues/163#issuecomment-129226520

But I am pretty sure you just run the command ``net stop`` with nothing else after it. I do not use windows so I am unsure.
