### ISSUE TITLE
Remote iPhone app not working 

### ISSUE THREAD

**Issue by CodyClark** [OstlerDev/PopcornTV#180]
I hesitate to ask this question because I don't know if PopcornTV could effect this at all. Before routing traffic through PopcornTv I could use the iOS remote app to control the apple tv. Do you know if the iOS Remote will work with Popcorn?

**Comment by OstlerDev** [comment]
It will still work as normal :)

**Comment by Samb00** [comment]
Working very well i tested

**Comment by OstlerDev** [comment]
Gonna close this issue, because I know that it works c:
