### ISSUE TITLE
how to set the default subtitle

### ISSUE THREAD

**Issue by Samb00** [OstlerDev/PopcornTV#181]
Hey my Friend 
i installed the latest update and i find out there an option for the default subtitle, i tried a lot to set it but i couldn't 
can you please tell me how can i do that.

**Comment by OstlerDev** [comment]
It has not been enabled for use yet, try following issue #105 as that is where updates will be posted. If you want to try out a beta version that only supports Movies then you can open up your aTVSettings.json file and where it says  ``Subtitle: 'Off',`` change "Off" to your Language (found [here](https://www.loc.gov/standards/iso639-2/php/code_list.php)) Set it to the iso 639-2.

**Comment by Samb00** [comment]
Working :+1:

**Comment by Sudden78** [comment]
Dosen´t work for swedish.
Have set it to swe but no subtitles showing.

**Comment by OstlerDev** [comment]
As I stated, the feature is not ready for the public, thus why it is not released. I cannot provide support for something that I have stated is not ready.

**Comment by Sudden78** [comment]
Ok sorry.
Thought it was working when it worked for Samb00.

**Comment by OstlerDev** [comment]
It does work, but I have not tested it fully, thus why I cannot provide support really for it :)

**Comment by Sudden78** [comment]
OK
