### ISSUE TITLE
"Trailers is unavailable. Try again later" error

### ISSUE THREAD

**Issue by ScottRD** [OstlerDev/PopcornTV#183]
Everything is working fine except I was watching a particular show (Mr. Robot, a specific episode) and navigated back out to the main menu for PopcornTV and now ONLY when I try to go back into Mr. Robot from finding the title in search, I get: "Trailers is unavailable. Try again later" error.  Again, not at entering Trailers on Apple TV, that's fine, and not on going into other shows or movies just Mr. Robot since I exited and now try to enter again.  I've tried restarting PopcornTV but to no avail.  Is there some cache somewhere that is somehow corrupted or something else I can check or delete, etc...?

**Comment by ScottRD** [comment]
On OS X, btw, if that's relevant.

**Comment by OstlerDev** [comment]
Can you post a log of what is happening using Debug mode? [guide](https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue)

If you do that I can better figure out what might be happening.

**Comment by shripadk** [comment]
I had the same issue. This happened because I changed my router and my DNS configuration changed accordingly. The fix is to reset the DNS setting to automatic, remove the Profile you added in Step 7 as shown in the installation steps here: https://github.com/OstlerDev/PopcornTV/wiki/How-to-install-(Mac) and then access Trailers. It will now load the default Trailers and should stop throwing that error. Then repeat Step 3 - Step 8 of installation again.

I tried running it in Debug mode but could not get any meaningful log entries because Trailers wasn't even opening in the first place.

**Comment by ScottRD** [comment]
Will do, and sorry I missed those instructions.  In the meantime I've noticed it is not just Mr. Robot but some (not even most, just some) other shows also.  Is it possible that's just the error if nobody is seeding or not enough seeds or too slow a speed?

**Comment by OstlerDev** [comment]
If after you press the play button the buffer just never moves, then yes there might be an issue where there is no seeders. But if you cannot get into the episode to select the play button then it is a different issue. If you post your Debug log then I can help you from there :)

**Comment by nicoti** [comment]
is it working on windows 10? Couse since i install wn 10 popcorntv doesn't work any more. It says something about my ip but is the same one as before.

**Comment by OstlerDev** [comment]
If you take a look on the [wiki install page](https://github.com/OstlerDev/PopcornTV/wiki/How-to-Install-(Windows)) you will see ``Step 0`` has [changed](https://github.com/OstlerDev/PopcornTV/wiki/How-to-Install-(Windows))

**Comment by nicoti** [comment]
how do i disable World Wide Web publishing Service??

**Comment by OstlerDev** [comment]
@nicoti Try looking around google, I do not run windows and as such cannot provide a good guide. When you figure it out can you post a tutorial that I can link on the wiki?

**Comment by nicoti** [comment]
ok! i'll try ! thanks

**Comment by nicoti** [comment]
I found on this link a very easy tutorial :https://support.microsoft.com/es-es/kb/930905  It work for me!

**Comment by JakeRound** [comment]
English link https://support.microsoft.com/en-us/kb/930905

**Comment by herosix** [comment]
I managed to get the program partially operational on my AppleTv, but kept getting the error message every time i tried to load a movie/series' page. I then uninstalled the program on both my appletv unit and my mac, but now I'm getting this error message: 

"error: ========= FATAL ERROR =========
error: Cannot bind to Port 53. Please make sure you are not running a DNS server on your machine!
error: Error Code: EADDRINUSE
error: ===============================
Mathias-Mac:popcorntv mathiasmollerup$"

 whenever i type in "$ sudo node atv.js".

Any clue to what is happening? I can try making a log if this is not a common problem.

**Comment by JakeRound** [comment]
Reset your computer, next time don't close the Terminal, stop the sever before hand using Alt & C then proceed to close Terminal.
