### ISSUE TITLE
Mark content as watched

### ISSUE THREAD

**Issue by wahlmanj** [OstlerDev/PopcornTV#184]
Is there a way to somehow mark what shows or movies etc have been watched already?

**Comment by OstlerDev** [comment]
This will be implemented when trakt.tv is implemented :) (it will be done using press and hold)

**Comment by wahlmanj** [comment]
Just noticed #73 my apologies ;)

**Comment by OstlerDev** [comment]
You are fine! I plan on getting trakt.tv all up and running once I have the desktop version working a bit more.
