### ISSUE TITLE
adding the Video Information 

### ISSUE THREAD

**Issue by Samb00** [OstlerDev/PopcornTV#186]
i think it would be good if the video information like "video name, the video quality" shows while the video is paused

**Comment by JakeRound** [comment]
We already have sometime similar implemented which shows movie title & description as shown in @OstlerDev video
![Here](http://i.imgur.com/KsMazS1.jpg)
However a bar similar to what YouTube uses would be pretty sweet to display both movie / tv show title, video quality and movie poster. (Something i might look into when #115 is finished)
![Here](https://i.imgur.com/AL6hmF3.jpg)

**Comment by Samb00** [comment]
Good job guys, you always working on my ideas :D

**Comment by OstlerDev** [comment]
I may go in and add the quality to it, but I do not think that matters too much. I like the youtube one as well, however they have custom code to show the button. Since their code is obfuscated it is very hard to read making it near impossible.
