### ISSUE TITLE
Unotelly

### ISSUE THREAD

**Issue by sjako** [OstlerDev/PopcornTV#187]
Hi,

I have a subscription to Unotelly to use a DNS service outside of my location to watch US content on my ATV. I was expecting by updating config.json with the DNS of Unotelly (instead of 8.8.8.8) I would be able to reroute traffic and watch Netflix via the Unotelly DNS. That does not seem to be the case.

Any thoughts?

**Comment by OstlerDev** [comment]
Did you save the file and restart PopcornTV?

**Comment by sjako** [comment]
I sure did (and the ATV for that matter)

**Comment by OstlerDev** [comment]
From what I am gathering from the UnoTelly website, you need to register the device that is going to be using the DNS with them. For this you would need to register your Desktop (you may also need to register the Apple TV)

Hope that works!

**Comment by OstlerDev** [comment]
Try making sure it is setup for your computer by visiting here: https://www2.unotelly.com/quickstart

The DNS redirection works fine though.
