### ISSUE TITLE
When playing an MKV i get error

### ISSUE THREAD

**Issue by bosox234** [OstlerDev/PopcornTV#189]
Installed FFMPEG but when I play i get the following error

error: =============== ERROR ===============
error: There was an error converting this file at:
error: frame=   30 fps= 20 q=0.0 size=N/A time=00:00:01.60 bitrate=N/A    
error: Please try a different file.
error: =====================================

What could be the issue, did i install it wrong?

Also fantastic work with this project.

**Comment by JakeRound** [comment]
Hai @bosox234 mind posting a whole error log? Also what exactly were you trying to watch?

**Comment by bosox234** [comment]
Here you go, is this enough?

https://gist.github.com/bosox234/5adad876a9f710cf7e8c

I was trying to watch GoT.

**Comment by OstlerDev** [comment]
@bosox234 This happens when it is not downloading fast enough, try choosing a lower quality to stream :+1:

**Comment by bosox234** [comment]
I have 50mb speeds, what is the minimum required?

**Comment by OstlerDev** [comment]
@bosox234 It varies depending on the video file, how long did it take to buffer?

**Comment by bosox234** [comment]
20 seconds or so, so it's more the file rather than my connection. Is this something that is fixable in the future? Sorry for the questions, overall i Love PopcornTV :+1:

**Comment by OstlerDev** [comment]
Yes, you can follow #3 for more information on the matter. The FFMPEG engine we have implemented works, but there is a lot that could be done to improve it.

**Comment by bosox234** [comment]
Do you have an example of an episode where FFMPEG works, I am still yet to get it to stream?
