### ISSUE TITLE
Provide "health" of underlying torrent?

### ISSUE THREAD

**Issue by krugster** [OstlerDev/PopcornTV#190]
In browsing some older tv shows I'm noticing that certain episodes seem to not be able to download enough to even get started playing, or go very slowly

Would it be possible to somehow advertise the "health" of a given episode based on the number of seeds or whatever makes the most sense?

**Comment by OstlerDev** [comment]
This is already implemented, however is only implemented for Movies as we directly know their seeders/peers without having to first download the torrent.
