### ISSUE TITLE
Can't load the addon.(node-images) - v0.1.13 only, OSX

### ISSUE THREAD

**Issue by Mauricevb** [OstlerDev/PopcornTV#195]
I can play one movie, but when I stop the movie and try the open another movie (de movie detail view), I get the following error. On the screen I see "Connecting to Trailers" and then "Trailers is not available".
```
error: uncaughtException: Can't load the addon. Issue to: https://github.com/PopcornTV/node-images/issues Error: Module version mismatch. Expected 14, got 43.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Maurice/PopcornTV/PopcornTV/node_modules/ptv-images/binding.js:52:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12) 
{ date: 'Tue Aug 18 2015 15:58:51 GMT+0200 (CEST)',
  process: 
   { pid: 1020,
     uid: 0,
     gid: 0,
     cwd: '/Users/Maurice/PopcornTV/PopcornTV',
     execPath: '/usr/local/bin/node',
     version: 'v0.12.7',
     argv: [ 'node', '/Users/Maurice/PopcornTV/PopcornTV/atv.js' ],
     memoryUsage: { rss: 84815872, heapTotal: 61766400, heapUsed: 31704712 } },
  os: 
   { loadavg: [ 1.8486328125, 1.78076171875, 1.5400390625 ],
     uptime: 1299 },
  trace: 
   [ { column: null,
       file: null,
       function: 'Error',
       line: null,
       method: null,
       native: true },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 355,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 310,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 365,
       method: 'require',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'require',
       line: 384,
       method: null,
       native: false },
     { column: 34,
       file: '/Users/Maurice/PopcornTV/PopcornTV/node_modules/ptv-images/binding.js',
       function: '',
       line: 52,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 460,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 478,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 355,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 310,
       method: 'Module._load',
       native: false },
     { column: 23,
       file: '/Users/Maurice/PopcornTV/PopcornTV/node_modules/ptv-images/binding.js',
       function: '',
       line: 55,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 460,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 478,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 355,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 310,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 365,
       method: 'require',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'require',
       line: 384,
       method: null,
       native: false },
     { column: 15,
       file: '/Users/Maurice/PopcornTV/PopcornTV/node_modules/ptv-images/index.js',
       function: '',
       line: 4,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 460,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 478,
       method: 'Module._extensions..js',
       native: false } ],
  stack: 
   [ 'Error: Can\'t load the addon. Issue to: https://github.com/PopcornTV/node-images/issues Error: Module version mismatch. Expected 14, got 43.',
     '    at Error (native)',
     '    at Module.load (module.js:355:32)',
     '    at Function.Module._load (module.js:310:12)',
     '    at Module.require (module.js:365:17)',
     '    at require (module.js:384:17)',
     '    at Object.<anonymous> (/Users/Maurice/PopcornTV/PopcornTV/node_modules/ptv-images/binding.js:52:34)',
     '    at Module._compile (module.js:460:26)',
     '    at Object.Module._extensions..js (module.js:478:10)',
     '    at Module.load (module.js:355:32)',
     '    at Function.Module._load (module.js:310:12)',
     '    at Object.<anonymous> (/Users/Maurice/PopcornTV/PopcornTV/node_modules/ptv-images/binding.js:55:23)',
     '    at Module._compile (module.js:460:26)',
     '    at Object.Module._extensions..js (module.js:478:10)',
     '    at Module.load (module.js:355:32)',
     '    at Function.Module._load (module.js:310:12)',
     '    at Module.require (module.js:365:17)',
     '    at require (module.js:384:17)',
     '    at Object.<anonymous> (/Users/Maurice/PopcornTV/PopcornTV/node_modules/ptv-images/index.js:4:15)',
     '    at Module._compile (module.js:460:26)',
     '    at Object.Module._extensions..js (module.js:478:10)' ] }

```

**Comment by OstlerDev** [comment]
There might have been issues in the ptv-images repository. I will test it out and get back to you.

**Comment by oki46** [comment]
Hi, 

It seems I've got the same problem (OS X YOSEMITE + V0.1.13.)
It works once, but then If I got this:

I Don't understand why.


 [ 'Error: Can\'t load the addon. Issue to: https://github.com/PopcornTV/node-images/issues Error: Module version mismatch. Expected 14, got 43.',
     '    at Error (native)',
     '    at Module.load (module.js:355:32)',
     '    at Function.Module._load (module.js:310:12)',
     '    at Module.require (module.js:365:17)',
     '    at require (module.js:384:17)',
     '    at Object.<anonymous> (/Users/antoineocchipinti/Desktop/PopcornTV/node_modules/ptv-images/binding.js:52:34)',
     '    at Module._compile (module.js:460:26)',
     '    at Object.Module._extensions..js (module.js:478:10)',
     '    at Module.load (module.js:355:32)',
     '    at Function.Module._load (module.js:310:12)',
     '    at Object.<anonymous> (/Users/antoineocchipinti/Desktop/PopcornTV/node_modules/ptv-images/binding.js:55:23)',
     '    at Module._compile (module.js:460:26)',
     '    at Object.Module._extensions..js (module.js:478:10)',
     '    at Module.load (module.js:355:32)',
     '    at Function.Module._load (module.js:310:12)',
     '    at Module.require (module.js:365:17)',
     '    at require (module.js:384:17)',
     '    at Object.<anonymous> (/Users/antoineocchipinti/Desktop/PopcornTV/node_modules/ptv-images/index.js:4:15)',
     '    at Module._compile (module.js:460:26)',
     '    at Object.Module._extensions..js (module.js:478:10)' ] }
error: Error: Can't load the addon. Issue to: https://github.com/PopcornTV/node-images/issues Error: Module version mismatch. Expected 14, got 43.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/antoineocchipinti/Desktop/PopcornTV/node_modules/ptv-images/binding.js:52:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/Users/antoineocchipinti/Desktop/PopcornTV/node_modules/ptv-images/binding.js:55:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/antoineocchipinti/Desktop/PopcornTV/node_modules/ptv-images/index.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
DNS: Blocking ATV Update Attempt
DNS: setup.icloud.com

**Comment by OstlerDev** [comment]
Please run ``npm update`` it should work. I just updated the ptv-images module.

**Comment by oki46** [comment]
Super Thx. It works.

**Comment by rodrigordi** [comment]
Hi. There is  a problem if you use node.js v4.0.0.0. 
I did unistall version 4.0.0.0 and then I install version 0.12.0.
And now this works fine. I am using windows 10.

Could be a problem in "if (compiler(versions[0], cur) <= 0 && compiler(versions[1], cur) >= 0)" because using version 4, this IF will be false always and will throw error on line 61 of bindings.js

Great!

**Comment by OstlerDev** [comment]
It's going to require an update to the database.

**Comment by GisliR** [comment]
Had the problem. Installing node.js version 0.12.0 fixed it. Thanx guys

**Comment by OstlerDev** [comment]
@GisliR I just need to update ptv-images, but yeah downgrading or just plain installing 0.12.0 works just fine :)

**Comment by GisliR** [comment]
Great job btw Ostler. Finally found a use for that wretched ATV my friends got for my birthday. :D

**Comment by OstlerDev** [comment]
@GisliR Glad you like it! I really love being able to watch anything with just a click :)
