### ISSUE TITLE
0.1.5 - error on AppleTv

### ISSUE THREAD

**Issue by brunojalves** [OstlerDev/PopcornTV#20]
Hi,

I'm testing the new version 0.1.5 with my appletv and ubuntu 15.05, and with the version 0.1.4 i can run, but wen using this one i'm getting and error wen open the trailers.
Trailers are not available. please try again latter.

There is some way to have more verbose, wen run the PopcornTV, on command line i do not see any error.

Regrads,

**Comment by OstlerDev** [comment]
Does it happened right as you open the trailers application or can you open some pages? Have you made sure to add the certificate to your Apple TV?

I plan to add the high logging setting once I am home so that people can better report errors.

**Comment by brunojalves** [comment]
wen i open some page related to Apple, like Movies and Music, i can open put nothing is showing.

Ok, 

Yes is that the problem, add the certificate again to apple tv. 

Thanks

**Comment by OstlerDev** [comment]
Glad that works for you, enjoy!

**Comment by brunojalves** [comment]
This is normal, Photos on icloud app do not show new photos

**Comment by OstlerDev** [comment]
I have not tested the photos app and that should not affect anything other than the trailers application.

**Comment by brunojalves** [comment]
i think i solve the problem, wen i forget to load the certificate, i saw on appletv something can't access your account.
Just remove and add again my account and the photos are back.

Thank again.

Regards, if you need any help, please let me know.
