### ISSUE TITLE
Unable to open the trailer section on the apple TV

### ISSUE THREAD

**Issue by flopapp** [OstlerDev/PopcornTV#200]
After doing over and over the all installation process I finally succeeded once, then, when I started a movie to try if it was working, it wouldn't open the movie saying that the movie wasn't available. Since then, I can't even open the trailer section... it says that it is not available. 
The Terminal writes this at the same time : 
DNS: www.apple.com
DNS: p20-buy.itunes.apple.com
DNS: pd-nk.itunes.apple.com
DNS: a5.mzstatic.com

did I do anything wrong ? How could I make it work ?

Thank you!

**Comment by OstlerDev** [comment]
Try restarting your Apple TV.
