### ISSUE TITLE
Missing episodes?

### ISSUE THREAD

**Issue by krugster** [OstlerDev/PopcornTV#202]
This is probably more of a question than a bug, but curious how we should go about diagnosing and reporting missing TV episodes?

**Comment by OstlerDev** [comment]
From the Popcorn Time Forum
```
Why is episode X of TV show Y missing?
All episodes and tv shows come from multiple sources on the internet that are collected. If anything is missing or not right, report it in the content provider category on the forum.
```
So basically just post it here: https://discuss.popcorntime.io/c/related-services/content-providers
