### ISSUE TITLE
Adding Profile fails

### ISSUE THREAD

**Issue by alesrosina** [OstlerDev/PopcornTV#203]
I went through all steps, but it fails when adding profile - Apple TV just stops at "adding profile" loading page and shows infinite loader. If I enter "http://trailers.apple.com/trailers.cer" in browser, got 404 error on apple.com.

I have a jailbroken Apple TV 2 and running nodejs code on my mac, if that makes any difference.

**Comment by OstlerDev** [comment]
Did you make sure to leave PopcornTV running on your Mac? It must be running at all times.

**Comment by alesrosina** [comment]
Yeah. 
I got this output once when clicking OK on add profile on TV:
```
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.6:53
Web: listening on 192.168.1.6:80
Web: SSL Web: listening on 192.168.1.6:443
notice: Starting Commit 63bbedf
DNS: time.apple.com
DNS: init.itunes.apple.com
DNS: sr.symcd.com
DNS: itunes.apple.com
DNS: xp.apple.com
DNS: EVIntl-ocsp.verisign.com
DNS: EVSecure-ocsp.verisign.com
DNS: configuration.apple.com
DNS: cl2.apple.com
DNS: e8218.ce.akamaiedge.net
```
Mostly its just sitting there idle:
```
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.6:53
Web: listening on 192.168.1.6:80
Web: SSL Web: listening on 192.168.1.6:443
notice: Starting Commit 63bbedf
```

So not sure what is going on - are there any other debug options?

**Comment by OstlerDev** [comment]
You can run it using ``sudo node atv.js Debug`` if you are on a Mac, and just ``node atv.js Debug`` if on Windows. If the profile is added you should be ok to go into the Trailers Application.

**Comment by alesrosina** [comment]
How long does it usually take to add a profile? I'm waiting now for several minutes and also debug version is not throwing me anything. Apple TV is stuck on "Adding profile" loader ...

There are some different DNS popping out, but apple tv is still stuck on "Adding profile" loader.
```
DNS: gs-loc.apple.com
DNS: gs-loc.apple.com
DNS: e8218.ce.akamaiedge.net
```

**Comment by OstlerDev** [comment]
It should take 3-5 seconds. Here are some steps you can try next. (attempt to add the profile after each step)

1. Restart the Apple TV
2. Restart your Computer
3. Completely close, delete, and reclone PopcornTV then reinstall on your Apple TV.

**Comment by alesrosina** [comment]
Hey, thanks for your help - I did a complete restore of Apple TV (thus removing jailbreak) and now it works. Not sure jailbreak was the issue, but anyhow it's working now.

Thanks for your help.

PS: Is there any option to run your server on raspbery pi? That would be perfect, but i just cannot manage to run it there. But I guess that question for a new issue :)

**Comment by OstlerDev** [comment]
I plan on creating a guide for the Raspi, however I am not sure if it would require the Raspi 2. I believe for certain functions it would require the faster processor and more ram, but as money is tight for me right now I cannot invest in getting that hardware. (I only have the first generation Raspi)

**Comment by alesrosina** [comment]
I also have the first gen. If you mange to stuck it on first gen, that would be awesome.

Will close this issue and follow git page for raspi guide.

Thanks man!

**Comment by OstlerDev** [comment]
No problem! Enjoy!
