### ISSUE TITLE
Set Default Subtitles

### ISSUE THREAD

**Issue by silentwarrior** [OstlerDev/PopcornTV#205]
Hello.

How can i set the default subtitles? In the menu it wont show any options. 

On "aTVSettings.json" it says "subtitle: "Off", but i dont know the correct "text" for english subtitles.

**Comment by Sudden78** [comment]
Read issue 181

https://github.com/OstlerDev/PopcornTV/issues/181

**Comment by OstlerDev** [comment]
Issue #105 is actually the issue to follow for updates :)

If you would like to test the feature in a very alpha way then please set it to ``eng``
