### ISSUE TITLE
Watching movies by browsing them from Genre will not work

### ISSUE THREAD

**Issue by acalatrava** [OstlerDev/PopcornTV#207]
If you select Movies -> Genre and select a movie it will not load.

http://pastebin.com/bCeTdUba

**Comment by OstlerDev** [comment]
Looks more like an issue with the default subtitle you defined: 

`` 2015-08-25T17:59:11.021Z - Debug: Default Subtitle Language Defined as: spa ``

I just tested it on my own and it loads perfectly fine.
