### ISSUE TITLE
Movie downloads are kept

### ISSUE THREAD

**Issue by masonjames** [OstlerDev/PopcornTV#21]
Screenshot below shows what happens.  I started to watch a movie last night, but didn't finish. However it looks like a copy of the movie was made locally (4094.mp4 is nearly a gig).

I started a different movie today and a new mp4 was created (4021.mp4).
![popcorntv](https://cloud.githubusercontent.com/assets/297610/7949475/1beb22a8-095c-11e5-8cd9-f589d3fd1d30.png)

Is this expected?

**Comment by OstlerDev** [comment]
Yes, this is currently expected. I will be adding in a setting to delete videos when the stream ends in the next version hopefully. The way it works is the streamer streams the file named (torrent-id).mp4 and so it saves it to the directory. If you also watch a trailer it will do the same. This is bad for systems that have a small amount of disk space.

There is also an issue where it downloads the full torrent files to /tmp making two copies of each file. I hope to fix this as well in the next version or sooner. This will mean that it needs to stream the full file each time.

**Comment by OstlerDev** [comment]
I have added this setting to the settings page in the latest commit. I should have it working shortly, which will allow us to save some storage if desired!

**Comment by OstlerDev** [comment]
In the settings menu set Keep Movies to Off, it will from then on automatically delete all of the videos as well as the TMP folder.

**Comment by OstlerDev** [comment]
This setting /might/ crash the process on Windows computers. If someone could please report where the torrent-stream data is stored on windows I can fix this possibile issue.
