### ISSUE TITLE
Cant start PopcornTV

### ISSUE THREAD

**Issue by bob1321** [OstlerDev/PopcornTV#212]
I have an error when I enter node atv.js

Microsoft Windows [version 10.0.10240]
(c) 2015 Microsoft Corporation. Tous droits réservés.

C:\Users\pas_c>C:\Users\pas_c\Desktop\PopcornTV
'C:\Users\pas_c\Desktop\PopcornTV' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\pas_c>cd C:\Users\pas_c\Desktop\PopcornTV

C:\Users\pas_c\Desktop\PopcornTV>npm install
npm WARN package.json popcorntv@ No license field.
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
|

> ptv-images@2.1.11 install C:\Users\pas_c\Desktop\PopcornTV\node_modules\ptv-images
> echo 'ptv-images Installed'

'ptv-images Installed'
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
read-chunk@1.0.1 node_modules\read-chunk

range-parser@1.0.2 node_modules\range-parser

git-rev@0.2.1 node_modules\git-rev

ip@0.3.3 node_modules\ip

xml@1.0.0 node_modules\xml

mime@1.3.4 node_modules\mime

xml-writer@1.6.0 node_modules\xml-writer

underscore@1.8.3 node_modules\underscore

q@1.4.1 node_modules\q

URIjs@1.16.0 node_modules\URIjs

pump@1.0.0 node_modules\pump
├── end-of-stream@1.1.0
└── once@1.3.2 (wrappy@1.0.1)

pem@1.8.0 node_modules\pem
└── which@1.0.9

iconv-lite@0.4.11 node_modules\iconv-lite

progress-stream@1.1.1 node_modules\progress-stream
├── single-line-log@0.3.1
├── speedometer@0.1.4
└── through2@0.2.3 (xtend@2.1.2, readable-stream@1.1.13)

streamify@0.2.4 node_modules\streamify
├── readable-stream@1.1.13 (inherits@2.0.1, isarray@0.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── hashish@0.0.4 (traverse@0.6.6)

file-type@2.10.2 node_modules\file-type
└── meow@3.3.0 (object-assign@3.0.0, camelcase-keys@1.0.0, minimist@1.2.0, indent-string@1.2.2)

rimraf@2.4.3 node_modules\rimraf
└── glob@5.0.14 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)

winston@1.0.1 node_modules\winston
├── cycle@1.0.3
├── stack-trace@0.0.9
├── eyes@0.1.8
├── isstream@0.1.2
├── pkginfo@0.3.0
├── async@0.9.2
└── colors@1.0.3

xmlrpc@1.3.1 node_modules\xmlrpc
├── xmlbuilder@2.6.4
└── sax@0.6.1

parse-torrent@5.3.0 node_modules\parse-torrent
├── get-stdin@4.0.1
├── dezalgo@1.0.3 (wrappy@1.0.1, asap@2.0.3)
├── simple-get@1.4.3 (unzip-response@1.0.0, xtend@4.0.0, once@1.3.2)
├── magnet-uri@5.0.0 (uniq@1.0.1, xtend@4.0.0, thirty-two@0.0.2)
└── parse-torrent-file@3.2.1 (uniq@1.0.1, bencode@0.7.0, simple-sha1@2.0.7)

read-torrent@1.3.0 node_modules\read-torrent
├── xtend@4.0.0
├── magnet-uri@2.0.1 (thirty-two@0.0.2)
├── parse-torrent@4.1.0 (magnet-uri@4.2.3, parse-torrent-file@2.1.4)
└── request@2.16.6 (forever-agent@0.2.0, aws-sign@0.2.0, tunnel-agent@0.2.0, oauth-sign@0.2.0, json-stringify-safe@3.0.0, cookie-jar@0.2.0, mime@1.2.11, node-uuid@1.4.3, form-data@0.0.10, qs@0.5.6, hawk@0.10.2)

torrent-stream@0.21.3 node_modules\torrent-stream
├── bitfield@0.1.0
├── thunky@0.1.0
├── hat@0.0.3
├── random-access-file@0.3.1
├── mkdirp@0.3.5
├── ip-set@1.0.0
├── end-of-stream@0.1.5 (once@1.3.2)
├── bncode@0.5.3
├── compact2string@1.4.0 (ipaddr.js@1.0.3)
├── bittorrent-dht@3.2.6 (inherits@2.0.1, buffer-equal@0.0.1, addr-to-ip-port@1.4.1, network-address@1.0.0, once@1.3.2, simple-get@1.4.3, k-bucket@0.5.0, bencode@0.7.0, debug@2.2.0, string2compact@1.2.2, is-ip@1.0.0, run-parallel@1.1.2)
├── bittorrent-tracker@2.12.1 (inherits@2.0.1, buffer-equal@0.0.1, extend.js@0.0.2, once@1.3.2, bn.js@1.3.0, simple-get@1.4.3, debug@2.2.0, portfinder@0.3.0, string2compact@1.2.2, run-series@1.1.2, bencode@0.6.0)
├── parse-torrent@4.1.0 (magnet-uri@4.2.3, parse-torrent-file@2.1.4)
└── peer-wire-swarm@0.12.1 (fifo@0.1.4, speedometer@0.1.4, once@1.3.2, utp@0.0.7, peer-wire-protocol@0.7.0)

lodash@3.10.1 node_modules\lodash

ptv-images@2.1.11 node_modules\ptv-images

request@2.55.0 node_modules\request
├── caseless@0.9.0
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── stringstream@0.0.4
├── oauth-sign@0.6.0
├── tunnel-agent@0.4.1
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── node-uuid@1.4.3
├── qs@2.4.2
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── form-data@0.2.0 (async@0.9.2)
├── mime-types@2.0.14 (mime-db@1.12.0)
├── bl@0.9.4 (readable-stream@1.0.33)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── tough-cookie@2.0.0
├── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.8.0, hoek@2.14.0)
└── har-validator@1.8.0 (commander@2.8.1, chalk@1.1.1, bluebird@2.9.34, is-my-json-valid@2.12.2)

semantic-release@6.0.1 node_modules\semantic-release
├── require-relative@0.8.7
├── @semantic-release/error@1.0.0
├── @semantic-release/condition-travis@4.1.2
├── parse-github-repo-url@1.0.0
├── nerf-dart@1.0.0
├── semver@5.0.1
├── nopt@3.0.3 (abbrev@1.0.7)
├── run-auto@1.1.3 (dezalgo@1.0.3)
├── run-series@1.1.2 (dezalgo@1.0.3)
├── npmlog@1.2.1 (ansi@0.3.0, are-we-there-yet@1.0.4, gauge@1.2.2)
├── npmconf@2.1.2 (ini@1.3.4, uid-number@0.0.5, inherits@2.0.1, once@1.3.2, config-chain@1.1.9, osenv@0.1.3, mkdirp@0.5.1, semver@4.3.6)
├── git-head@1.2.1 (git-refs@1.1.3)
├── github@0.2.4
├── @semantic-release/commit-analyzer@2.0.0 (conventional-changelog@0.0.17)
├── @semantic-release/release-notes-generator@2.0.0 (github-url-from-git@1.4.0, conventional-changelog@0.0.17)
└── @semantic-release/last-release-npm@1.2.1 (npm-registry-client@7.0.1)

ytdl-core@0.5.1 node_modules\ytdl-core
├── jstream@0.2.7 (readable-stream@1.1.13, clarinet@0.8.1)
└── cheerio@0.18.0 (entities@1.1.1, lodash@2.4.2, dom-serializer@0.0.1, CSSselect@0.4.1, htmlparser2@3.8.3)

C:\Users\pas_c\Desktop\PopcornTV>node atv.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'winston-loggly'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\pas_c\Desktop\PopcornTV\logger.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

C:\Users\pas_c\Desktop\PopcornTV>

**Comment by OstlerDev** [comment]
My bad, when I removed loggly from the repository there was an issue where I left one line of code in. Try updating to the latest and starting it back up.

**Comment by bob1321** [comment]
thx its working now

**Comment by OstlerDev** [comment]
No problem! Enjoy.
