### ISSUE TITLE
How can I use PlexConnect and PopcornTV on different computer

### ISSUE THREAD

**Issue by bob1321** [OstlerDev/PopcornTV#213]
If I install plexconnect dand PopcornTV on different computer, can I use both?

**Comment by OstlerDev** [comment]
Yes, get PlexConnect working on a different app other then the trailers application, then in config.json put the IP of the PlexConnect computer.

Once you do that you should be good to go!

**Comment by bob1321** [comment]
Not working, I have this error

error: ========= FATAL ERROR =========
error: Cannot start DNS Server. Please make sure you are using the correct IP!
error: Error Code: EADDRNOTAVAIL
error: ===============================

**Comment by OstlerDev** [comment]
You need to put the PlexConnect IP as the DNS IP, replacing `8.8.8.8` (which is googles public DNS server). Don't change the local IP that it already had in there for "ip"

**Comment by bob1321** [comment]
so if my PlexConnect ip is 192.168.1.175

my config.json will be this?
{
    "ip": "192.168.1.110",
    "default_dns": "192.168.1.175"
}

**Comment by OstlerDev** [comment]
Yes, that is correct

**Comment by OstlerDev** [comment]
You will need to install PlexConnect on an application other then trailers, such as iMovie theater

**Comment by bob1321** [comment]
yep I already did that, but on the Apple TV wich IP I need to write?

**Comment by bob1321** [comment]
Because my Apple TV only open Plex Connect on iMovie, PopcornTV doesnt open on Trailers :/

**Comment by OstlerDev** [comment]
Your PopcornTV IP

**Comment by bob1321** [comment]
If I do that only PopcornTV will open no?

**Comment by OstlerDev** [comment]
No. We are redirecting all traffic that is not PopcornTV onto PlexConnect to handle.

**Comment by bob1321** [comment]
ohh okok thx

**Comment by bob1321** [comment]
Now PlexConnect dont open, its iMovie instead
Did in need to change imovie.cer?

**Comment by OstlerDev** [comment]
You need to have both the trailers certificate and the iMovie certificate.
