### ISSUE TITLE
Installation issue "No license field"

### ISSUE THREAD

**Issue by xavsoub** [OstlerDev/PopcornTV#216]
Hello,

Thank you for your work, it looks truly amazing. I can't manage to install though. I followed thoroughly your instructions on Github. Do you have any idea what i could do to make it work ?

Below is what i get when i want to install.

BR

MacBook-Pro:~ xavsoub$ cd desktop
MacBook-Pro:desktop xavsoub$ cd popcorntv
MacBook-Pro:popcorntv xavsoub$ sudo npm install
npm WARN package.json popcorntv@ No license field.
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
 
> ptv-images@2.1.11 install /Users/xavsoub/Desktop/PopcornTV/node_modules/ptv-images
> echo 'ptv-images Installed'

ptv-images Installed
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
read-chunk@1.0.1 node_modules/read-chunk

range-parser@1.0.2 node_modules/range-parser

git-rev@0.2.1 node_modules/git-rev

ip@0.3.3 node_modules/ip

xml@1.0.0 node_modules/xml

mime@1.3.4 node_modules/mime

xml-writer@1.6.0 node_modules/xml-writer

underscore@1.8.3 node_modules/underscore

q@1.4.1 node_modules/q

pump@1.0.0 node_modules/pump
├── end-of-stream@1.1.0
└── once@1.3.2 (wrappy@1.0.1)

pem@1.8.0 node_modules/pem
└── which@1.0.9

URIjs@1.16.0 node_modules/URIjs

iconv-lite@0.4.11 node_modules/iconv-lite

file-type@2.10.2 node_modules/file-type
└── meow@3.3.0 (object-assign@3.0.0, minimist@1.2.0, camelcase-keys@1.0.0, indent-string@1.2.2)

streamify@0.2.4 node_modules/streamify
├── readable-stream@1.1.13 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── hashish@0.0.4 (traverse@0.6.6)

progress-stream@1.1.1 node_modules/progress-stream
├── single-line-log@0.3.1
├── speedometer@0.1.4
└── through2@0.2.3 (xtend@2.1.2, readable-stream@1.1.13)

rimraf@2.4.3 node_modules/rimraf
└── glob@5.0.14 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)

parse-torrent@5.3.0 node_modules/parse-torrent
├── get-stdin@4.0.1
├── dezalgo@1.0.3 (wrappy@1.0.1, asap@2.0.3)
├── simple-get@1.4.3 (unzip-response@1.0.0, xtend@4.0.0, once@1.3.2)
├── magnet-uri@5.0.0 (uniq@1.0.1, xtend@4.0.0, thirty-two@0.0.2)
└── parse-torrent-file@3.2.1 (uniq@1.0.1, bencode@0.7.0, simple-sha1@2.0.7)

winston@1.0.1 node_modules/winston
├── cycle@1.0.3
├── stack-trace@0.0.9
├── eyes@0.1.8
├── isstream@0.1.2
├── pkginfo@0.3.0
├── async@0.9.2
└── colors@1.0.3

xmlrpc@1.3.1 node_modules/xmlrpc
├── xmlbuilder@2.6.4
└── sax@0.6.1

read-torrent@1.3.0 node_modules/read-torrent
├── xtend@4.0.0
├── magnet-uri@2.0.1 (thirty-two@0.0.2)
├── parse-torrent@4.1.0 (magnet-uri@4.2.3, parse-torrent-file@2.1.4)
└── request@2.16.6 (forever-agent@0.2.0, aws-sign@0.2.0, tunnel-agent@0.2.0, oauth-sign@0.2.0, json-stringify-safe@3.0.0, cookie-jar@0.2.0, mime@1.2.11, node-uuid@1.4.3, form-data@0.0.10, qs@0.5.6, hawk@0.10.2)

request@2.55.0 node_modules/request
├── caseless@0.9.0
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── stringstream@0.0.4
├── oauth-sign@0.6.0
├── tunnel-agent@0.4.1
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── node-uuid@1.4.3
├── qs@2.4.2
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── form-data@0.2.0 (async@0.9.2)
├── mime-types@2.0.14 (mime-db@1.12.0)
├── bl@0.9.4 (readable-stream@1.0.33)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── tough-cookie@2.0.0
├── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.8.0, hoek@2.14.0)
└── har-validator@1.8.0 (commander@2.8.1, chalk@1.1.1, is-my-json-valid@2.12.2, bluebird@2.9.34)

torrent-stream@0.21.3 node_modules/torrent-stream
├── bitfield@0.1.0
├── thunky@0.1.0
├── hat@0.0.3
├── random-access-file@0.3.1
├── mkdirp@0.3.5
├── ip-set@1.0.0
├── end-of-stream@0.1.5 (once@1.3.2)
├── bncode@0.5.3
├── compact2string@1.4.0 (ipaddr.js@1.0.3)
├── peer-wire-swarm@0.12.1 (fifo@0.1.4, speedometer@0.1.4, once@1.3.2, utp@0.0.7, peer-wire-protocol@0.7.0)
├── bittorrent-dht@3.2.6 (buffer-equal@0.0.1, inherits@2.0.1, addr-to-ip-port@1.4.1, network-address@1.0.0, once@1.3.2, is-ip@1.0.0, simple-get@1.4.3, k-bucket@0.5.0, bencode@0.7.0, debug@2.2.0, string2compact@1.2.2, run-parallel@1.1.2)
├── parse-torrent@4.1.0 (magnet-uri@4.2.3, parse-torrent-file@2.1.4)
└── bittorrent-tracker@2.12.1 (inherits@2.0.1, buffer-equal@0.0.1, extend.js@0.0.2, once@1.3.2, simple-get@1.4.3, bn.js@1.3.0, debug@2.2.0, portfinder@0.3.0, string2compact@1.2.2, run-series@1.1.2, bencode@0.6.0)

lodash@3.10.1 node_modules/lodash

ptv-images@2.1.11 node_modules/ptv-images

semantic-release@6.0.1 node_modules/semantic-release
├── require-relative@0.8.7
├── @semantic-release/error@1.0.0
├── @semantic-release/condition-travis@4.1.2
├── parse-github-repo-url@1.0.0
├── nerf-dart@1.0.0
├── semver@5.0.1
├── nopt@3.0.3 (abbrev@1.0.7)
├── run-auto@1.1.3 (dezalgo@1.0.3)
├── run-series@1.1.2 (dezalgo@1.0.3)
├── npmlog@1.2.1 (ansi@0.3.0, gauge@1.2.2, are-we-there-yet@1.0.4)
├── npmconf@2.1.2 (uid-number@0.0.5, ini@1.3.4, inherits@2.0.1, once@1.3.2, osenv@0.1.3, config-chain@1.1.9, semver@4.3.6, mkdirp@0.5.1)
├── git-head@1.2.1 (git-refs@1.1.3)
├── @semantic-release/commit-analyzer@2.0.0 (conventional-changelog@0.0.17)
├── @semantic-release/release-notes-generator@2.0.0 (github-url-from-git@1.4.0, conventional-changelog@0.0.17)
├── github@0.2.4
└── @semantic-release/last-release-npm@1.2.1 (npm-registry-client@7.0.1)

ytdl-core@0.5.1 node_modules/ytdl-core
├── cheerio@0.18.0 (entities@1.1.1, dom-serializer@0.0.1, htmlparser2@3.8.3, CSSselect@0.4.1, lodash@2.4.2)
└── jstream@0.2.7 (readable-stream@1.1.13, clarinet@0.8.1)

**Comment by OstlerDev** [comment]
That is not an issue, just a warning. You are find to continue on with the installation.
