### ISSUE TITLE
Partial word search matches

### ISSUE THREAD

**Issue by krugster** [OstlerDev/PopcornTV#218]
Looks like the search currently only supports full word matches.  Could it be enhanced to support partial words as well?

For example, when looking for "The Big Bang Theory":
-If I put in "Big" or "Bang" or "Big Bang" then it finds the show
-If I start typing "Bi" or "Ban" then nothing shows up until I finish at least one of the words.  

Is the search being done within PopcornTV or just as a request to the API?

**Comment by OstlerDev** [comment]
It is being done using a request to the API.

**Comment by hiblen** [comment]
I found this on google, not sure there is an answer to the original question though?
