### ISSUE TITLE
Show PopcornTV icon instead of trailers icon

### ISSUE THREAD

**Issue by pitercio** [OstlerDev/PopcornTV#22]
Not an issue, but a "nice to have" feature: Using the same steps provided here...

   https://forums.plex.tv/index.php/topic/95309-trailers-icon-to-plex-icon/

... wouldn't it be nice to have a PopcornTV icon? :)

(Using this, the Plex icon has been nicely showing on my Apple TV for ages...)

**Comment by masonjames** [comment]
Oh nice! I love this idea +1

**Comment by OstlerDev** [comment]
The problem with this is it requires the user to reset their Apple TV, for some this isn't an issue, for others it is. I might implement something for this in the future.

**Comment by OstlerDev** [comment]
If I do end up implementing this I will be putting it on a different repository or application.

**Comment by OstlerDev** [comment]
If added this will be put into the desktop application.
