### ISSUE TITLE
Enhancement: Try to hijack the youtube api/app

### ISSUE THREAD

**Issue by loekup** [OstlerDev/PopcornTV#221]
I think if you manage to hijack the youtube api call you can make this app work for tons off devices, think about samsung smart tv's, mobile phones etc. etc.

**Comment by wahlmanj** [comment]
You understand this is for hijacking aTV's apps right?

**Comment by OstlerDev** [comment]
@loekup It is not really possibile to hijack the Youtube App, HOWEVER, I do think it would be possibile to make a port of this to serve up a website. Meaning that you could open a page on your iPhone or similar device and interact with PopcornTV.

This is outside the scope of the current project so I am going to close this issue.
