### ISSUE TITLE
node-images can't load bindings.node on raspberry pi

### ISSUE THREAD

**Issue by masonjames** [OstlerDev/PopcornTV#223]
Hiya, 

Me again.  I've tried a fresh install, as well as applying your forked version of the node-images module here:
https://github.com/PopcornTV/node-images

In either case the atv.js file loads up, and allows me to select any move/tv show, but on selection it throws a few errors;
https://gist.github.com/masonjames/d6d10efd3ed981bbc109

Note both line 2 & 154 are looking for "bindings/linux/arm/0.9.11/binding.node" which I do not believe I have.  Not sure if that's the actual issue or I'm missing something else.  I'm only running node v0.10.22 as they haven't had an update that supported raspberry pi in awhile (as far as I can tell) but npm is 2.14.2.

Tried running through the step by step instructions for node-images and everything went well there. Just trying to get this one module to work and I think I'll be in good shape. Any thoughts?

**Comment by OstlerDev** [comment]
Were you able to build the binding? (as outlined here: https://github.com/PopcornTV/node-images/wiki/How-to-build-a-binding)

I would suggest attempting to update to a later node version (if you can). If you are able to build a binding successfully it should work for you locally, after that it would be a great help if you could upload  the new binding here for me to add to the main repository.

**Comment by masonjames** [comment]
I'm trying this out on my Raspberry pi. After a bunch of digging I finally found an updated version (0.12.2) that will compile correctly on the Raspberry Pi:
http://conoroneill.net/node-v0122-for-arm-v6v7-including-raspberry-pi-raspberry-pi-2-and-odroid-c1

Anyway, now successfully running 0.12.2 I'm still getting the bindings issue. I was able to build a binding as outlined, but I'm not sure how to read/share the build/Release/binding.node file

Will keep digging :)

**Comment by OstlerDev** [comment]
@masonjames were you able to get it working?

**Comment by masonjames** [comment]
Sadly, still stuck on getting node-images installed. This means PopcornTV technically loads, but fails on the final screen due to this error:
https://github.com/PopcornTV/node-images/issues/4

Right now I run popcorntv with forever start atv.js so that I can keep it running when I close out the ssh session, but have been thinking about adding it as part of the boot loading since I'd prefer to always have it on and available.

I made a quick video demo of what's running on my raspberry pi (includes props to PopcornTV - terrible video quality, but gives an idea):
https://www.youtube.com/watch?v=SL5rQDYEJTI

Any help is appreciated, but it's not a PopcornTV issue - it's something with node/gyp/node-images that isn't compiling properly.

**Comment by Pizara** [comment]
@masonjames : I got it fully functional on a Raspberry Pi 2 - Model B on Raspberian

- do an apt-get update and upgrade on a fresh install, install nodejs & npm, clone popcorntv and follow the Mac install instructions. (npm install etc.)
- create a new /arm/0.12.0/ folder in ..[[popcorntv folder]]/node-modules/ptv-images/bindings/linux

- and all you have to do to make it work, is to copy this file into a new folder: 
https://github.com/NosirrahBlanca/node-images/blob/master/bindings/linux/arm/0.12.0/binding.node

@OstlerDev : can you include this file also into your node-images repo?

**Comment by masonjames** [comment]
Thanks @Pizara.  The roadblock for me now is actually on the final step of building [the binding](https://github.com/PopcornTV/node-images/wiki/How-to-build-a-binding).
```In file included from ../gyp/third-party/libjpeg-turbo/cdjpeg.h:16:0,
                 from ../gyp/third-party/libjpeg-turbo/bmp.c:33:
../gyp/third-party/libjpeg-turbo/jinclude.h:22:65: fatal error: jconfig.h: No such file or directory
compilation terminated.
gyp/gyp/libjpeg-turbo.target.mk:161: recipe for target 'Release/obj.target/libjpeg-turbo/gyp/third-party/libjpeg-turbo/bmp.o' failed
make: *** [Release/obj.target/libjpeg-turbo/gyp/third-party/libjpeg-turbo/bmp.o] Error 1
make: Leaving directory '/home/pi/PopcornTV/node_modules/node-images/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:267:23)```

I've looked through the libjpeg-turbo/ dir and found that the file is not there. However, adding it manually just leads to another file that can't be found and another and so on...

Adding a binding.node file manually doesn't solve it either. I'd like to get the binding to compile correctly but am stuck.  I've tried installing various versions of node, npm, gyp, and nw-gyp to see if I can find a combination that works, but haven't been successful so far.  Glad to hear you got yours working though! I know I'm so close.

**Comment by Pizara** [comment]
@masonjames can i help you remotely with this problem?

**Comment by OstlerDev** [comment]
@pizara I will merge the binding into the repository soon, along with bindings for v4.0.0 of node

**Comment by masonjames** [comment]
@Pizara I'd love some help.  I'm going back through the steps again.  I updated the thirdparty.sh script to grab the updated 1.4.1 version of libpeg-turbo (and spotted a spelling error in the gyp dir!) but neither of those things seems to have helped much so far.  How can we get in touch? I can join an IRC channel, Slack, twitter... :) I appreciate it!

**Comment by Pizara** [comment]
@masonjames i'm on IRC now please leave me a personal message

**Comment by masonjames** [comment]
So with @Pizara's awesome help I reinstalled PopcornTV and the binding.node file he provided worked for me as well!

Also, @Pizara went WAY beyond by walking me through my issue - very cool guy and his help was very much appreciated :+1:
