### ISSUE TITLE
how do you shutdown popcorntv?

### ISSUE THREAD

**Issue by skirocket** [OstlerDev/PopcornTV#228]
Hi i have a macbook pro and I'm using plex along with popcorntv, how can i shutdown the server for popcorntv without having to reset my mac to start plex? or is it at all possible to get them both running

thanks in advance

**Comment by Mauricevb** [comment]
CTRL + C stops the proces :)

**Comment by skirocket** [comment]
Thanks, i have tried that but the plex server still says that UDP port 53 is in use.

**Comment by OstlerDev** [comment]
Sounds like you might have closed either Plex or PopcornTV by just closing the terminal window without doing CTRL + C first. The easiest way to fix this is going to be restarting your computer.
