### ISSUE TITLE
Other AppleTV apps broken when atv.js is not running

### ISSUE THREAD

**Issue by masonjames** [OstlerDev/PopcornTV#23]
So today I started up the appleTV and noticed that hulu, netflix, and hbo now did not work.  I started up popcorntv and everything began working.  

My original thought was that popcorntv would not have an impact on other appletv areas. Is this a bug or did I misunderstand how this works?  Happy to provide extra logging info if you let me know what's helpful.

Thanks!

**Comment by OstlerDev** [comment]
Sadly the way that it works is by hijacking the DNS. Without running PopcornTV or changing the DNS back to default the DNS requests just 404.

This is expected sadly and why I run it on a dedicated VPS.
