### ISSUE TITLE
Raspberry Pi Wiki Update

### ISSUE THREAD

**Issue by masonjames** [OstlerDev/PopcornTV#231]
Hiya,

I wasn't totally sure how to help with the wiki, so I cloned my own copy, made the changes and uploaded them here.  https://github.com/masonjames/mj-popcorntv-wiki

If you find the changes helpful, feel free to merge them into the original wiki here.  The only page I changed was instructions on running PopcornTV on a VPS (Raspberry Pi):
https://github.com/masonjames/mj-popcorntv-wiki/blob/master/Running-PopcornTV-on-a-VPS.md

Hope this helps!

**Comment by OstlerDev** [comment]
Just pulled the change in! Thanks for spending the time and writing the guide! If you would like me to add credits to the bottom (thanking you for writing it) just let me know! I have updated it. https://github.com/OstlerDev/PopcornTV/wiki/Running-PopcornTV-on-a-VPS

**Comment by masonjames** [comment]
Woot!  Sure. I'd love to have some minor props somewhere :) I've been digging into the pi over the past couple weeks and will try to contribute more whenever I can.

**Comment by OstlerDev** [comment]
Awesome :)
