### ISSUE TITLE
Isn't working on Apple TV 4

### ISSUE THREAD

**Issue by rjong** [OstlerDev/PopcornTV#233]
See the title ;(

iTunes won't start anymore when I use it.

**Comment by OstlerDev** [comment]
The Apple TV 4 is not yet supported, it looks like you have a developer kit. Unfortunately I was not able to get a dev kit so I have to buy it with the wave of general consumers. If you want to speed up development by helping me get a dev kit let me know and I will talk to you about pricing. (I would offer to buy yours)
