### ISSUE TITLE
PopcornTV on a dedicated server

### ISSUE THREAD

**Issue by poloh11** [OstlerDev/PopcornTV#236]
I am actually trying to setup PopcornTV on an ubuntu dedicated server and then to connect the DNS of my apple TV on it.
All seems to be correct (Others functionalities are OK trough the DNS)
But I always have the error message "Trailers are unavailable. Try it later". on the Trailers menu

Should I open specific ports ? Have you got an idee to get it work ?

My node version is : v0.12.7
Logs of Atv.js:
root@PopcornTV:/home/PopcornTV# node atv.js 
notice: Starting PopcornTV
DNS: DnsProxy binding on 179.62.**.***:53
Web: listening on 179.62.**.***:80
Web: SSL Web: listening on 179.62.**.***:443
notice: Starting Commit 5a4e1**
DNS: p49-buy.itunes-apple.com.akadns.net
DNS: api-global.netflix.com
DNS: apple.com
DNS: www.apple.com

When I click on Trailers nothing appear in logs 

Thanks a lot
Paul

**Comment by OstlerDev** [comment]
Make sure to have ports 53, 80, and 443 open (send and receive). If that works then make sure to add the profile to your aTV because that sounds like the issue.

Let me know how it goes! (Take a look at the Wiki as there is an article on how to do this, but for a raspberry pi)

**Comment by poloh11** [comment]
Ports 53, 80 and 443 are open both on the server and on my provider access
Certificate is also ok .. It work when I run it locally from my Mac

**Comment by poloh11** [comment]
Any idee ? :(

**Comment by poloh11** [comment]
It work by regenerating the certificate ! :dancer:
