### ISSUE TITLE
Error Code: EADDRINUSE. Can't bind to port 53

### ISSUE THREAD

**Issue by pbassut** [OstlerDev/PopcornTV#237]
I'm getting this error when starting the dns server. It says something is running on port 53 but I got nothing there. Did a ```lsof -i :53``` to check.
Tried restarting the computer and still nothing.

Looks like someone else has the [same problem](https://discuss.popcorntime.io/t/popcorntv-bringing-popcorn-time-to-your-apple-tv/38367/78) as myself. But that didn't work out the way it did for him.

Any ideias?

I'm using Yosemite.

**Comment by JHFreeman** [comment]
try “sudo killall node"

**Comment by pbassut** [comment]
It's not node-related. It looks like something in the system.

**Comment by OstlerDev** [comment]
It could be an issue if you are running VMWare, I know that can cause issues.

**Comment by pbassut** [comment]
Oh man, that was bonjour with mDNSResponder. Bonjour sets up a dns and it only shows up if you do a ```lsof``` with sudo.

You might wanna add that to the docs.

**Comment by OstlerDev** [comment]
Will be sure to add it to the Docs when we make them :+1:

**Comment by pbassut** [comment]
Just in case someone else have the same problem. Unload mDNSResponder with the following command ```sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist```. Bonjour won't work properly though.

**Comment by pbassut** [comment]
@OstlerDev well, there's a [wiki page](https://github.com/OstlerDev/PopcornTV/wiki/How-to-install-(Mac)), isn't there? 
That looks like it's gonna get people into trouble while setting up. 
Just suggesting something to avoid headaches while helping people. (y)

**Comment by OstlerDev** [comment]
I was more meaning the FAQ (that still needs to be written). I have been working on the native application lately and have been slacking off on the FAQ lately.
