### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by randyellis** [OstlerDev/PopcornTV#24]
Got this when trying to run 'node atv.js' after the certs were made and moved to the cert folder.

C:\Users\Randy\Desktop\PopcornTV>node atv.js
Starting PopcornTV
DnsProxy binding on 10.0.0.16:53
There is an error starting Popcorn TV, please post this on the Github page
{ [Error: Cannot find module 'popcorn-streamer'] code: 'MODULE_NOT_FOUND' }

**Comment by OstlerDev** [comment]
Try running this again, it seems it did not download all the packages for some reason.

```
npm install
```

If that does not work the first time repeat the process a couple times. Report back your findings.

**Comment by randyellis** [comment]
This is what I got:C:\PopcornTV>npm install
npm WARN package.json PopcornTV@0.1.3 No repository field.
npm WARN package.json PopcornTV@0.1.3 No license field.
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:72:28)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:75:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:83:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:95:15)
npm WARN addRemoteGit  git+https://github.com/xeoncore/torrent-stream.git resett
ing remote C:\Users\Randy\AppData\Roaming\npm-cache\_git-remotes\https-github-co
m-xeoncore-torrent-stream-git-864d0b24 because of error: { [Error: not found: gi
t] code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:72:28)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:75:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:83:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:95:15)
npm WARN addRemoteGit  git+https://github.com/xeoncore/progress-stream.git#7070d
b resetting remote C:\Users\Randy\AppData\Roaming\npm-cache\_git-remotes\https-g
ithub-com-xeoncore-progress-stream-git-609443b1 because of error: { [Error: not
found: git] code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Randy\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror https://github.com/xeoncore/torrent-stream.git C:\Users\
Randy\AppData\Roaming\npm-cache\_git-remotes\https-github-com-xeoncore-torrent-s
tream-git-864d0b24: undefined
npm ERR! git clone --template=C:\Users\Randy\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror https://github.com/xeoncore/torrent-stream.git C:\Users\
Randy\AppData\Roaming\npm-cache\_git-remotes\https-github-com-xeoncore-torrent-s
tream-git-864d0b24: undefined
npm ERR! git clone --template=C:\Users\Randy\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror https://github.com/xeoncore/progress-stream.git C:\Users
\Randy\AppData\Roaming\npm-cache\_git-remotes\https-github-com-xeoncore-progress
-stream-git-609443b1: undefined
npm ERR! git clone --template=C:\Users\Randy\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror https://github.com/xeoncore/progress-stream.git C:\Users
\Randy\AppData\Roaming\npm-cache\_git-remotes\https-github-com-xeoncore-progress
-stream-git-609443b1: undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\PopcornTV\npm-debug.log

C:\PopcornTV>

Do I run this in Windows command prompt or Node js command prompt?

**Comment by OstlerDev** [comment]
Looks like you ran it correctly but there was an issue where it needed git installed on the computer. Please install git and re-run that command like you did as above: https://git-scm.com/download/win

**Comment by Mehmeed** [comment]
i had the same exact issue, but a restart fixed it.

**Comment by OstlerDev** [comment]
This general issue can happen if the install process stops for some reason, usually rerunning will fix that, however in this persons case it seems that they need to install git in order to install some of the repositories (as can be seen in the log)
```
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
```

**Comment by OstlerDev** [comment]
@randyellis let me know if this fixed the issue for you so I can close this issue.

**Comment by randyellis** [comment]
I installed git and did 'npm install' then 'node atv.js'. This is what I got:
```
C:\Users\Randy\Desktop\PopcornTV>node atv.js
Starting PopcornTV
DnsProxy binding on 10.0.1.16:53
Web: listening on 10.0.1.16:80
There is an error starting Popcorn TV, please post this on the Github page
[Error: error:0906D06C:PEM routines:PEM_read_bio:no start line]

C:\Users\Randy\Desktop\PopcornTV>
```

**Comment by OstlerDev** [comment]
Please regenerate the certificates, it looks like they may have been made incorrectly

**Comment by randyellis** [comment]
Here's what I've gotten:
```
C:\Users\Randy\Desktop\PopcornTV>node atv.js
Starting PopcornTV
DnsProxy binding on 10.0.1.16:53
Web: listening on 10.0.1.16:80
SSL Web: listening on 10.0.1.16:443
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRNOTAVAIL
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

C:\Users\Randy\Desktop\PopcornTV>
```

**Comment by OstlerDev** [comment]
What router are you using? Can you try updating to the latest development build? (you will need to run npm install again)

**Comment by randyellis** [comment]
I'm using an ARRIS TG862. Xfinity Comcast.

**Comment by OstlerDev** [comment]
Can you confirm that 10.0.1.16 is your Local IP address? It seems that it might not be currently.

**Comment by randyellis** [comment]
IP is correct. I've got PopcornTV working now. Now I'm adding the profile and it's taking quite awhile to add.

**Comment by OstlerDev** [comment]
Glad that everything turned out good for you! Did you end up using the latest dev version?

**Comment by randyellis** [comment]
Yes, I did used the latest version.
