### ISSUE TITLE
OS X El Capitan, Stuck on "Accessing trailers" with several can't load addon

### ISSUE THREAD

**Issue by idanew** [OstlerDev/PopcornTV#243]
OS X: El capitan
had same errors before , recently had to change the port to 10.0.0.143, due to
getting several error on terminal:

error: uncaughtException: Can't load the addon. Issue to: https://github.com/PopcornTV/node-images/issues 

Error: Can\'t load the addon. Issue to: https://github.com/PopcornTV/node-images/issues

Files: https://gist.github.com/idanew/f088e0fd448bae9e7314

**Comment by OstlerDev** [comment]
I just updated it so reform load and try again. This is most likely an issue with using Node 4.0.0.

**Comment by idanew** [comment]
I am not expert with terminal should I perform update and later run?!
Please specify the commands
Tnx

**Comment by OstlerDev** [comment]
Please downgrade from Node v4.x.x to a Node version of 0.12.x.

**Comment by idanew** [comment]
Hi 
i will do that, i might have missed it on your instruction but if not suggest to update the instructions on https://github.com/OstlerDev/PopcornTV/wiki/How-to-install-(Mac)#section-1-preparing-the-application
