### ISSUE TITLE
cannot read property 'data'

### ISSUE THREAD

**Issue by nveurvkl1** [OstlerDev/PopcornTV#248]
HI, i am using the 0.12.7 node.js and the latest popcornTv version.
at the first time, it worked well but since the second time this is the error im getting:

Web: /Parade.xml
error: uncaughtException: Cannot read property 'data' of undefined
{ date: 'Wed Oct 21 2015 00:44:13 GMT+0300 (Jerusalem Daylight Time)',
  process:
   { pid: 9412,
     uid: null,
     gid: null,
     cwd: 'C:\\Users\\Rinat\\Desktop\\PopcornTV-0.2.3',
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     version: 'v0.12.7',
     argv: [ 'node', 'C:\\Users\\Rinat\\Desktop\\PopcornTV-0.2.3\\atv.js' ],
     memoryUsage: { rss: 54468608, heapTotal: 56618752, heapUsed: 29507000 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 16399.2574598 },
  trace:
   [ { column: 27,
       file: 'C:\\Users\\Rinat\\Desktop\\PopcornTV-0.2.3\\MoviesAPI.js',
       function: 'Request._callback',
       line: 14,
       method: '_callback',
       native: false },
     { column: 22,
       file: 'C:\\Users\\Rinat\\Desktop\\PopcornTV-0.2.3\\node_modules\\request\
\request.js',
       function: 'Request.self.callback',
       line: 368,
       method: 'self.callback',
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Request.emit',
       line: 110,
       method: 'emit',
       native: false },
     { column: 14,
       file: 'C:\\Users\\Rinat\\Desktop\\PopcornTV-0.2.3\\node_modules\\request\
\request.js',
       function: '',
       line: 1219,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'Request.emit',
       line: 129,
       method: 'emit',
       native: false },
     { column: 12,
       file: 'C:\\Users\\Rinat\\Desktop\\PopcornTV-0.2.3\\node_modules\\request\
\request.js',
       function: '',
       line: 1167,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'IncomingMessage.emit',
       line: 129,
       method: 'emit',
       native: false },
     { column: 16,
       file: '_stream_readable.js',
       function: null,
       line: 908,
       method: null,
       native: false },
     { column: 11,
       file: 'node.js',
       function: 'process._tickCallback',
       line: 355,
       method: '_tickCallback',
       native: false } ],
  stack:
   [ 'TypeError: Cannot read property \'data\' of undefined',
     '    at Request._callback (C:\\Users\\Rinat\\Desktop\\PopcornTV-0.2.3\\Movi
esAPI.js:14:27)',
     '    at Request.self.callback (C:\\Users\\Rinat\\Desktop\\PopcornTV-0.2.3\\
node_modules\\request\\request.js:368:22)',
     '    at Request.emit (events.js:110:17)',
     '    at Request.<anonymous> (C:\\Users\\Rinat\\Desktop\\PopcornTV-0.2.3\\no
de_modules\\request\\request.js:1219:14)',
     '    at Request.emit (events.js:129:20)',
     '    at IncomingMessage.<anonymous> (C:\\Users\\Rinat\\Desktop\\PopcornTV-0
.2.3\\node_modules\\request\\request.js:1167:12)',
     '    at IncomingMessage.emit (events.js:129:20)',
     '    at _stream_readable.js:908:16',
     '    at process._tickCallback (node.js:355:11)' ] }
error: TypeError: Cannot read property 'data' of undefined
    at Request._callback (C:\Users\Rinat\Desktop\PopcornTV-0.2.3\MoviesAPI.js:14
:27)
    at Request.self.callback (C:\Users\Rinat\Desktop\PopcornTV-0.2.3\node_module
s\request\request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\Rinat\Desktop\PopcornTV-0.2.3\node_modules\
request\request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\Rinat\Desktop\PopcornTV-0.2.3\node_
modules\request\request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by reejosamuel** [comment]
facing the same issue

```
stack: 
   [ 'TypeError: Cannot read property \'data\' of undefined',
     '    at Request._callback (/Users/username/Downloads/PopcornTV/MoviesAPI.js:14:27)',
     '    at Request.self.callback (/Users/username/Downloads/PopcornTV/node_modules/request/request.js:368:22)',
     '    at Request.emit (events.js:110:17)',
     '    at Request.<anonymous> (/Users/username/Downloads/PopcornTV/node_modules/request/request.js:1219:14)',
     '    at Request.emit (events.js:129:20)',
     '    at IncomingMessage.<anonymous> (/Users/username/Downloads/PopcornTV/node_modules/request/request.js:1167:12)',
     '    at IncomingMessage.emit (events.js:129:20)',
     '    at _stream_readable.js:908:16',
     '    at process._tickCallback (node.js:355:11)' ] }
```

TV shows are facing another issue also
`warning: Error connecting to eztvapi.re and grabbing json: http://eztvapi.re/shows/1`

**Comment by emielvangoor** [comment]
I have te same problem...

**Comment by OstlerDev** [comment]
yts.to is currently down. The TV Api may also be down.
