### ISSUE TITLE
Cannot get PopcornTV to work anymore

### ISSUE THREAD

**Issue by hawks79** [OstlerDev/PopcornTV#250]
Up until recent everything was working fine. Now I get TypeError: Cannot read property 'data' of undefined

error: uncaughtException: Cannot read property 'data' of undefined
{ date: 'Mon Oct 26 2015 19:03:32 GMT-0600 (Mountain Daylight Time)',
  process:
   { pid: 3160,
     uid: null,
     gid: null,
     cwd: 'C:\\Users\\admin\\Desktop\\ptv',
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     version: 'v4.2.1',
     argv:a
      [ 'C:\\Program Files\\nodejs\\node.exe',
        'C:\\Users\\admin\\Desktop\\ptv\\atv.js' ],
     memoryUsage: { rss: 45555712, heapTotal: 25800192, heapUsed: 22320712 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 707.4208984 },
  trace:
   [ { column: 27,
       file: 'C:\\Users\\admin\\Desktop\\ptv\\MoviesAPI.js',
       function: 'Request._callback',
       line: 14,
       method: '_callback',
       native: false },
     { column: 22,
       file: 'C:\\Users\\admin\\Desktop\\ptv\\node_modules\\request\\request.js'
,
       function: 'Request.self.callback',
       line: 368,
       method: 'self.callback',
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitTwo',
       line: 87,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Request.emit',
       line: 172,
       method: 'emit',
       native: false },
     { column: 14,
       file: 'C:\\Users\\admin\\Desktop\\ptv\\node_modules\\request\\request.js'
,
       function: '',
       line: 1219,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'emitOne',
       line: 82,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Request.emit',
       line: 169,
       method: 'emit',
       native: false },
     { column: 12,
       file: 'C:\\Users\\admin\\Desktop\\ptv\\node_modules\\request\\request.js'
,
       function: '',
       line: 1167,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'emitNone',
       line: 72,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'IncomingMessage.emit',
       line: 166,
       method: 'emit',
       native: false } ],
  stack:
   [ 'TypeError: Cannot read property \'data\' of undefined',
     '    at Request._callback (C:\\Users\\admin\\Desktop\\ptv\\MoviesAPI.js:14:
27)',
     '    at Request.self.callback (C:\\Users\\admin\\Desktop\\ptv\\node_modules
\\request\\request.js:368:22)',
     '    at emitTwo (events.js:87:13)',
     '    at Request.emit (events.js:172:7)',
     '    at Request.<anonymous> (C:\\Users\\admin\\Desktop\\ptv\\node_modules\\
request\\request.js:1219:14)',
     '    at emitOne (events.js:82:20)',
     '    at Request.emit (events.js:169:7)',
     '    at IncomingMessage.<anonymous> (C:\\Users\\admin\\Desktop\\ptv\\node_m
odules\\request\\request.js:1167:12)',
     '    at emitNone (events.js:72:20)',
     '    at IncomingMessage.emit (events.js:166:7)' ] }

**Comment by OstlerDev** [comment]
The place we pull our Movies from as well as the place we pull our TV shows from are offline. This is not a quick fix and will take some time.
