### ISSUE TITLE
popcorn tv

### ISSUE THREAD

**Issue by tiamat1974** [OstlerDev/PopcornTV#251]
hi everybody,

trying to stream movies via popcorn tv to my apple tv.
i have followed all instructions, downloaded and installed node.js. however when i start and go to trailers on my tv nothing is shown.
in my cmd (windows vista) the error i get is uncaughtexception cannot read property "movies" of undefined.

i would appreciate ur help

**Comment by OstlerDev** [comment]
If you take a look at the project readme it states that the project is currently not working. Please read that for more information.
