### ISSUE TITLE
New links

### ISSUE THREAD

**Issue by hugge1818** [OstlerDev/PopcornTV#257]
https://eztv.ag/ and https://yify-movie.com/ ?

**Comment by YIFYtorrents** [comment]
yify.is, a very good yify clone. Unfortunately, eztv.ag is SCAM and owned by the same guy behind yts.ag, who's hijacked yify brand and calls themselfs 'official'.

**Comment by OstlerDev** [comment]
Seeing as you may be the person that created yify.is @YIFYtorrents I would not recommend users follow your advice. Users should research both websites if they would like to decide what to use personally. I have however discontinued the production of this application for worry of legal issues.

**Comment by hugge1818** [comment]
Can u show me how to change it and maybe just be so nice that u can update it to a clone maybe but thanks for replaying and great support keep it up man
