### ISSUE TITLE
Changed the link to yify.is and got this. Is it a away to make this link work? sorry for being so annoying

### ISSUE THREAD

**Issue by hugge1818** [OstlerDev/PopcornTV#258]
![skarmklipp2](https://cloud.githubusercontent.com/assets/16634417/12356278/0e9da7a8-bba2-11e5-9ccc-bc892dc38e4d.PNG)

**Comment by hugge1818** [comment]
It's*

**Comment by YIFYtorrents** [comment]
changto http://yify.is/index.php instead of http://yify.is

**Comment by hugge1818** [comment]
@YIFYtorrents didn't work sry but thank for the advice

**Comment by YIFYtorrents** [comment]
Where is the yts.js file located? You need to change some variables. I have no AppleTV, that's why I cannot test if it works.

**Comment by hugge1818** [comment]
@OstlerDev

**Comment by hugge1818** [comment]
@YIFYtorrents It booted up fine at the cmd. But at the apple tv it was only loading and didn't start. [stock at the booting] You mabye have to do a movie_details.json file like this https://yts.to/api/v2/movie_details.json and a movie_suggestions.json file like this https://yts.to/api/v2/movie_suggestions.json im not sure. We should ask @OstlerDev on this.
Thanks so much u are best man!!!!!!!
Keep up the work!!!!!!!
I tryied later to change only the first link https://yts.to/api/v2/list_movies.json?sort_by=  to see if anything changed but i got the same boot up at the computer and the apple tv.
But thats not so importent but i just wanted to share that information with u.
Thank u really much again, awesome support, keep it up!!!
![skarmklipp66](https://cloud.githubusercontent.com/assets/16634417/12429989/65ffe184-beed-11e5-9390-24d46c312fbc.PNG)

**Comment by hugge1818** [comment]
@YIFYtorrents  YIFY!!!!!!!! ALMOST WORKED GOT THIS ON THE APPLE TV. 
ITS A VIDEO INSIDE THE ZIP

[Ny(tt) WinRAR ZIP archive (2).zip](https://github.com/OstlerDev/PopcornTV/files/97652/Ny.tt.WinRAR.ZIP.archive.2.zip)

HERE IS THE MOVIESAPI.JS

[LELELE.zip](https://github.com/OstlerDev/PopcornTV/files/97654/LELELE.zip)




AND THIS ON THE PC
![skarmklipp7](https://cloud.githubusercontent.com/assets/16634417/12454172/a87986ce-bf96-11e5-8adf-0d5cd69a7bd5.PNG)
U GUYS OR U ARE FUCKING AMAZING LOVE U!!!!!!!!!!!!!!!!!!!!

**Comment by hugge1818** [comment]
AND THIS KNOW
![skarmklipp8](https://cloud.githubusercontent.com/assets/16634417/12454600/794486fe-bf98-11e5-922e-4c0c01311b17.PNG)

**Comment by hugge1818** [comment]
ITS THANK TO FOR MAKING A movie_suggestions.json FILE ON THE INTERNET THANKS

**Comment by YIFYtorrents** [comment]
http://yify.is/api/v2/list_movies.json works without index.php

Please check it again.

**Comment by soavarice** [comment]
The problem is that @YIFYtorrents movie_details.json doesnt work. Check:

http://yify.is/index.php/api/v2/movie_details.json?with_images=true&with_cast=true&movie_id=33

{"status":"error","status_message":"movie_id does not exist","meta":{"server_time":"1432814403","server_timezone":"Pacific\/Auckland","api_version":"2","execution_time":"37.13 ms"}}

**Comment by YIFYtorrents** [comment]
>The problem is that @YIFYtorrents movie_details.json doesnt work. Check:

>http://yify.is/index.php/api/v2/movie_details.json?with_images=true&with_cast=true&movie_id=33

>{"status":"error","status_message":"movie_id does not exist","meta":{"server_time":"1432814403","server_timezone":"Pacific\/Auckland","api_version":"2","execution_time":"37.13 ms"}}

You cannot choose a random id and they say the API is not working. It works like a charm. check here: http://yify.is/index.php/api/v2/movie_details.json?with_images=true&with_cast=true&movie_id=115655
