### ISSUE TITLE
Movies and TV shows show Static Qualities

### ISSUE THREAD

**Issue by OstlerDev** [OstlerDev/PopcornTV#26]
Currently the Movie and TV PrePlay screens show a static value for formats available, while just a small blemish currently, implementing this will also get us closer to selecting a quality.

**Comment by pitercio** [comment]
Don't know if it's related to this but, when showing the quality selection window, you can't choose any option by pushing the central button or the play button on the remote, you can just go back by pushing the menu button.

**Comment by OstlerDev** [comment]
As of right now that is just a static page, it will be implemented soon (hopefully the next week) as to where we can select the quality. As for right now it just takes the first torrent provided.

Hope that clarifies it a bit for you.

**Comment by pitercio** [comment]
Ahm, that makes sense, because the selection page also showed more options than the badges on the movie pre-play screen :)

**Comment by OstlerDev** [comment]
Yeah, both the quality badges and the quality selection page are static. I did however fix the bug that was preventing most TV shows from streaming, so if you were looking for that you are in luck!
