### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by randyellis** [OstlerDev/PopcornTV#27]
I'm also installing this on my mac and I made it to this point and got this error:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at Object.startWebServer (/Users/presentationgamemode/Desktop/PopcornTV/webserver.js:200:9)
    at Object.<anonymous> (/Users/presentationgamemode/Desktop/PopcornTV/atv.js:21:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
Randys-MacBook-Air:popcorntv presentationgamemode$ 
```

Does this have to do with OpenSSL? Or something else?

**Comment by OstlerDev** [comment]
That means that the port is currently in use, do you have a web server, Plexconnect, or anything running that would be taking port 53, 80, or 443?

**Comment by randyellis** [comment]
Not to my knowledge. Should I check the router settings?

**Comment by OstlerDev** [comment]
It would be something on the computer, restarting your computer might fix the error.

**Comment by randyellis** [comment]
I scanned the ports between 50 and 450 and found this:

```
Port Scan has started…

Port Scanning host: 10.0.0.4

	 Open TCP Port: 	80     		http
	 Open TCP Port: 	88     		kerberos
Port Scan has completed…
```

**Comment by OstlerDev** [comment]
It seems like you are running a web server as well, can you try to figure out what application is bound to it?

**Comment by randyellis** [comment]
Yeah this is weird, this is a bare-bones profile on my MacBook. I only use it for presentations/games/movies. No webserver/startup apps when I login.

**Comment by OstlerDev** [comment]
Try shutting down the web server using this command: http://www.cyberciti.biz/faq/howto-macosx-starting-stopping-apache-web-server/

It could be a remote app or something similar, do you access that computer via a phone or something during presentations? That could be it.

**Comment by randyellis** [comment]
I'll try this and update you. Thanks.

**Comment by randyellis** [comment]
That cleared it up. Everything works now. Would I have to do this every time I want to run PTV?

Also, can I use my native VPN to stream anonymously?

**Comment by OstlerDev** [comment]
It should be fine from now on, but yes, if you run a VPN on your Mac it will be anonymous
