### ISSUE TITLE
Some tv content not loading up. 

### ISSUE THREAD

**Issue by Moeith** [OstlerDev/PopcornTV#28]
This was homeland Season 1. Not sure if it was content specific, I had issues with other tv shows as well. 

Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
Web: /Movies/MoviePlay.xml
DNS: api-global.netflix.com
Web: /Movies/TVPrePlay.xml
warning: Error connecting to trakt.tv and grabbing json: https://api-v2launch.trakt.tv/shows/undefined/seasons/undefined?extended=full,images

**Comment by OstlerDev** [comment]
No TV shows stream currently, this is a known bug and has multiple reasons as outlined in issue #1 and #3

**Comment by Moeith** [comment]
My bad, thanks

**Comment by OstlerDev** [comment]
No problem! It is a common mistake and I am actively working on getting TV shows to work, it just takes quite a few more bug fixes on my part. I am planning it being fully working for the 0.1.6 release. I am currently working on 0.1.5 but after that is fixed and released I will be actively working on 0.1.6. 

You can view the current progress on these releases here: https://github.com/OstlerDev/PopcornTV/milestones
