### ISSUE TITLE
sudo node atv.js Debug - Log

### ISSUE THREAD

**Issue by yamilfarach** [OstlerDev/PopcornTV#32]
This is what I got after starting it in debug mode
I can start the program now in Trailers and the internet issue is gone but the movies or shows wont start

notice: Started logger in Debug mode!
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.0.13:53
Web: listening on 192.168.0.13:80
Web: SSL Web: listening on 192.168.0.13:443
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by OstlerDev** [comment]
That means that the address is in use. Make sure you are not running a web server or anything using port 53. 80, or 443.
