### ISSUE TITLE
Trying to install Master branch, getting this error? Am i missing anything?

### ISSUE THREAD

**Issue by Mehmeed** [OstlerDev/PopcornTV#34]
Here's link to npm-debug.log 
http://expirebox.com/download/583449053d8520b64805e84ec04b19ae.html

>Microsoft Windows [Version 6.3.9600]
>(c) 2013 Microsoft Corporation. All rights reserved.

>C:\Users\Mehmeed>cd desktop

>C:\Users\Mehmeed\Desktop>cd popcorntv-master

>C:\Users\Mehmeed\Desktop\PopcornTV-master>imp install
'imp' is not recognized as an internal or external command,
>operable program or batch file.

>C:\Users\Mehmeed\Desktop\PopcornTV-master>npm install
npm WARN package.json PopcornTV@0.1.3 No repository field.
npm WARN package.json PopcornTV@0.1.3 No license field.
\

> images@2.1.6 install C:\Users\Mehmeed\Desktop\PopcornTV-master\node_modules\im
ages
> echo "Hello, World."

>"Hello, World."
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4"
,"npm":"2.10.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4",
"npm":"2.10.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4",
"npm":"2.10.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.1
2.4","npm":"2.10.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4",
"npm":"2.10.1"})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

>npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

>npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
http@0.0.0 node_modules\http

>fs@0.0.2 node_modules\fs

>range-parser@1.0.2 node_modules\range-parser

>ip@0.3.3 node_modules\ip

>xml@1.0.0 node_modules\xml

>mime@1.3.4 node_modules\mime

>xml-writer@1.6.0 node_modules\xml-writer

>underscore@1.8.3 node_modules\underscore

>pem@1.7.2 node_modules\pem
└── which@1.0.9

>images@2.1.6 node_modules\images

>util@0.10.3 node_modules\util
└── inherits@2.0.1

>pump@1.0.0 node_modules\pump
├── end-of-stream@1.1.0
└── once@1.3.2 (wrappy@1.0.1)

>url@0.10.3 node_modules\url
├── punycode@1.3.2
└── querystring@0.2.0

>winston@1.0.0 node_modules\winston
├── cycle@1.0.3
├── stack-trace@0.0.9
├── isstream@0.1.2
├── eyes@0.1.8
├── pkginfo@0.3.0
├── async@0.9.2
└── colors@1.0.3

>request@2.55.0 node_modules\request
├── caseless@0.9.0
├── aws-sign2@0.5.0
├── stringstream@0.0.4
├── tunnel-agent@0.4.0
├── forever-agent@0.6.1
├── oauth-sign@0.6.0
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── qs@2.4.2
├── node-uuid@1.4.3
├── form-data@0.2.0 (async@0.9.2)
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── mime-types@2.0.14 (mime-db@1.12.0)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@0.9.4 (readable-stream@1.0.33)
├── tough-cookie@2.0.0
├── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.7.2, hoek@2.14.0)
└── har-validator@1.7.1 (commander@2.8.1, chalk@1.0.0, is-my-json-valid@2.12.0,
bluebird@2.9.27)

>popcorn-streamer@0.1.0 node_modules\popcorn-streamer
├── URIjs@1.15.1
├── progress-stream@0.5.0 (single-line-log@0.3.1, speedometer@0.1.4, through2@0.
2.3)
├── streamify@0.2.4 (readable-stream@1.1.13, hashish@0.0.4)
├── read-torrent@1.3.0 (xtend@4.0.0, magnet-uri@2.0.1, request@2.16.6, parse-tor
rent@4.1.0)
├── torrent-stream@0.16.2 (bitfield@0.1.0, thunky@0.1.0, hat@0.0.3, random-acces
s-file@0.3.1, mkdirp@0.3.5, magnet-uri@2.0.1, ip-set@1.0.0, bncode@0.5.3, compac
t2string@1.4.0, end-of-stream@0.1.5, peer-wire-swarm@0.9.2, bittorrent-dht@2.7.2
, rimraf@2.4.0, parse-torrent@1.7.0, bittorrent-tracker@2.12.1)
└── ytdl-core@0.2.4 (underscore@1.6.0, request@2.37.0, jstream@0.2.7)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

>npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

>npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mehmeed\Desktop\PopcornTV-master\npm-debug.log

>C:\Users\Mehmeed\Desktop\PopcornTV-master>

**Comment by Mehmeed** [comment]
Actually, i was trying to make a tutorial video for this latest branch. But then this happened. If i can this working then i'll complete that tutorial and send it to you.

**Comment by OstlerDev** [comment]
It looks like you are having an issue here:
```
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
```

For some reason your network is blocking NPM for that package. Try running it again and see if it works.

And thats awesome about the tutorial! I actually just added some awesome new features today (Favorites, to add one hover over a movie or TV show poster and hold the select button) as well as bug fixes. Once you get it made, just post it as an issue or something so that I can add it to the wiki.

**Comment by Mehmeed** [comment]
ohh.. ran it again.. and same error! is it because i have 0.1.4 installed? should i delete that folder? and will do sir! and thanks for the info, i didnt know about that favorites feature

**Comment by OstlerDev** [comment]
Try deleting the old folder and trying from scratch. That could possibly be the issue?

And yes, I have added quite a few features and a log of code changes since the 0.1.4. The main bug fix being that Most TV Shows now work and stream.

All the code from June 3rd and up is brand new and packed with features, just take a look at some of the messages to get an idea on them: https://github.com/OstlerDev/PopcornTV/commits/master?page=1

**Comment by Mehmeed** [comment]
so i deleted the folder and tried again.. and it worked but just for one time.. and now whenever i go apple tv trailers it says trailers is unavailable.. my pc is on. and when first time it worked, it didnt play movie. cuz i couldnt click on it

**Comment by Mehmeed** [comment]
never mind its fixed.. so yeah ima go ahead and make that video

**Comment by OstlerDev** [comment]
Try to check and see if popcorn TV is running. Can you copy and paste the log onto here from "PopcornTV.log"?

If you can start it back up and reproduce the issue, please start it in debug mode and post that log using:

```
node atv.js Debug
```

**Comment by Mehmeed** [comment]
i figured out the problem.. so when you hold center button on any movie poster, it just turns off your popcorntv. so i have to go and do node atv.js again.

**Comment by Mehmeed** [comment]
and it does same when you go to favorites section

**Comment by OstlerDev** [comment]
Can you start up the program in debug mode then post the full log on Pastebin or something similar so I can take a look at the error?

**Comment by Mehmeed** [comment]
This is what i get when i hold button for favorite or go to favorites section
http://pastebin.com/G2yBmwpX

**Comment by OstlerDev** [comment]
Ah, can you try something for me? Try going to the settings page them attempting again.

**Comment by Mehmeed** [comment]
Well i tried running on node.js command and everything worked perfect. 
So i went to settings first, then turned subtitles on, then changed default quality to 1080p, then went back to movies, played a movie, went back, added that movie to favorites, then tried going to favorites section and it didnt load. and after that i get same screen "Accessing traielrs" on every page. Here's the log:
http://pastebin.com/EwiqgpFc

**Comment by OstlerDev** [comment]
Can you start up PopcornTV in debut mode by using the following?

```
node atv.js Debug
```

Then post the logs of that.

**Comment by Mehmeed** [comment]
As you requested :) This is when i try opening trailers app
http://pastebin.com/V7mSacEg

**Comment by OstlerDev** [comment]
That is only a partial bit of the logs, can you open the "PopcornTV.log" file and post it? Or maybe upload that file somewhere?

**Comment by Mehmeed** [comment]
Oh ok i will as soon as i get home

**Comment by OstlerDev** [comment]
@Mehmeed Is the issue still happening for you?

**Comment by OstlerDev** [comment]
This has been fixed a few versions ago.
