### ISSUE TITLE
Move from EZTVapi to Get Strike.

### ISSUE THREAD

**Issue by OstlerDev** [OstlerDev/PopcornTV#36]
It seems that Get Strike might have a better API for getting and presenting higher quality torrents.

Link: http://blog.getstrike.net/post/121229490218/new-tv-endpoints-beta

**Comment by Mehmeed** [comment]
wow they're so well organized. Love the idea. I say go for it. :)

**Comment by OstlerDev** [comment]
The only reason currently I would not go for it, is that I cannot pass an IMDB ID to them and get back the TV show. I have to send the title. Which is still possibile, but requires extra work. For that fact and the fact that I cannot get popular TV shows (other then from trakt.tv) I may not be going with it. I will try to do a test of it over the weekend to get a feel of it.

**Comment by Mehmeed** [comment]
Oh okay makes sense. but i just read article about eztv, that its been taken down or something.

**Comment by OstlerDev** [comment]
There was a hostile takeover of the site, as such I do not use their Api, but rather one maintained by Popcorn Time

**Comment by Codeusa** [comment]
I'll add a query option for imdb ids

**Comment by OstlerDev** [comment]
@Codeusa Oh wow! That would be awesome if you could add that! Something similar to this would be the best way (for me at least):
```
https://getstrike.net/api/v2/torrents/tv/?imdb=tt0944947
```
Great to see you here on the project! As soon as you get that implemented I will switch over the API to use GetStrike.

Another more random question, but I am not sure if you are tracking the most popular TV shows or most updated? If not it is not a huge issue, just something I was curious about.

**Comment by OstlerDev** [comment]
As I was implementing Getstrike, I am having troubles. Some shows just do not have all of the TV shows that we need. For example, Breaking bad, which the eztvapi.re has most of the episodes for, Strike only has 16 of the episodes.

EZTV:
```
http://eztvapi.re/show/tt0903747
```
Get Strike:
```
https://getstrike.net/api/v2/torrents/tv/?imdb=tt0903747
```

This could be because this Getstrike API for TV shows was just implemented or for some other reasons. I am going put this switch on hold for now while I debate the pros and cons. For anyone that wishes to have a list of the pro's and cons:

Pros:
- Faster, Cleaner, less need to pull from Trakt
- Multiple torrents per episode and quality (allowing us to select the .mp4 easier without only having a .avi for some)
- Get direct torrent file rather then issue with some magnet links.

Cons:
- Some TV shows are missing or have no episodes.
- Shows all episodes per season even if there are no torrents, something that the EZTVapi omits.

While I would love to switch over to GetStrike, I am not sure that the pro's and cons outweigh each other. I will put this on hold for now and check back with it later.

**Comment by Codeusa** [comment]
The missing tv will be fixed whenever i get a more solid regex down for
matching tv shows; if you have one you'd like to provide that can extract

Title, Season, Episode Number and Meta data like quality from any torrent
feel free.

**Comment by OstlerDev** [comment]
@Codeusa I will see what I can comeup with!

**Comment by Codeusa** [comment]
Basically currently take torrents and parse them using this method

$pattern       = "/(.*)\\.S?(\\d{1,2})E?(\\d{2})\\.(.*)/";
$torrentTitle = preg_replace('-', ' ', $dhtStream["torrent_title"]);
$torrentTitle = preg_replace('/\s+/', '.', $dhtStream["torrent_title"]);
 preg_match($pattern, $torrentTitle, $matches);

Basically hard coding it to try and make most torrents this format

MyTV.Show.S09E01.HDTV.XviD

Could obviously be done better so we're missing a lot

**Comment by OstlerDev** [comment]
Ok, I will see what I can do. I assume that you would have to re-run it over every TV show though?

**Comment by Codeusa** [comment]
Its all on demand, so if i can get a regex that can match all that information in various formats without needing to alter the actual torrent title it should be fine.

**Comment by OstlerDev** [comment]
What about something like this?
```
^(.+)\.S(\d+)E(\d+)\.(\w+)\.(\w+)$
```

**Comment by Codeusa** [comment]
That would match 

MyTV.Show.S09E01.HDTV.XviD

but not 

Game of Thrones S05E04 WEBRip XviD-FUM[ettv]

https://getstrike.net/torrents/?q=breaking%20bad


As you can see i have well over 1000 breaking bad torrents but you only get 16 because its failing to match a lot of them

**Comment by Codeusa** [comment]
For example 

Breaking.Bad.S01E07.FINAL.FRENCH.DVDRip.XviD-JMT

And 

Breaking Bad S01E07 FINAL FRENCH DVDRip XviD-JMT

both don't match

**Comment by OstlerDev** [comment]
That is what I was working on next, is there a way to run multiple regex tests or should I build them all into one.

**Comment by Codeusa** [comment]
I can run multiple, but a single universe would be preferred, i just converted my code to php for readable sake, Strike is mostly C++ so I'd like to keep the regex single

**Comment by OstlerDev** [comment]
@Codeusa Could this work possibily? By casting all spaces to periods you add a lot of torrents that might have been missed: https://gist.github.com/OstlerDev/afa32b9b2bfc8ab1e2d4

It might be a long shot and there are more episodes that need to be parsed in, but for the most part this would include lots of the missed episodes. Are there more formats that you would like me to look at?

**Comment by OstlerDev** [comment]
It seems like your regex already does what mine would do as well. However, if you let me know what else you would need it to do then I can provide that, I kinda just threw this together fast.

**Comment by Codeusa** [comment]
I think the easier work around would be to just get a complete archive of all the ettv torrents which is what i primarily look for, i do seem to be missing some. I will update you on this when its done

**Comment by OstlerDev** [comment]
@Codeusa I do think that the system you have currently is much better. It allows for returning of multiple torrents per quality, where as with just pulling from ETTV will just give you one torrent. Having multiple torrents for each quality allows for better torrents in the long run. While it may be a bit more work I think it is work it.

If there was a way to pull more than 50 results from a query (rather than loading the HTML page and parsing it) I would consider possibly writing my own library that does the same thing.

**Comment by OstlerDev** [comment]
It looks like Get Strike was implemented into the EZTVapi if the EZTVapi could not find videos. For now we will stick with the EZTVapi.
