### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by craiem** [OstlerDev/PopcornTV#39]
It would be awesome to work in raspberry pi! I tried to install it but throws errors when you start the download

**Comment by OstlerDev** [comment]
There is no reason that it should not work. I have thought about creating an install guide just for the Raspberry Pi, but have never gotten around to it.

Try searching the error on google to find out what you may be needing to do.

**Comment by craiem** [comment]
I think I must be missing something, It is the best use that could give my Raspberry Pi!

**Comment by OstlerDev** [comment]
Try reinstalling Rasbasian, then installing git and cloning the project. You will need to be sure to install all the dependencies, until I can write up a guide I suggest using google.

Please try and report what packages you needed on here.

**Comment by craiem** [comment]
OMG, i pulled the last git on lastest raspbian-wheezy and its Works! its really amazing, i dont need to get my computer on! I will waiting for the subs update! Thanks!!

pd: How can i use the other apps in apple tv ( like netflix)  without change the dns again?

**Comment by OstlerDev** [comment]
Just leave PopcornTV running in the background on your Raspberry Pi. If you are not running PopcornTV then you will need to change the DNS to use other Applications.

The Subtitles feature is still a while off and I am not sure when I will get time to work on it. I need to write another API as well as convert and inject the JSON subs.

**Comment by craiem** [comment]
Some movies crash when gets the picture:

/home/PopcornTV/node_modules/images/binding.js:55
                throw new Error('Can\'t load the addon. Issue to: ' + bugUrl +
                      ^
Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: Cannot find module './bindings/linux/arm/0.12.0/binding.node'

**Comment by OstlerDev** [comment]
That is an issue with a library not being installed, try asking on that github page.
