### ISSUE TITLE
Crash on Checksetting

### ISSUE THREAD

**Issue by legendaryv** [OstlerDev/PopcornTV#40]
I finally got the system up and running, but it keeps failing as soon as it tries to stream. Can you take a look at two snapshots when it started failing and let me know what I'm doing wrong? Both of these failures started when I tried to start a stream. 

Web: /thumbnails/MediaBadges/1080.png
Web: 404: /thumbnails/MediaBadges/1080.png
Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
Web: /Movies/MoviePlay.xml
Streamer: Ready to Stream, binding to http://10.0.0.57:9999
Web: /Movies/TVPrePlay.xml
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory './aTVSettings.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.checkSetting (/Users/jordan/Desktop/PopcornTV/settings.js:134:19)
    at null.<anonymous> (/Users/jordan/Desktop/PopcornTV/webserver.js:61:34)
    at emit (events.js:129:20)
    at null._onTimeout (/Users/jordan/Desktop/PopcornTV/streamer-server.js:100:18)
    at Timer.listOnTimeout (timers.js:110:15)
Jordans-Mac-mini:PopcornTV jordan$ sudo node atv.js
Password:
notice: Starting PopcornTV
DNS: DnsProxy binding on 10.0.0.57:53
Web: listening on 10.0.0.57:80
Web: SSL Web: listening on 10.0.0.57:443
DNS: trailers.apple.com change to 10.0.0.57
Web: /Movies/TVPrePlay.xml
DNS: trailers.apple.com change to 10.0.0.57
Web: /Parade.xml
Web: templates/MovieNav.xml
Web: /js/utils.js
Web: /js/navbarHandler.js
Web: /MoviesGrid.xml
Web: /js/utils.js
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory './aTVSettings.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.checkSetting (/Users/jordan/Desktop/PopcornTV/settings.js:134:19)
    at Server.<anonymous> (/Users/jordan/Desktop/PopcornTV/webserver.js:121:29)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)

**Comment by OstlerDev** [comment]
Ah, this is happening because it attempts to check the setting file before it is generated. I will add a catch for this and commit it a bit later tonight.

**Comment by OstlerDev** [comment]
@legendaryv this has now been fixed, can you please attempt to update to the latest version and try again?

**Comment by legendaryv** [comment]
Absolutely! I'll try it tonight. Thanks for fixing this!

**Comment by legendaryv** [comment]
I can now stream movies. TV shows are timing out in the appleTV app. No code errors. There also appears to be a lot of "loading trailers" when nothing appears to be happening (i.e., going into an episode to then hit play). 

Favorites also times out, but don't know if you want me to put this in another issue. 

All together, this is freaking sweet work guys.

**Comment by legendaryv** [comment]
I'm actually getting two types of errors on the appleTV. The first one is clearly the time out one where it says "trailers is not accessible right now". The other error is "An error occurred loading this content". 

The specific streams I was loading were;

Big Bang, Season 8, episode 24 (time out error)
How I met your mother, Season 9, episode 22 (An error ...)

Both play fine on the mac desktop version of Popcorn.

**Comment by OstlerDev** [comment]
The timeout error occurs because the Apple TV page times out of loading before 5mb has been downloaded.

The other error occurs because it is not an MP4 file. Both are known issues and will be resolved sometime in the future.
