### ISSUE TITLE
Error in PopcornTV Download on Apple TV

### ISSUE THREAD

**Issue by ADMNTK** [OstlerDev/PopcornTV#43]
HI

I saw a video of the work for you to download on Apple PopcornTV
I got an error after writing -node leadership atv.js what is the solution to this error.

Video 

https://www.youtube.com/watch?v=x_A58Ttvjd0

![default](https://cloud.githubusercontent.com/assets/12907809/8178579/fddb92b8-1417-11e5-956a-03f3ee5ce6d2.png)

**Comment by OstlerDev** [comment]
You need to create and install a certificate manually.

**Comment by ADMNTK** [comment]
What is the way to create the certificate please explain Thank you

**Comment by OstlerDev** [comment]
If you take a look at the wiki it links to the post needed, that post can be found here: https://github.com/OstlerDev/PopcornTV/issues/11#issuecomment-107713666

**Comment by ADMNTK** [comment]
Yes I reached for step No. 3 but do not know what to do after this step please explain.

**Comment by OstlerDev** [comment]
Please follow the guide here: https://github.com/OstlerDev/PopcornTV/wiki/How-to-Install-(Windows)

It was written up for a reason.

**Comment by ADMNTK** [comment]
I will try for the tenth time :(
Do you change your IP required me to work or not, I'm from Saudi Arabia .

**Comment by ADMNTK** [comment]
Is it practical True or False ?

What do I do after this step?

I am not a programmer .
![11111111](https://cloud.githubusercontent.com/assets/12907809/8196160/846bd30a-1491-11e5-91ad-cef1d7ba440a.png)

**Comment by ADMNTK** [comment]
These files existence of the certificate was transferred to the application folder was the work of the steps again and interest !! I wish to clarify more :(
![22222222222](https://cloud.githubusercontent.com/assets/12907809/8196298/180abd6e-1493-11e5-807c-aaba18c7c8aa.png)

**Comment by ADMNTK** [comment]
File does not appear config.json .
