### ISSUE TITLE
Error in PopcornTV Download on Apple TV .

### ISSUE THREAD

**Issue by ADMNTK** [OstlerDev/PopcornTV#45]
We have reached a certificate file with other files have been placed in the application folder

What do I do next ?

I need to explain with pictures or video to overcome this problem and run the APPLE TV without any problems ..

![11111111](https://cloud.githubusercontent.com/assets/12907809/8197145/f015e798-149c-11e5-9858-c41f844ad346.png)
![22222222222](https://cloud.githubusercontent.com/assets/12907809/8197152/f5f49934-149c-11e5-8fa2-48625fb0289f.png)

Please help thank you very much

**Comment by OstlerDev** [comment]
You need to move those files into "assets/certificates" like it says in the wiki.

**Comment by ADMNTK** [comment]
Where is the transport?

**Comment by OstlerDev** [comment]
The transport?

**Comment by ADMNTK** [comment]
Do you move the files to a folder
PopcornTV

**Comment by OstlerDev** [comment]
Move those files you made to "PopcornTV/assets/certificates/"

**Comment by ADMNTK** [comment]
Is transferring files to work properly, why after this step
![default](https://cloud.githubusercontent.com/assets/12907809/8201015/079fb028-14d5-11e5-92ee-d1745b3cc0a1.png)

**Comment by OstlerDev** [comment]
Please follow the next steps in the video and the wiki.

**Comment by OstlerDev** [comment]
Make sure that you rename "trailers.der" to "trailers.cer"

After you do that start up PopcornTV again using ``node atv.js``

**Comment by ADMNTK** [comment]
Yes you re- naming the file Do I recall to the original name or type this command and follow the next steps ?

File setter security certificate file in this folder ?

**Comment by ADMNTK** [comment]
Same as the previous error !!
Is it possible to explain the video attached to me ?
![243](https://cloud.githubusercontent.com/assets/12907809/8201447/e0509e56-14d9-11e5-8cd9-ef0c72b47266.png)

**Comment by OstlerDev** [comment]
You did not rename the file to "trailers.cer" like I stated. Once you rename the file from "trailers.der" to "trailers.cer" then it will work. As I stated in my previous post, rewatch the video and read the tutorial.

**Comment by ADMNTK** [comment]
Where was renamed file?

**Comment by OstlerDev** [comment]
The files you just moved. You just need to rename it to the new name. I cannot help you further if you are not going to read what I am directing you to do.

**Comment by ADMNTK** [comment]
What is the method of re- label ?

Excuse me, I do not understand English well

**Comment by OstlerDev** [comment]
You take the original file name and rename it to the new name. I am sorry if my instructions get lost in translation.

**Comment by ADMNTK** [comment]
Yesterday I spoke with you in Twitter, the solution has been operating well and lacks only translation of the completed project. Thank you very much for Matkdmh .
