### ISSUE TITLE
Installation: Stuck on Step 3.

### ISSUE THREAD

**Issue by mrjoaoms** [OstlerDev/PopcornTV#46]
Hi!

When I enter the command "$ sudo nom install" i get this message from terminal: "command not found". I'm unable to proceed with further steps. Could you please help me?

Kind Regards

mrjoaoms

**Comment by OstlerDev** [comment]
You mis-spelled npm. Please use ``sudo npm install`` not sudo nom install.

Is there somewhere in the documentation that it says to use nom?

**Comment by mrjoaoms** [comment]
Sorry my mistake! I always write "$ sudo npm install" = command not found :(
![terminal](https://cloud.githubusercontent.com/assets/12943143/8224831/eaee70c6-1584-11e5-899d-43cbf5257aef.jpg) What did I miss?

**Comment by OstlerDev** [comment]
Did you make sure to install Node? You are getting that error because you did not have node installed.

**Comment by mrjoaoms** [comment]
Thank you! Its done! Im already on step 6. However I get the error code: EADDRINUSE. "Cannot bind to Port 80"
![terminal2](https://cloud.githubusercontent.com/assets/12943143/8225420/410c87de-158c-11e5-95fa-cb9f001cbd99.jpg)

Thank you once again!

**Comment by OstlerDev** [comment]
As it says in the error, make sure that you are not running a web server or something similar on your machine. You need port 80 to be open for PopcornTV to run.

**Comment by mrjoaoms** [comment]
Is there a simple way to make sure port 80 is open in Mac OS?

**Comment by OstlerDev** [comment]
Use the following command to terminate the application/process that is taking port 80.

```
sudo lsof -i tcp:80
```

It will output a few lines, look for the one that says (LISTEN) at the end. In the second column there should be a number, take that number and type the following in.

```
sudo kill -9 <number from the PID column>
```

So I would type

```
sudo kill -9 16194
```

Let me know if that helps!

**Comment by mrjoaoms** [comment]
Thank you so much! I've completed the process. Where can I find the Popcorn TV on my Apple TV?

Best Regards!

**Comment by OstlerDev** [comment]
Please follow the rest of the instructions on the Wiki. It clearly explains how. After you install the certificate and change the DNS you will need to go into the "Trailers" application.

**Comment by mrjoaoms** [comment]
Sorry bud! On wiki tutorial for mac (https://github.com/OstlerDev/PopcornTV/wiki/How-to-install-(Mac)I've completed the section 2. The only further information on section 3 is
"You are now done with the installation! Just make sure PopcornTV is running whenever you wish to use it!

Are there other page with more instructions?

**Comment by OstlerDev** [comment]
If you have completed section two open the "Trailers" application that is on your Apple TV. I will update the Wiki to be clearer.

**Comment by mrjoaoms** [comment]
Yeah! Finally testing popcorn tv! Well done @OstlerDev!! Is there any possibility to get subtitles working?

**Comment by OstlerDev** [comment]
Right now subtitles are not implemented. They are on the roadmap for 0.1.6.

**Comment by mrjoaoms** [comment]
Thank you for your suppor! Truly great app! Is there a way to make a script in order to run the terminal commands with a simple click?
