### ISSUE TITLE
Trailers not available right now.

### ISSUE THREAD

**Issue by DreamWalker77** [OstlerDev/PopcornTV#48]

**Comment by fguespe** [comment]
Im having this problem. Trailers not available right now

**Comment by OstlerDev** [comment]
Do you get this when first entering the trailers application? If so that means that you did not install the certificate. Please go back and follow the tutorial fully.

**Comment by fguespe** [comment]
I doit 2 times now.

This is my config.json

{
    "ip": "192.168.1.104",
    "default_dns": "8.8.8.8"
}

And the log

MacBook-Air-de-fabrizioguespe:PopcornTV myname$ sudo node atv.js
notice: Creating SSL Certificates...
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.104:53
Web: listening on 192.168.1.104:80
Web: SSL Web: listening on 192.168.1.104:443
MacBook-Air-de-fabrizioguespe:PopcornTV myname$ sudo node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.104:53
Web: listening on 192.168.1.104:80
Web: SSL Web: listening on 192.168.1.104:443

There are trailers.pem and trailers.cer created in folder.


I add the profile this url: 192.168.1.104/trailers.cer

**Comment by OstlerDev** [comment]
Use http://trailers.apple.com/trailers.cer for the URL.

**Comment by OstlerDev** [comment]
Does the profile add correctly?

**Comment by fguespe** [comment]
I tried that but said error not found. So i read a thread where it said to try what i did last

**Comment by OstlerDev** [comment]
Looks like you did not change your DNS to the new IP.

**Comment by fguespe** [comment]
Do you mean in network config in apple tv? 10.0.1.2? I did that

**Comment by OstlerDev** [comment]
You do not change it to 10.0.1.2. You change it to your IP address, which in your case is ``192.168.1.104``

**Comment by fguespe** [comment]
You mean to add new profile 10.0.1.2/trailers.cer?

**Comment by OstlerDev** [comment]
If you take a look in step 3 inside the [install guide](https://github.com/OstlerDev/PopcornTV/wiki/How-to-install-(Mac)) it says to change the DNS on the Apple TV to your local IP address. It gives ``10.0.1.2`` as an Example. You need to change the DNS on your Apple TV to your Local IP address which is ``192.168.1.104``

**Comment by fguespe** [comment]
oh! sory!!! works!!! Thanks!! I thought it was related some how with one of your dns servers. Didnt get it as an example ip

**Comment by OstlerDev** [comment]
Glad that it works for you now! Enjoy.
