### ISSUE TITLE
Popcorn streamer not found

### ISSUE THREAD

**Issue by regioblogs** [OstlerDev/PopcornTV#5]
After creating the file "config.json" I get this message: { [Error: Cannot find module 'popcorn-streamer'] code: 'MODULE_NOT_FOUND' } any thoughts

**Comment by OstlerDev** [comment]
Try running "npm install" again and paste the output on here. It seems that for some reason it didn't get installed when you ran that command earlier.

What OS are you running?

**Comment by OstlerDev** [comment]
@regioblogs let me know if this solution worked for you so I can get this marked as closed :)

**Comment by regioblogs** [comment]
Thanks, It worked. But now i received this message when trying to open the Trailers app "An Error Occurred Loading This Content. Try Again Later"

**Comment by OstlerDev** [comment]
That error usually occurs if you did not install the Certificate correctly. Can you post the following information for me?

Apple TV Version (2 or 3):
Apple TV OS Version:
A picture of your "Add profile" page.

If the profile was added correctly you should see something like this in the logs of PopcornTV "WEB: certificates/trailers.cer". You should also see a button below the "Add Profile" button that says "trailers.apple.com". Do you see either of those? If not make sure popcorn time is running then make sure the DNS is changed and try adding the certificate again.

**Comment by regioblogs** [comment]
apple tv 2
6.2
I didn´t get an "add profile" page.
I saw my mistake. I didn´t add the profile correctly.  I did everything again, now is up and running.
Thanks for your help

**Comment by OstlerDev** [comment]
Glad to see it is working fine for you! If you have any more problems feel free to open up another issue.
