### ISSUE TITLE
Movies won't stream?

### ISSUE THREAD

**Issue by JakeRound** [OstlerDev/PopcornTV#52]
Every thing else seems to be working in the movies section. However when it comes to playing the movie it's self it outputs the following error. Trailers work but not movies. Thanks when i can get this all setup i'd be willing to donate :+1: 

![Console Log](http://i.imgur.com/kcGFK8P.png)

**Comment by OstlerDev** [comment]
Can you try the following?

1. Rerun the command ``sudo npm install``
2. Report the issue using the issue reporting guidelines found here: https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue

**Comment by JakeRound** [comment]
Fixed. Will take not for next time. Apologies

**Comment by OstlerDev** [comment]
Glad that it fixed it for you! As for the donation, I currently do not have any way for people to donate. If I open it up for donations in the future it will most likely only be for Bitcoin and such.

Let me know if you have any other issues!
