### ISSUE TITLE
Weird Crash on Playing TV Episode

### ISSUE THREAD

**Issue by masonjames** [OstlerDev/PopcornTV#53]
Updated to latest from Trunk (1 more commit === 100!!!) and got the following when trying to watch a tv show:
```
/Users/masonjames/Desktop/PopcornTV/XMLGenerator.js:1702
    var torrentURL = torrents[quality].url;
                                      ^
TypeError: Cannot read property 'url' of undefined
    at selectTorrentTV (/Users/masonjames/Desktop/PopcornTV/XMLGenerator.js:1702:39)
    at /Users/masonjames/Desktop/PopcornTV/XMLGenerator.js:1408:45
    at /Users/masonjames/Desktop/PopcornTV/TVApi.js:245:17
    at Request._callback (/Users/masonjames/Desktop/PopcornTV/TVApi.js:66:10)
    at Request.self.callback (/Users/masonjames/Desktop/PopcornTV/node_modules/request/request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/masonjames/Desktop/PopcornTV/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/masonjames/Desktop/PopcornTV/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
```
The entire app crashed.  The same things happens when I try that particular episode again - however other episodes work just fine.  I also got the message on the appleTV when trying to watch a show that used an mkv file - awesome improvement :)

**Comment by OstlerDev** [comment]
Do you think you could provide the following for me?

1. A full log of the issue (Here is how to produce it: https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue )
2. Your aTVSettings.json file.
3. The series, season, and episode number so I can test it myself.

It seems to be that the TV show does not have a set of torrents or something similar. Once you get me all of that stuff I will be able to further debug your issue!

I am amazed as to how the commits have piled up, I plan on releasing 0.1.5 soon and adding subtitles soon as well.

**Comment by masonjames** [comment]
Sure thing.

New PopcornTV Log file: https://gist.github.com/masonjames/041d862a9e74a96ea061
aTVSettings.json file: https://gist.github.com/masonjames/1a4762e41ed15250bae3

Big Bang Theory, Season 8, Episode 1. The app crashes and closes as soon as you try to play the episode on the appleTV.

Let me know if there's anything else I can do to help!

**Comment by OstlerDev** [comment]
Thanks for that info! I am pushing up a commit now to fix this issue for you!

**Comment by masonjames** [comment]
Works! Many thanks!

Note - for whatever reason, I didn't realize until now that running the popcorntime app isn't required for popcorntv to work correctly.

**Comment by OstlerDev** [comment]
Yeah, you do not need to run Popcorn Time at the same time as PopcornTV. Hope that did not cause anyone confusion! It is a completely standalone application.
