### ISSUE TITLE
Just a comment

### ISSUE THREAD

**Issue by freestylemaster** [OstlerDev/PopcornTV#54]
Myself and I am sure many others are enjoying your work. This is really something special so please consider accepting "donation". I am sure some people will appreciate this work.
Thanks really!

**Comment by OstlerDev** [comment]
Thanks for the positive comment! I may add an ability for people to donate via BTC, but I cannot accept Paypal for a few reasons.

Thanks for supporting the project!

**Comment by pitercio** [comment]
+1. Let us know how to donate :)
