### ISSUE TITLE
Error: Cannot find module 'xmlrpc'

### ISSUE THREAD

**Issue by brunojalves** [OstlerDev/PopcornTV#55]
Wen i select a movie and click to play or to change the subtitles i have this error

https://gist.github.com/anonymous/b0ee4616fa29e2251422

I'm using ubuntu 15.04 

Regards

**Comment by OstlerDev** [comment]
Thanks for pointing that out! It looks like I forgot to add a few packages to the package.json file. I will push up an update right now.

In the meantime you can run the following commands:

```
npm install xmlrpc
npm install g
npm install lodash
```

**Comment by brunojalves** [comment]
Thanks, 
i need to run this to:
npm install q 


By the way, i can change the subtitles but wen i play the movie have this error

Debug: Query: {"torrent":"https://yts.to/torrent/download/FA8F6D21EEB3948B8497439B4D540294C42653DF.torrent","id":"4094","title":"Kingsman: The Secret Service","desc":"Based upon the acclaimed comic book and directed by Matthew Vaughn, Kingsman: The Secret Service tells the story of a super-secret spy organization that recruits an unrefined but promising street kid into the agencys ultra-competitive training program just as a global threat emerges from a twisted tech genius.","poster":"https://s.ynet.io/assets/images/movies/kingsman_the_secret_service_2014/medium-cover.jpg","subtitle":"http://dl.opensubtitles.org/en/download/filead/src-api/vrf-5ebbcc535a/sid-265r1d7jbhugm9mfjeqmj0v4d3/1954758851.srt","UDID":"C1MN93VPFF54"}
Debug: === Starting MoviePlay.xml Generation ===
Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
Web: /Movies/MoviePlay.xml
Debug: [0%] Downloaded 0.02MB - 0MB/s | Peers: 0 Seeds: 48 | ETA: 33587.8m
Streamer: Ready to Stream, binding to http://192.168.7.22:9999
Debug: === Ending MoviePlay.xml Generation ===
Debug: <?xml version="1.0" encoding="UTF-8"?>
<atv><body><videoPlayer id="com.sample.video-player"><httpFileVideoAsset id="Kingsman: The Secret Service"><mediaURL>http://192.168.7.22:9999/4094.mp4</mediaURL><title>Kingsman: The Secret Service</title><description>Based upon the acclaimed comic book and directed by Matthew Vaughn, Kingsman: The Secret Service tells the story of a super-secret spy organization that recruits an unrefined but promising street kid into the agencys ultra-competitive training program just as a global threat emerges from a twisted tech genius.</description><image>https://s.ynet.io/assets/images/movies/kingsman_the_secret_service_2014/medium-cover.jpg</image><videoPlayerSettings><subtitleSize>100</subtitleSize></videoPlayerSettings><myMetadata><subtitleURL>http://trailers.apple.com/subtitle.json?url=http://dl.opensubtitles.org/en/download/filead/src-api/vrf-5ebbcc535a/sid-265r1d7jbhugm9mfjeqmj0v4d3/1954758851.srt</subtitleURL></myMetadata></httpFileVideoAsset></videoPlayer></body></atv>
Debug: [0%] Downloaded 2.02MB - 0.12MB/s | Peers: 0 Seeds: 45 | ETA: 268.4m
Debug: Query: {"level":"Debug","log":"willStartPlaying/getVideoPlayerSettings done"}
Debug: Query: {"url":"http://dl.opensubtitles.org/en/download/filead/src-api/vrf-5ebbcc535a/sid-265r1d7jbhugm9mfjeqmj0v4d3/1954758851.srt"}
Debug: === Starting subtitle.json Generation ===
Debug: === Getting and Parsing SRT ===
Debug: http://dl.opensubtitles.org/en/download/filead/src-api/vrf-5ebbcc535a/sid-265r1d7jbhugm9mfjeqmj0v4d3/1954758851.srt
Web: /subtitle.json
Debug: [0%] Downloaded 8.36MB - 0.51MB/s | Peers: 0 Seeds: 45 | ETA: 65.5m
Debug: Query: {"level":"Debug","log":"updateMetadata/getMetadata done"}
Debug: Query: {"level":"Debug","log":"subtitleURL: http://trailers.apple.com/subtitle.json?url=http://dl.opensubtitles.org/en/download/filead/src-api/vrf-5ebbcc535a/sid-265r1d7jbhugm9mfjeqmj0v4d3/1954758851.srt"}
Debug: Query: {"level":"Debug","log":"updateMetadata done"}
Debug: Query: {"level":"Debug","log":"willStartPlaying/createSubtitleView done"}
Debug: Query: {"level":"Debug","log":"willStartPlaying done"}
/home/ipbrick/Documents/Bruno/PopCorn/Pop AppleTV/PopcornTV-master1/SubtitleAPI.js:174
                timePart = ItemPart[1].replace(/\s/g, '').split(/:|,|-->/);
                                      ^
TypeError: Cannot read property 'replace' of undefined
    at /home/ipbrick/Documents/Bruno/PopCorn/Pop AppleTV/PopcornTV-master1/SubtitleAPI.js:174:39
    at Array.forEach (native)
    at Request._callback (/home/ipbrick/Documents/Bruno/PopCorn/Pop AppleTV/PopcornTV-master1/SubtitleAPI.js:172:22)
    at Request.self.callback (/home/ipbrick/Documents/Bruno/PopCorn/Pop AppleTV/PopcornTV-master1/node_modules/request/request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/ipbrick/Documents/Bruno/PopCorn/Pop AppleTV/PopcornTV-master1/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/ipbrick/Documents/Bruno/PopCorn/Pop AppleTV/PopcornTV-master1/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

**Comment by OstlerDev** [comment]
I just was testing and got this error too. OpenSubtitles went down around 30 minutes ago, and it looks like they changed their API.

Now instead of linking to the SRT file, some links produce a link instead. 

Example: http://dl.opensubtitles.org/en/download/filead/src-api/vrf-28ef9f577c/sid-bqeorncscs5upt78cgl0q3h7u4/1954779205.srt

Produces: http://www.opensubtitles.org/en/subtitles/6198726/get-hard-en#rate

I will look into this in the morning, but it looks like they just broke the system that I just implemented.
