### ISSUE TITLE
Recent Update Causing Issues?

### ISSUE THREAD

**Issue by JakeRound** [OstlerDev/PopcornTV#60]
PopcornTV.log - https://gist.github.com/JakeRound/058ab4daa0d304670671
aTVSettings.json - Blank File?

The process i've taken
Open Trailers App > Select Movies / TV Show's > Chose a video to watch > Crashes and receive the error "Trailers is unavailable. Try again later. (Meaning the terminal command sudo node atv.js needs to be re run.

A possible error as i hadn't had an issue with previous versions? PS Keep up the awesome work ;)

**Comment by OstlerDev** [comment]
Try deleting the blank 'aTVSettings.json' file.

**Comment by JakeRound** [comment]
Still seems to be outputting a blank document? Should i create a new install?
https://gist.github.com/JakeRound/12600d9d11ceeedf08a2

**Comment by OstlerDev** [comment]
I am looking into this now, I should be able to fix this in 1-2 minutes and push up an update.

**Comment by JakeRound** [comment]
Resolved thanks!

**Comment by OstlerDev** [comment]
Glad that it fixed it for you! I am planning on releasing v0.1.5 later tonight/tomorrow so I need all the testing I can get for now.

**Comment by JakeRound** [comment]
Of course! I'm happy to report any bugs i come across.

I take it that there isn't away around many of tv shows that show "Unsupported File Type" something out of your control?

**Comment by OstlerDev** [comment]
Right now the only way around the unsupported file type is to convert it while its being downloaded. I have a plan for this using FFMPEG, but that will need to wait for another day. (Watch #3 for more information)
