### ISSUE TITLE
Crash on selecting movie

### ISSUE THREAD

**Issue by seeitbelieveit** [OstlerDev/PopcornTV#61]
Trying to select Gascoigne under Recently Released resulted in this log
https://gist.github.com/seeitbelieveit/38c89a616618e5a4b03d

**Comment by OstlerDev** [comment]
This is a rare error, but is very hard to reproduce. If you restart PopcornTV then you most likely not going to see the same error

**Comment by seeitbelieveit** [comment]
I'm able to reproduce it everytime

**Comment by OstlerDev** [comment]
Testing now.

**Comment by OstlerDev** [comment]
I have figured that this happens if the URL is null when passed into the fanart generator, I am pushing up a patch for this now.
