### ISSUE TITLE
Pressing play crashes atv.js

### ISSUE THREAD

**Issue by seeitbelieveit** [OstlerDev/PopcornTV#62]
South Park s18e9 pressing Play generates
https://gist.github.com/seeitbelieveit/fd940881124c83cfb6e8

**Comment by OstlerDev** [comment]
Looks like it was happening because there was a "#"

Pushing up a commit to fix that now.

**Comment by seeitbelieveit** [comment]
I'm still getting a crash after using 'git pull'

**Comment by OstlerDev** [comment]
Make sure to restart the application as well as go out of the Episode view and back in.

**Comment by seeitbelieveit** [comment]
Restarted, exited all the way to atv home screen, and went back, still having the issue

**Comment by OstlerDev** [comment]
Try stopping the application, pulling, then restarting again. It is working on my end so I am not sure why it is crashing for you. Are you still getting the same error?

**Comment by seeitbelieveit** [comment]
Did as instructed.

Debug: Query: {"id":"tt0121955","UDID":"F6MPJ0FBFF54","title":""}
Debug: === Starting MoviePlay.xml Generation ===
Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
Web: /Movies/MoviePlay.xml
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open 'undefined'
    at Error (native)
Is the error

**Comment by OstlerDev** [comment]
Can you try restarting your Apple TV?

**Comment by seeitbelieveit** [comment]
Still crashing, going to try a fresh clone

**Comment by seeitbelieveit** [comment]
That didn't work either...

**Comment by OstlerDev** [comment]
Hmm, seems to be not working again for me, I will look into it and make another commit once I figure it out.
