### ISSUE TITLE
Unable to access anything under movies after commit 7979231cf1e9e64845e57cc8521e6f1cf39816ec

### ISSUE THREAD

**Issue by seeitbelieveit** [OstlerDev/PopcornTV#63]
https://gist.github.com/seeitbelieveit/06c0b85664b2526553e4

**Comment by seeitbelieveit** [comment]
Fixed with a fresh clone, unsure of what actual issue was.

**Comment by seeitbelieveit** [comment]
Issue returns with second selection of movie title

**Comment by OstlerDev** [comment]
What movies are you selecting?

**Comment by seeitbelieveit** [comment]
Recently Added>Maggie

Now unable to even access maggie again

**Comment by OstlerDev** [comment]
I will test it in the morning.

**Comment by seeitbelieveit** [comment]
This is on OS X Yosemite also

**Comment by OstlerDev** [comment]
Could be a posible duplicate of #15 please pull down the latest and try again.

**Comment by OstlerDev** [comment]
Fixed in commit 2ac3a94d11090e7e7eaa7de0d5672e089570cf6e

**Comment by seeitbelieveit** [comment]
yeah its fixed, thanks
