### ISSUE TITLE
Subs showing wrong (encoding issue)

### ISSUE THREAD

**Issue by NicoMag** [OstlerDev/PopcornTV#68]
Hi, 
I tried lots of movies and some symbols with accent like à, è, etc... are show with a big "?" instead.
You can try on Gone Girl with french subs, the right beginning of the movie is showing it easily

**Comment by pitercio** [comment]
The encoding is working here for spanish subs (tested on "Get Hard", read "El último año" perfectly written on my TV in the early 5 mins). Fantastic!! :)

**Comment by OstlerDev** [comment]
This issue occurs when the subtitles are encoded with Ansi instead of UTF-8. I am looking into work arounds, but have none yet other than individually parsing and replacing the affected characters.

**Comment by OstlerDev** [comment]
As for now I am going to mark this as won't fix and close this as there is no clear thing I can do that would easily fix this issue. If someone would like to help please feel free to comment or make a pull request.

**Comment by OstlerDev** [comment]
Why we cannot re-encode: http://stackoverflow.com/questions/2674411/convert-iso-windows-charsets-to-utf-8-in-javascript

**Comment by Sudden78** [comment]
Hi 
Is this something that can help you?
It´s from popcorntime source generic.js

convert: function (data, cb) { // Converts .srt's to .vtt's
            try {
                var srtPath = data.path;
                var vttPath = srtPath.replace('.srt', '.vtt');
                var srtData = fs.readFileSync(srtPath);
                self.decode(srtData, data.language, function (srtDecodedData) {
                    captions.srt.parse(srtDecodedData, function (err, vttData) {
                        if (err) {
                            return cb(err, null);
                        }
                        // Save vtt as UTF-8 encoded, so that foreign subs will be shown correctly on ext. devices.
                        fs.writeFile(vttPath, captions.vtt.generate(captions.srt.toJSON(vttData)), 'utf8', function (err) {
                            if (err) {
                                return cb(err, null);
                            } else {
                                cb(null, {
                                    vtt: vttPath,
                                    srt: srtPath,
                                    encoding: 'utf8'
                                });
                            }
                        });
                    });
                });
            } catch (e) {
                win.error('error converting subtitles', e);
                cb(e, null);
            }
        },
        // Handles charset encoding
        decode: function (dataBuff, language, callback) {
            var targetEncodingCharset = 'utf8';

            var charset = charsetDetect.detect(dataBuff);
            var detectedEncoding = charset.encoding;
            win.debug('SUB charset detected: ', detectedEncoding);
            // Do we need decoding?
            if (detectedEncoding.toLowerCase().replace('-', '') === targetEncodingCharset) {
                callback(dataBuff.toString('utf8'));
                // We do
            } else {
                var langInfo = App.Localization.langcodes[language] || {};
                win.debug('SUB charset expected for \'%s\': ', language, langInfo.encoding);
                if (langInfo.encoding !== undefined && langInfo.encoding.indexOf(detectedEncoding) < 0) {
                    // The detected encoding was unexepected to the language, so we'll use the most common
                    // encoding for that language instead.
                    detectedEncoding = langInfo.encoding[0];
                }
                win.debug('SUB charset used: ', detectedEncoding);
                dataBuff = iconv.encode(iconv.decode(dataBuff, detectedEncoding), targetEncodingCharset);
                callback(dataBuff.toString('utf8'));
            }
        }

    });

    App.Subtitles = {
        Generic: new Subtitles()
    };
})(window.App);


They convert to UTF-8

**Comment by OstlerDev** [comment]
Not sure if this would work but I will look into it.

**Comment by brauliotejeda** [comment]
This issue it should be open, only need to fix this for the app be perfect. Thanks for a such great work.

**Comment by brauliotejeda** [comment]
I think that would be of help see the code of the app Beamer.

**Comment by shali3** [comment]
@OstlerDev I'm working on a fix right now. I'll send a pull request once I'm done.

**Comment by Sudden78** [comment]
Ok perfect

**Comment by shali3** [comment]
DONE. Works like a charm ;)

**Comment by Sudden78** [comment]
Perfect i will test it in the weekend

Skickat från min iPhone

**Comment by pitercio** [comment]
Thank you!! I'll try it as soon as I get home :)



—
Enviado desde Mailbox

**Comment by Sudden78** [comment]
Works fine for Swedish subs.

Was som problem geting it to work.
Needed to update NPM to gett ICONV to work.

To update NPM i needed to install PYTHON and Microsoft Visual Studio C++ 2012 Express version.

Then everything worked fine.
