### ISSUE TITLE
I get error 109 when I try to add profile

### ISSUE THREAD

**Issue by elfeffe** [OstlerDev/PopcornTV#69]
I get some warnings when I try to install
npm WARN package.json PopcornTV@0.1.3 No repository field.
npm WARN package.json PopcornTV@0.1.3 No license field.

But this seems to be working
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.100:53
Web: listening on 192.168.1.100:80
Web: SSL Web: listening on 192.168.1.100:443

And it has some traffic from akamai when I use Apple TV
But I can't add the profile, I get error 109. And Trailers section doesn't work.

**Comment by OstlerDev** [comment]
Are you running on Mac or Windows? There could be a possibility that the certificates were generated incorrectly.

**Comment by elfeffe** [comment]
No, it was Nginx.
I had Nginx enabled in port 80 :(
Is there any way to change the port?

**Comment by OstlerDev** [comment]
You can change the port that Nginx runs on, but PopcornTV requires port 80. You can setup fancy port redirection, but I cannot provide any support for that.
