### ISSUE TITLE
atv.js crash after stream close

### ISSUE THREAD

**Issue by coolmase** [OstlerDev/PopcornTV#70]
First of all, loving your work!

When a stream is closed, so after hitting the Menu button or when the stream stops at the end of the movie/show, atv.js crashes in my setup. It happens with all streams. Could you see what's going wrong? Thanks!

Debug: Streamer: Stream Closed
Debug: ====== Keep Movies is Off, Deleting Files ======
Debug: Deleting 4240.mp4
Debug: Deleting tt1442437.mp4
Debug: Deleting assets/torrent-stream//0aedb8fcca64cfb4506b12f82d069755f138e3e2/
Paul Blart Mall Cop 2 (2015) [1080p]/Paul.Blart.Mall.Cop.2.2015.1080p.BluRay.x26
4.YIFY.mp4
fs.js:711
  return binding.rmdir(pathModule._makeLong(path));
                 ^
Error: ENOTEMPTY, directory not empty 'C:\Users\M\Desktop\PopcornTV-master\asset
s\torrent-stream\0aedb8fcca64cfb4506b12f82d069755f138e3e2\Paul Blart Mall Cop 2
(2015) [1080p]'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:711:18)
    at deleteFolderRecursive (C:\Users\M\Desktop\PopcornTV-master\webserver.js:6
05:8)
    at C:\Users\M\Desktop\PopcornTV-master\webserver.js:599:9
    at Array.forEach (native)
    at deleteFolderRecursive (C:\Users\M\Desktop\PopcornTV-master\webserver.js:5
96:26)
    at C:\Users\M\Desktop\PopcornTV-master\webserver.js:599:9
    at Array.forEach (native)
    at deleteFolderRecursive (C:\Users\M\Desktop\PopcornTV-master\webserver.js:5
96:26)
    at null.<anonymous> (C:\Users\M\Desktop\PopcornTV-master\webserver.js:82:9)
 
C:\Users\M\Desktop\PopcornTV-master>

Links:
extra log from command prompt: https://gist.github.com/f762777f252e5104f753.git
popcornTV log: https://gist.github.com/7f03bbf2cac94e38518a.git
settings file: https://gist.github.com/2b3f433217192faa73d8.git

**Comment by OstlerDev** [comment]
Looks like there is an issue with the recursive deleter in windows. As a temporary fix just turn "Keep Movies" to on from the settings page of the Apple TV (still inside the PopcornTV application).

I will look into it when I get some time.

**Comment by coolmase** [comment]
Alright, will give that a try. Thanks!
