### ISSUE TITLE
can't create certificate

### ISSUE THREAD

**Issue by grcn** [OstlerDev/PopcornTV#72]
hi,

i got this error code when applied your solution #11 

TypeError: Cannot read property 'certificate' of undefined
    at C:\Users\b2\Desktop\PopcornTV\atv.js:11:62
    at C:\Users\b2\Desktop\PopcornTV\node_modules\pem\lib\pem.js:238:24
    at C:\Users\b2\Desktop\PopcornTV\node_modules\pem\lib\pem.js:146:24
    at C:\Users\b2\Desktop\PopcornTV\node_modules\pem\lib\pem.js:67:20
    at C:\Users\b2\Desktop\PopcornTV\node_modules\pem\lib\pem.js:754:20
    at C:\Users\b2\Desktop\PopcornTV\node_modules\pem\lib\pem.js:733:13
    at C:\Users\b2\Desktop\PopcornTV\node_modules\pem\lib\pem.js:640:20
    at C:\Users\b2\Desktop\PopcornTV\node_modules\pem\lib\pem.js:786:20
    at F (C:\Users\b2\Desktop\PopcornTV\node_modules\pem\node_modules\which\whic
h.js:40:25)
    at E (C:\Users\b2\Desktop\PopcornTV\node_modules\pem\node_modules\which\whic
h.js:43:29)

C:\Users\b2\Desktop\PopcornTV>C:\OpenSSL-Win32\bin\openssl.exe req -new -nodes -
newkey rsa:2048 -out C:\trailers.pem -keyout C:\trailers.key -x509 -days 7300 -s
ubj "/C=US/CN=trailers.apple.com" -config C:\OpenSSL-Win32\bin\openssl.cfg
Loading 'screen' into random state - done
Generating a 2048 bit RSA private key
.....................................................+++
................................................................................
....+++
writing new private key to 'C:\trailers.key'
C:\trailers.key: Permission denied
1032:error:02001005:system library:fopen:Input/output error:.\crypto\bio\bss_fil
e.c:391:fopen('C:\trailers.key','wb')
1032:error:20074002:BIO routines:FILE_CTRL:system lib:.\crypto\bio\bss_file.c:39
3:

**Comment by JakeRound** [comment]
Hey Grcn!

Please follow the [Wiki](https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue) guidelines on how to report a bug, it only makes it easier for Skylar to figure out whats gone wrong. :+1: 

Thanks

**Comment by OstlerDev** [comment]
This has to do with you not starting up command prompt in administrator mode, please try that and report back.
