### ISSUE TITLE
After watching a movie, server disconnects itself. 

### ISSUE THREAD

**Issue by Mehmeed** [OstlerDev/PopcornTV#76]
So after finishing this movie, i was going to play another movie. but it was stuck on "accessing trailers" screen. When i checked my computer, there was nothing going on. so i had to run popcorntv again.
here's the log. http://pastebin.com/PUDrgRxY

**Comment by OstlerDev** [comment]
This seems to be an issue with Windows, on the settings page of PopcornTV change the "Keep Movie Downloads" to "On". This will fix the issue until I can push up a patch.

**Comment by Mehmeed** [comment]
Alrighty thanks

**Comment by OstlerDev** [comment]
Duplicate of #70
