### ISSUE TITLE
Issue with installing latest version.

### ISSUE THREAD

**Issue by Mehmeed** [OstlerDev/PopcornTV#78]
So i saw that you have added the feature to reduce subtitle size. And i was trying to install the latest version to get that feature. As always i deleted the old folder and downloaded master branch. but i kept getting this error. Any idea what is it?
http://pastebin.com/WzLM6B60

**Comment by OstlerDev** [comment]
Ah, looks like I forgot to add that package to the ``package.json`` file, manually run the command below to fix it for now:

```
npm install winston-loggly
```

I will push up a commit when I get home from work to fix this for everyone.

**Comment by CodyClark** [comment]
@Mehmeed I was just receiving this error also. I just ran the install command winston-loggly

**Comment by CodyClark** [comment]
AND @OstlerDev beat me to the punch.

**Comment by OstlerDev** [comment]
Thanks @CodyClark for offering support :)

Loggly automatically sends the error logs to me so that I can fix errors before they are even reported :)

**Comment by CodyClark** [comment]
@OstlerDev nice. No problem man. This application is awesome. Thanks for creating it!

**Comment by Mehmeed** [comment]
hah ohh thank you all. I'm not too good with codes, sorry for asking too much.

**Comment by OstlerDev** [comment]
No problem guys! If you find any new bugs/errors, or if you just have an awesome suggestion please let me know! I do my best in the spare time I have to add to this application and make it as amazing as I can.
