### ISSUE TITLE
Ability to Run Duel Apple TV's off one Web Server?

### ISSUE THREAD

**Issue by JakeRound** [OstlerDev/PopcornTV#82]
Hey Ostler, I had a question about running the web server let's say on a Raspberry Pi (in my planned case) Would it be possible to have two Apple TV's running on the same network to connect to one server?

**Comment by OstlerDev** [comment]
I have made it in such a way that it can run multiple Apple TV's completely separately. The only issue I think you might experience could happen when you try to stream two videos at the same time. Feel free to try it and let me know how it goes!

If you are unable to stream two movies/videos at the same time let me know so I can push up an update.

**Comment by JakeRound** [comment]
Thanks! I'll look into it. It was planned to have multiple Apple TV's setup around the house because of PopcornTV. Feel free to close this issue now as i'm not planning on picking up the additional apple tv for another week.

**Comment by OstlerDev** [comment]
@JakeRound let me know when you are able to test this, for now I am closing this issue.
