### ISSUE TITLE
Subtitle is not synchronized with the film

### ISSUE THREAD

**Issue by Ashwien** [OstlerDev/PopcornTV#84]
Hello OstlerDev,

I do not know if anyone has this problem, but when I am playing a movie. Sometimes subtitles are displayed even before the dialogues in the movie are spoken. This happens with the follow films:
- Focus (Dutch subtitles) 
- wyrmwood (Dutch and English subtitles)
- Chappie (Dutch and English subtitles) 

Movies as Fast 6,Dark Summer, Captain America: The Winter Soldier are just working great!

Is there a way to fix this? Thanks in advance.

PS. Is there a way to see how good the torrent health (tracker health) is?

Thanks!

Greetz,

Ashwien

**Comment by OstlerDev** [comment]
This happens because some movies are encoded differently, adding a few seconds to the start or end. This happens because the subtitles are created for a different version of the same movie. Currently we are searching for the movie on OpenSubtitles using the IMDB ID, this gives us more results then using something such as "yifysubtitles.com".

**Comment by OstlerDev** [comment]
As for the torrent health, on movies you can see a colored dot displayed next to the quality, that shows the torrent health. For TV Shows since it is only a magnet link I cannot easily pull the health right now.

**Comment by Ashwien** [comment]
Thanks for your quick reply. I get it, thanks for explaining. 

As for the torrent health, I always see a green dot, but still sometimes I can't stream the movie.

Thanks for your efforts!

**Comment by OstlerDev** [comment]
If you can see a green dot there is a good seeder to peer ratio, which is how the health is calculated. At that point it could be your internet speed capping you.

You are welcome, enjoy!
