### ISSUE TITLE
Trailers is unavailable

### ISSUE THREAD

**Issue by CodyClark** [OstlerDev/PopcornTV#86]
I have routinely been getting the trailers is unavailable message when accessing it on my apple TV. I'm not sure if the issue could be related to PopcornTv or not. Is anyone else experiencing this issue? Is there a quick workaround? I have been unplugging my appleTV and that seems to resolve it but I am looking for a more elegant solution. Thanks! Keep up the great work!

**Comment by OstlerDev** [comment]
What pages are you experiencing this on?

**Comment by CodyClark** [comment]
I'm unable to get into the trailers "app". If I re-add the profile on the apple TV that seems to fix it.

**Comment by OstlerDev** [comment]
Hmm, it could be that the profiles are not being saved correctly.

**Comment by OstlerDev** [comment]
Are you still able to reproduce this?

**Comment by Uokereh** [comment]
IT WORKS!
thank you - keep up the work!
