### ISSUE TITLE
Bug report for TV conversion in latest version

### ISSUE THREAD

**Issue by JakeRound** [OstlerDev/PopcornTV#89]
PopcornTV.log
https://gist.github.com/JakeRound/0e53523496a3c24a3a35
aTVSettings.json
https://gist.github.com/JakeRound/07502ebc35f89f619d56

Process 
Start web server > Navigate to TV > Dexter > Season 1 > Episode 3 > 'An error occurred loading this content'

**Comment by OstlerDev** [comment]
Do you have ffmpeg installed?

**Comment by JakeRound** [comment]
I've only used git to pull their latest version, unsure if i've missed a step out or something.
git clone git://source.ffmpeg.org/ffmpeg.git ffmpeg

**Comment by OstlerDev** [comment]
That is not the best way to install it, the way that I suggest is by following this guide that I just put on the wiki: https://github.com/OstlerDev/PopcornTV/wiki/How-to-install-FFMPEG

The guide kinda sucks right now, but I do not have much time to write it. Another thing you can attempt. Is to download a static binary then put it inside the PopcornTV folder (this would be the best option).

**Comment by JakeRound** [comment]
Ahh thanks! Didn't see that you had added a basic post on the wiki, i'll try things out and let you know if i have any success.

**Comment by OstlerDev** [comment]
No problem, I just added it just now. Just let me know.

**Comment by JakeRound** [comment]
Outstanding work! While the loading seems to take a little longer compared to Movies possibly because i have to be connected to a VPN to access movies & tv shows in the UK as the API's are blocked it works! I take it that running this on a Raspberry Pi is highly unlikely as ffmpeg is CPU intensive? Just a bug i think i noticed that when watching a stream, 8 minuets in on the walking dead to test this out i received an error, i think this is repeatable would you like a log?

Debug: [20%] Downloaded 459.02MB - 0.57MB/s | Peers: 0 Seeds: 8 | ETA: 52m
Debug: Streamer: Stream Closed

**Comment by OstlerDev** [comment]
FFMPEG can be CPU intensive but the way I have it running you might be able to run it on a Raspberry Pi.  If you can get it to repeat itself that would be great, which guide for FFMPEG did you install and test?

Also, please make sure that if you are running it on a Raspberry Pi that you are either running it as root (you can use "sudo" in order to run it as root if you are on another account). I am getting thousands of automatic error reports per hour from someones Raspberry Pi because they are not running the script as root.

**Comment by JakeRound** [comment]
I assumed so, i wanted to setup more of a permanent solution rather than running on my primary laptop, more like a server 24/7. Seems like it was just a one off being the TV series Arrow, Episode 1 Pilot haven't end's 10 seconds into streaming may possible be an issue with the torrent? The same sudden stop happened in the walking dead but i wasn't able to repeat it. 

I actually don't own a Raspberry Pi yet just looking into permanent solutions, i'm assuming those error reports are a pain in the ass :grin: 

Attached Log
Process = TV Shows > Arrow > Season 1 > Pilot 
https://gist.github.com/JakeRound/1f8edf041354b63f8cfa

**Comment by OstlerDev** [comment]
If it ends early then it is an issue with not downloading fast enough. I am currently limiting ffmpeg as much as I can, if it happens you can attempt to stream again, but it might not make much of a difference, there is just not enough seeders to download from.

I don't think that a Raspberry Pi is powerful enough, but I may test it to find out.

Also, Arrow is an awesome TV show.

**Comment by JakeRound** [comment]
Ahh i thought that might be the issue, i've switched my VPN width a much better download speed now (using a VPN because all API's are blocked in the UK now getting around 15 up and 15 down. Sucks using a VPN simply because my home connection speeds are around 40 up and 40 down. Yeah i started to assume that it wasn't going to be powerful enough.

I was told by a friend to watch it! Something i'm going to watch after i've finished up watching Dexter hehe.

https://gist.github.com/JakeRound/382d422b4c72c9e4ee9b

**Comment by JakeRound** [comment]
@OstlerDev Hai, mind if i ask about  if you had any success with the ffmpeg conversion on the raspberrypi? Thanks.
