### ISSUE TITLE
Stuck on adding trailers profile on ATV

### ISSUE THREAD

**Issue by domidyon** [OstlerDev/PopcornTV#90]
Hi!

Everything works fine in the process of installation, but the trailers profile takes ages to add. How long is it supposed to take? I changed my DNS now to the right IP which I did wrong in the first place, but now its just stuck at ''adding profile''..

Any ideas?

**Comment by OstlerDev** [comment]
Looks like you must not still be running PopcornTV. You need to be running the application at all times when you want to use it.

**Comment by domidyon** [comment]
@OstlerDev First of all, thanks for the quick response time! I must say, I have no idea what I am doing. How do I know when PopcornTV is actually running?

**Comment by OstlerDev** [comment]
You will still have the terminal/command prompt open. It will display that it is running. If you close that window then you stopped it from running.

**Comment by domidyon** [comment]
I just restarted terminal and ran the command, now I can't bind to port 53, the error;
error: ========= FATAL ERROR =========
error: Cannot bind to Port 53. Please make sure you are not running a DNS server on your machine!
error: Error Code: EADDRINUSE
error: ===============================

It started fine the first time I tried. I'm sorry if I sounds like a clueless dickhead right now, but that's because I am..

**Comment by OstlerDev** [comment]
Try restarting your computer and trying again.

**Comment by domidyon** [comment]
Alright, done that. I don't get the error anymore. I now get this;

notice: Starting PopcornTV
DNS: DnsProxy binding on xxxxxx
Web: listening on xxxxxxxx
Web: SSL Web: listening on xxxxxxx

I assume that means its running now, but I still can't install the profile. It just stucks at 'adding profile'.

**Comment by OstlerDev** [comment]
Are you changing your DNS to the correct address that it shows it is binding to?

**Comment by domidyon** [comment]
I got it working, the DNS was entered incorrect. I feel like a major dumbass now. Thanks for your help, and I'm going to enjoy the crap out of this! Im going to get a wallet for bitcoins to support this! :+1:

**Comment by OstlerDev** [comment]
Glad to hear that you enjoy the project! It is still in development so be sure to post any bugs you find!

Any donations made really help, all time I devote is 100% unpaid so far.
