### ISSUE TITLE
Excuse the silly questions, but...

### ISSUE THREAD

**Issue by ssurfong** [OstlerDev/PopcornTV#91]
I have it working and realise Popcorn needs to be running, but can I move the 'PopcornTV' folder from my Desktop to somewhere else? And do I need to keep Terminal running as well or can I quit out with just Popcorn running. Thanks in advance and GREAT WORK!

**Comment by OstlerDev** [comment]
You can move it to wherever you want, just know that the 'cd' command is going to change.

Also, anytime you want to use features on your Apple TV you need to make sure that PopcornTV is running OR that you change the DNS of the Apple TV.
