### ISSUE TITLE
Mac Installation Problem

### ISSUE THREAD

**Issue by Uokereh** [OstlerDev/PopcornTV#92]
hey i don't know if i'm missing some steps but i am having a really hard time getting this done on a Mac and Windows. I am trying to follow the steps you have listed but its still quiet difficult for someone less adventurous. 

i keep getting 'npm'  command not recognized when i run the sudo npm install line.

PLEASE HELP

**Comment by OstlerDev** [comment]
You are getting that because you have not installed Node.js. As it says on the "How To Install" page, Node.js is a prerequisite: https://github.com/OstlerDev/PopcornTV/wiki/How-to-Install

Just download and install Node.js from here: https://nodejs.org/

**Comment by Uokereh** [comment]
I followed that instruction 

first i downloaded the PopcornTV.zip and extracted it to the Decktop
then i downloaded Github and installed it to my system.
next i opened Terminal on Mac and entered
 “ cd Desktop ” 
“ git clone https://github.com/OstlerDev/PopcornTV.git <https://github.com/OstlerDev/PopcornTV.git>"
it ran and said done.

then i started to follow the Mac installation process - but when i get to 
“sudo npm install” i get the error: "sudo: npm: command not found”

i don’t know what I’m doing wrong and how to processed - what am i missing?

**Comment by OstlerDev** [comment]
Did you make sure to install Node.js like I specifically said in the last post? Your instructions that you responded with are saying that you didnt.

When you run the command: ``node`` in your terminal what pulls up?

**Comment by Uokereh** [comment]
ok that seems to be my mistake, how exactly do i install node?

**Comment by OstlerDev** [comment]
On this page there is an install button right in the middle of it: https://nodejs.org/

Download that then install it like you would for any other application.

**Comment by Uokereh** [comment]
THANKS! i got pass that step.

now I’m getting this:
MacBook-Pro:PopcornTV ujuchrisokereh$ sudo node atv.js
warning: SSL Certificate does not exist, Please restart PopcornTV once the process ends!

**Comment by OstlerDev** [comment]
As it says, "Please restart PopcornTV once the process ends!"

Seeing as the process ended, please start PopcornTV again.

**Comment by Uokereh** [comment]
sorry I’m a dummying at these thing - so basically now i close the Cmd Terminal and start over?

**Comment by OstlerDev** [comment]
Yes, or just type ``sudo node atv.js`` again.

**Comment by Uokereh** [comment]
its Adding the Profile now - hope it works!

**Comment by Uokereh** [comment]
hey it doesn’t seem to be playing the tv shows

all I’m getting is Trailers is unavailable each time i try to play something on my appleTV

**Comment by OstlerDev** [comment]
Please follow the guide on [How to Report an Issue](https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue).
