### ISSUE TITLE
VPN on Windows does not work.

### ISSUE THREAD

**Issue by sonnyvision** [OstlerDev/PopcornTV#94]
Hello,
Im using a vpn client on the computer where I have installed popcorntv. With the vpn off I can see popcorntv show up on the apple tv. When I switch on the vpn it doesn't work anymore. My question is is there anything I can exclude from the vpn tunnel for it to work?

**Comment by OstlerDev** [comment]
It should work out of the box with the VPN, are you still seeing DNS requests inside the terminal?

What VPN are you using?

**Comment by Uokereh** [comment]
I am still unable to watch any tv shows on PopcornTV on my apple tv, has anyone figured out this issue?

**Comment by sonnyvision** [comment]
No as soon as I turned on the vpn I see no more request inside the terminal.

**Comment by sonnyvision** [comment]
I'm using Astrill

**Comment by JakeRound** [comment]
I'm using a paid VPN, haven't had an issue at all.

**Comment by sonnyvision** [comment]
Ok any tips for troubleshooting my issue?

**Comment by JakeRound** [comment]
Yeah sure, follow the Wiki's process of reporting a bug, take a look here https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue and i'll try solve your issue. Feel free to post the error log (PopcornTV.log & aTVSettings.json) in this issue thread. So i can take a look. :smiley:

**Comment by sonnyvision** [comment]
Hi JakeRound,
Here is popcorntv.log while reproducing the issue:
2015-07-11T18:11:24.419Z - notice: Started logger in Debug mode!
2015-07-11T18:11:24.446Z - notice: Starting PopcornTV
2015-07-11T18:11:24.460Z - DNS: DnsProxy binding on 192.168.2.124:53
2015-07-11T18:11:27.613Z - Web: listening on 192.168.2.124:80
2015-07-11T18:11:27.626Z - Web: SSL Web: listening on 192.168.2.124:443

Basically it does not receive any dns request while the vpn is ON and the atv says trailers not available. 
If the VPN is off it works then no problem. I can see the menu and covers on the tv and the console feels up with requests.
Here is the atvsettings.json:
{
    "C07N94PXFF54": {
        "quality": "720p",
        "fanart": "On",
        "subtitle": "Off",
        "keep": "Off"
    }
}

I'm sure it's something stupid but can't figure it out!!

**Comment by OstlerDev** [comment]
It could be possible that your VPN is either blocking ports that are needed or it is redirecting ports elsewhere.

**Comment by sonnyvision** [comment]
For info it works fine on my Mac. Problem is only with my windows machine. Both computers are running the same astrill vpn.

**Comment by OstlerDev** [comment]
It looks like the protocol is being run differently on Windows. I am not sure if windows has built in VPN support, so it might be that botching the results. I will look into this regardless.

**Comment by OstlerDev** [comment]
@sonnyvision Are you still having this issue? Is it just happening with that one VPN provider?

**Comment by sonnyvision** [comment]
To be honest I haven't tried with any other vpn providers. It's still work quite well on the mac though. If you happen to know any other good vpn providers I would be happy to test it.

**Comment by JakeRound** [comment]
@sonnyvision Personally i use https://www.privateinternetaccess.com they've got pretty decent download speeds 30mbps, also you can change between any of the VPN servers around the world. Would recommend only if your willing to pay the £3 or so

**Comment by OstlerDev** [comment]
One VPN provider I use is hotspotshield.com I am not sure if it would work for PopcornTV, but it is worth a try.

I am going to close this for now as I believe it is just dependent on how this one application goes about their VPN protocol, and sadly is external from this program.
