### ISSUE TITLE
TV Shows not playing on PopcornTV

### ISSUE THREAD

**Issue by Uokereh** [OstlerDev/PopcornTV#95]
![image](https://cloud.githubusercontent.com/assets/12503400/8632650/a7c7ea3e-2772-11e5-9746-525798de3a09.png)

**Comment by Uokereh** [comment]
![image](https://cloud.githubusercontent.com/assets/12503400/8632651/bbeee616-2772-11e5-92da-be5a966d78f4.png)

**Comment by OstlerDev** [comment]
Follow the guide on the wiki to install FFMPEG.

**Comment by Uokereh** [comment]
i’ve install the FFMPEG file into the PopcornTV folder, the tv shows  are starting to playing now but it crashes and returns to the play menu. basically it doesn’t play through out, it stops right after it starts.
